/* L11 — corrección de todas las alertas medias de Laboral (DLA/DPL).
 * Conserva el problema jurídico y la explicación/fuente de cada registro; reconstruye alternativas
 * para eliminar pistas de longitud, citas aisladas y distractores débiles.
 * No constituye verificación jurídica humana: fuente.verificada permanece false.
 */
(function(root){'use strict';
function p(correcta,distractores,pos){const xs=distractores.slice(0,3);xs.splice(pos,0,correcta);return{opciones:xs.map((text,i)=>({id:'ABCD'[i],text})),respuesta:pos,dificultad:'media-alta'};}
const L11_OVERRIDES=Object.freeze({
'pf93-dla-01-01':p('Debe examinarse la protección de la vida privada y demás derechos fundamentales dentro de la relación laboral',['Debe prevalecer la potestad de control empresarial cuando la comunicación se realiza mediante dispositivos utilizados para trabajar','Debe considerarse suficiente la propiedad del empleador sobre los equipos para excluir el examen de necesidad y proporcionalidad de la medida','Debe analizarse sólo la existencia de una cláusula contractual de control, aunque su aplicación concreta afecte ámbitos protegidos del trabajador'],0),
'pf93-dla-01-02':p('Impide diferencias carentes de justificación legítima en el acceso, desarrollo o término de la relación laboral',['Impide utilizar requisitos objetivos relacionados con la naturaleza de una función cuando ellos sean necesarios para ejecutar el trabajo convenido','Permite diferencias fundadas en categorías protegidas cuando se informan previamente a quienes postulan al puesto respectivo','Limita la igualdad al período posterior a la contratación y deja fuera las etapas de selección y acceso al empleo'],1),
'pf93-dla-01-03':p('Debe analizarse idoneidad, necesidad y proporcionalidad de la medida, además de la habilitación jurídica pertinente',['Debe bastar que la medida contribuya de algún modo al fin empresarial aunque exista una alternativa menos lesiva igualmente eficaz','Debe preferirse la medida que reduzca costos operacionales aun cuando la afectación del derecho resulte intensa frente al beneficio obtenido','Debe descartarse cualquier medida organizativa que incida en un derecho, aunque la limitación esté justificada y respete sus presupuestos'],2),
'pf93-dla-01-04':p('Busca otorgar tutela jurisdiccional frente a vulneraciones de derechos fundamentales ocurridas en el ámbito laboral',['Busca sustituir las acciones de cobro de remuneraciones mediante un procedimiento especial para cualquier deuda derivada del contrato','Busca trasladar al juez laboral todas las controversias sindicales aunque no exista una lesión de derechos comprendida por el procedimiento','Busca sancionar penalmente al empleador por toda infracción contractual que afecte de alguna forma los intereses del trabajador'],3),
'pf93-dla-02-01':p('Debe comprobarse prestación personal, remuneración y subordinación o dependencia atendiendo a la realidad del vínculo',['Debe atenderse principalmente a la denominación escrita que las partes asignaron al negocio, aunque los servicios se ejecuten bajo control permanente','Debe considerarse decisiva la emisión de documentos tributarios, con independencia de las instrucciones, horario y supervisión observados en la práctica','Debe calificarse según la profesión del prestador, porque determinadas actividades se consideran independientes por su naturaleza aunque exista subordinación'],0),
'pf93-dla-02-02':p('Son relevantes, apreciados en conjunto, el control, las instrucciones, el horario, la continuidad y la inserción organizacional',['Es suficiente comprobar que la persona utiliza uniforme corporativo, aunque organice libremente su actividad y no reciba instrucciones de ejecución','Resulta decisivo el lugar físico donde se presta el servicio, de modo que trabajar fuera del establecimiento excluye por sí mismo subordinación','Debe atenderse principalmente a la duración temporal del vínculo, porque una relación prolongada se transforma en laboral aunque falten indicios de dirección'],1),
'pf93-dla-03-02':p('En suministro la EST pone trabajadores a disposición de una usuaria; en subcontratación el contratista organiza la obra por su cuenta y riesgo',['En subcontratación la empresa principal asume directamente la posición de empleador y en suministro la EST se limita a una función de intermediación comercial','Ambas figuras suponen que la empresa usuaria organiza permanentemente al personal y se diferencian sólo por la duración de los servicios contratados','El suministro consiste en encargar una obra autónoma al contratista, mientras la subcontratación exige poner trabajadores a disposición directa de la principal'],2),
'pf93-dla-03-03':p('Permiten controlar obligaciones laborales y previsionales y vincular ese control con el régimen de responsabilidad de la empresa principal',['Permiten a la empresa principal sustituir al contratista como empleador respecto de todas sus decisiones de organización y disciplina de los trabajadores','Permiten excluir la responsabilidad de la principal por el solo hecho de solicitar información, aun cuando no adopte las medidas que el régimen contempla','Permiten modificar las remuneraciones pactadas por el contratista cuando la principal estime necesario ajustar los costos de ejecución de la obra'],3),
'pf93-dla-03-04':p('Debe analizarse la realidad del vínculo, la organización del contratista y quién ejerce efectivamente funciones propias del empleador',['Debe atenderse únicamente al contrato comercial suscrito entre las empresas, porque su denominación determina la naturaleza de todas las relaciones de trabajo','Debe presumirse válida la tercerización aunque la principal imparta directamente instrucciones permanentes y el contratista carezca de estructura propia','Debe trasladarse el conflicto a sede civil por existir dos empresas, sin examinar la dirección efectiva de los trabajadores involucrados'],0),
'pf93-dla-04-01':p('Las facultades de dirección están limitadas por el ordenamiento, el contrato y los derechos fundamentales del trabajador',['Las facultades de dirección permiten alterar condiciones esenciales cuando la medida mejore la productividad aunque no exista habilitación para modificar el contrato','Las instrucciones empresariales prevalecen sobre restricciones contractuales mientras se dicten dentro del establecimiento y se comuniquen formalmente','Los derechos fundamentales operan fuera del trabajo y sólo limitan al empleador cuando la conducta no guarda relación con la organización productiva'],1),
'pf93-dla-04-02':p('Debe existir un fin legítimo y la medida debe resultar idónea, necesaria y proporcional dentro del marco laboral aplicable',['Debe bastar que la medida de vigilancia sea técnicamente posible y útil para la empresa aunque exista otra alternativa menos intensa para el trabajador','Debe admitirse el control fuera del tiempo y lugar de trabajo cuando la empresa pueda relacionar la información obtenida con alguna finalidad organizativa','Debe considerarse irrelevante informar sobre el mecanismo de control cuando la medida se aplica del mismo modo a todas las personas de la organización'],2),
'pf93-dla-04-03':p('No; la modificación unilateral sólo puede operar dentro de las facultades y presupuestos que el ordenamiento autoriza',['Sí; el poder de mando permite alterar condiciones pactadas cuando el empleador estime que existe una razón productiva suficientemente importante','Sí; la falta de reclamo inmediato del trabajador transforma cualquier modificación unilateral en una estipulación contractual plenamente válida','No; las condiciones pactadas son absolutamente inmutables incluso cuando las partes acuerdan posteriormente una modificación lícita del contrato'],3),
'pf93-dla-05-01':p('Supone servicios personales remunerados prestados bajo subordinación o dependencia de quien los recibe',['Supone una prestación de servicios autónoma en que quien ejecuta el trabajo conserva íntegramente la organización y riesgo de su actividad','Supone una transferencia patrimonial a cambio de un precio, sin relevancia de instrucciones o inserción en la organización de otra persona','Supone una actividad personal realizada gratuitamente dentro de una estructura empresarial y sometida a directrices de quien recibe la prestación'],0),
'pf93-dla-05-02':p('La falta de escrituración no elimina una relación laboral existente, aunque genera consecuencias probatorias y sancionatorias',['La ausencia de documento impide reconocer el vínculo aunque los servicios hayan sido personales, remunerados y ejecutados bajo subordinación efectiva','La falta de firma transforma el vínculo en una sociedad entre las partes hasta que se otorgue el instrumento escrito exigido para el contrato','La omisión de escrituración priva al tribunal de competencia para declarar la relación y obliga al trabajador a regularizarla administrativamente primero'],1),
'pf93-dla-05-04':p('Resulta relevante la irrenunciabilidad de los derechos laborales en los términos en que el sistema limita su disposición',['Resulta aplicable una autonomía privada plena que permite renunciar anticipadamente a cualquier derecho si la cláusula fue aceptada al contratar','Resulta aplicable la prescripción, porque una renuncia anticipada produce el mismo efecto que dejar transcurrir el plazo para ejercer una acción','Resulta aplicable la libertad de empresa como regla que permite desplazar mediante acuerdo individual los mínimos establecidos para proteger al trabajador'],2),
'pf93-dla-06-01':p('Debe identificarse el régimen aplicable, sus eventuales exclusiones o sistemas especiales y la jornada máxima vigente en la fecha',['Debe utilizarse la jornada máxima que existía al inicio del contrato, aunque reformas posteriores hayan modificado gradualmente el límite aplicable','Debe atenderse a la jornada que el empleador comunique unilateralmente para el período examinado, aunque exceda los máximos del régimen vigente','Debe calcularse según la antigüedad del trabajador, porque el límite máximo disminuye automáticamente a medida que aumenta la duración del vínculo'],3),
'pf93-dla-06-03':p('No; el sobretiempo está sujeto a acuerdo, finalidad, límites y temporalidad dentro del régimen de horas extraordinarias',['Sí; las partes pueden transformar el sobretiempo en jornada ordinaria permanente mientras exista un consentimiento contractual expreso y escrito','Sí; la necesidad productiva del empleador permite mantener horas extraordinarias indefinidamente si la remuneración incorpora el recargo respectivo','No; las horas extraordinarias están excluidas de la relación laboral y cualquier prestación sobre la jornada ordinaria debe compensarse sólo con descanso'],0),
'pf93-dla-06-04':p('Dificulta controlar y probar jornada, descansos y sobretiempo y puede implicar incumplimiento de los deberes de registro aplicables',['La deficiencia convierte el vínculo en uno sin jornada y permite presumir que el trabajador organiza libremente todo su tiempo de prestación','La falta de registro transforma automáticamente las horas discutidas en tiempo de descanso y excluye el pago de cualquier diferencia por sobretiempo','El problema incide sólo en la administración interna de la empresa y carece de relevancia para acreditar la duración efectiva de la prestación'],1),
'pf93-dla-07-02':p('No; los descuentos requieren una fuente admitida y deben respetar las condiciones y límites aplicables a la remuneración',['Sí; el empleador puede descontar cualquier deuda que atribuya al trabajador si la informa en la liquidación correspondiente antes del pago','Sí; una instrucción de jefatura constituye fundamento suficiente para compensar unilateralmente créditos de la empresa contra la remuneración','No; la remuneración no admite descuento alguno, incluso respecto de retenciones u obligaciones cuya deducción está expresamente prevista'],2),
'pf93-dla-07-03':p('Debe atenderse a su naturaleza y a la definición y exclusiones del régimen de remuneraciones, no sólo al nombre asignado',['Debe atenderse exclusivamente a que la prestación se denomine bono, asignación o beneficio, porque la denominación contractual define su naturaleza','Debe considerarse remuneración únicamente cuando el pago se entrega físicamente en dinero y no cuando adopta otra forma de contraprestación','Debe depender de la decisión unilateral del empleador, quien puede definir el carácter remuneracional de cada prestación al incorporarla a la liquidación'],3),
'pf93-dla-07-04':p('Permite informar y acreditar haberes, descuentos y monto pagado, facilitando el control del cumplimiento remuneracional',['Reemplaza el contrato individual porque contiene los elementos económicos esenciales de la relación y puede suplir las demás estipulaciones pactadas','Extingue acciones posteriores respecto del pago aunque existan diferencias o errores que no hayan sido advertidos al momento de recibir el comprobante','Autoriza descuentos que de otro modo no serían procedentes cuando éstos aparecen individualizados y el trabajador recibe el documento sin formular reserva'],0),
'pf93-dla-08-02':p('Busca proteger salud, maternidad, paternidad, infancia y conciliación dentro de los supuestos y condiciones del régimen aplicable',['Busca sancionar económicamente a la empresa durante el período en que la persona deja de prestar servicios por causas familiares protegidas','Busca extinguir temporalmente todas las obligaciones derivadas del contrato, incluidas aquellas que subsisten durante una suspensión de prestación','Busca transferir el contrato a una persona sustituta mientras dure la licencia, de modo que quien utiliza el permiso pierde su posición contractual'],1),
'pf93-dla-08-04':p('Debe reconocer el permiso cuando concurren sus presupuestos y aplicar las reglas específicas sobre duración y efectos',['Debe negarlo cuando la necesidad familiar se produce fuera del lugar de trabajo, porque esas circunstancias pertenecen a la esfera privada del trabajador','Debe exigir una renuncia temporal al empleo para que la ausencia no se considere incumplimiento de la obligación principal de prestar servicios','Debe imputar el permiso a vacaciones aun cuando el régimen especial establezca un derecho distinto y no exista acuerdo para utilizar feriado'],2),
'pf93-dla-09-01':p('Debe contrastarse la causal con los hechos comunicados, las formalidades exigibles y los antecedentes que la sustenten',['Debe bastar que la comunicación mencione una disposición de término, aunque los hechos descritos no permitan relacionarla con la causal invocada','Debe atenderse a la preferencia del empleador por concluir el vínculo, porque la existencia de una causal formal excluye revisar sus presupuestos fácticos','Debe requerirse aceptación del trabajador como condición general de eficacia del despido, aunque el término se funde en una causal unilateral prevista'],3),
'pf93-dla-09-02':p('Corresponde examinar el despido indirecto si el incumplimiento empresarial encaja en una causal y se cumplen sus requisitos',['Corresponde tratarlo como renuncia ordinaria aunque la decisión del trabajador se funde en un incumplimiento grave atribuido al empleador','Corresponde calificarlo como huelga individual, pues la suspensión de servicios por incumplimiento empresarial constituye una medida de presión colectiva','Corresponde considerarlo mutuo acuerdo si el empleador discute la gravedad de su incumplimiento aunque nunca haya consentido en terminar el contrato'],0),
'pf93-dla-09-05':p('Debe solicitarse previamente la autorización judicial de desafuero cuando la causal invocada se encuentra sometida a ese requisito',['Debe comunicarse primero el despido y solicitar la autorización una vez terminado el vínculo para que la sentencia convalide retroactivamente la decisión','Debe obtenerse autorización de la organización sindical o de los restantes trabajadores antes de presentar una solicitud ante el tribunal competente','Debe prescindirse del desafuero cuando la carta de término describe detalladamente los hechos y el empleador considera acreditada la causal invocada'],1),
'pf93-dla-10-02':p('El empleador conserva los deberes legales de seguridad y salud, adaptados a las condiciones de la prestación remota',['El trabajador asume íntegramente esos deberes porque el empleador carece de control material sobre el domicilio o lugar elegido para prestar servicios','La empresa que provee conexión a internet pasa a ser responsable de las condiciones de seguridad por facilitar el medio técnico de trabajo a distancia','Las obligaciones preventivas se suspenden mientras el trabajo se realiza fuera de dependencias empresariales y se reactivan al volver a modalidad presencial'],2),
'pf93-dla-10-03':p('Protege un período de descanso en que no existe obligación de atender comunicaciones u órdenes laborales en los casos aplicables',['Permite interrumpir indefinidamente la prestación durante cualquier jornada si el trabajador declara que necesita un período personal de desconexión','Prohíbe utilizar herramientas digitales dentro de la relación laboral, aunque las comunicaciones se realicen durante el tiempo de prestación convenido','Autoriza al empleador a contactar fuera de jornada sin límites cuando el trabajador dispone de un teléfono o dispositivo proporcionado por la empresa'],3),
'pf93-dla-11-01':p('Comprende constituir organizaciones, afiliarse, desafiliarse y decidir no incorporarse, dentro del marco de libertad sindical',['Comprende el deber de incorporarse al sindicato con mayor representación cuando la empresa inicia un proceso de negociación colectiva reglada','Comprende una prohibición de renunciar a la afiliación durante la vigencia de cualquier instrumento colectivo suscrito por la organización respectiva','Comprende la facultad empresarial de determinar qué organización resulta más adecuada para representar a los trabajadores de una misma faena'],0),
'pf93-dla-11-03':p('Se comprometen la libertad sindical y la prohibición de interferencias o prácticas antisindicales contra la afiliación',['Se compromete principalmente el derecho de propiedad sobre el puesto de trabajo, porque la afiliación convierte la relación laboral en un derecho real','Se compromete la competencia territorial del tribunal, pues la afiliación sindical modifica el lugar donde deben discutirse futuras controversias','Se compromete únicamente la autonomía contractual individual, sin incidencia sobre la dimensión colectiva de los derechos de organización sindical'],1),
'pf93-dla-12-01':p('Debe cumplirse el régimen de quórum, asamblea, estatutos y formalidades de constitución que corresponda a la organización',['Debe obtenerse autorización previa del empleador, porque la constitución dentro de la empresa requiere consentimiento de quien organiza la actividad','Debe existir una sentencia judicial constitutiva que otorgue personalidad a la organización antes de que sus integrantes puedan elegir directiva','Debe lograrse aprobación unánime de la dotación de trabajadores aunque el régimen reconozca quórums específicos según el tipo de sindicato'],2),
'pf93-dla-12-04':p('No; la elección y administración interna pertenecen a la autonomía sindical y no quedan entregadas al empleador',['Sí; la empresa puede designar autoridades cuando financia actividades sindicales o facilita infraestructura para el funcionamiento de la organización','Sí; la dirección empresarial puede intervenir si considera que una decisión interna del sindicato afecta la productividad del establecimiento','No; la intervención sólo se encuentra limitada durante la huelga y vuelve a ser posible en los demás períodos de la relación colectiva'],3),
'pf93-dla-13-01':p('Busca que los sujetos colectivos acuerden condiciones comunes de trabajo y remuneración dentro del marco aplicable',['Busca reemplazar las normas imperativas por acuerdos colectivos incluso cuando ellas establecen mínimos indisponibles para quienes negocian','Busca resolver responsabilidad penal por hechos ocurridos en la empresa mediante acuerdos vinculantes entre la organización y el empleador','Busca transferir participación en la propiedad empresarial a quienes negocian como consecuencia necesaria de alcanzar un instrumento colectivo'],0),
'pf93-dla-13-02':p('Deben identificarse sujetos habilitados, oportunidad, instrumento vigente y reglas procedimentales aplicables a la negociación',['Debe atenderse sólo al número total de trabajadores de la región, dato que define por sí mismo el procedimiento y los plazos de negociación','Debe obtenerse autorización jurisdiccional antes de presentar el proyecto, aun cuando los sujetos y la oportunidad cumplan las reglas del procedimiento','Debe considerarse la opinión de clientes y proveedores sobre la conveniencia de iniciar negociación como antecedente de habilitación del proceso colectivo'],1),
'pf93-dla-13-03':p('Regula condiciones comunes durante su vigencia respecto de quienes quedan afectos, conforme a su contenido y al régimen aplicable',['Deroga las disposiciones laborales que regulaban esas materias y mantiene ese efecto aun después de terminar la vigencia del instrumento colectivo','Se extiende por sí mismo a toda persona que preste servicios en la empresa, aunque no exista una regla o mecanismo que la incorpore a sus efectos','Carece de fuerza obligatoria y funciona sólo como pauta para futuros contratos individuales que las partes pueden aceptar o rechazar libremente'],2),
'pf93-dla-14-01':p('Deben verificarse la etapa de negociación, la votación, el quórum y los demás requisitos que condicionan su ejercicio',['Basta la decisión de una sola persona afiliada para iniciar una huelga de la organización cuando existe una negociación colectiva pendiente','Se requiere autorización unilateral del empleador porque la suspensión colectiva de servicios modifica temporalmente la prestación convenida','Se necesita una sentencia civil firme que declare agotadas todas las posibilidades de acuerdo antes de realizar la votación de huelga'],3),
'pf93-dla-14-02':p('No; las interferencias ilegítimas pueden constituir prácticas antisindicales o desleales según su configuración concreta',['Sí; durante una huelga las facultades empresariales se amplían para neutralizar los efectos de la suspensión colectiva sobre la actividad productiva','Sí; las represalias son admisibles si la empresa acredita que buscan reducir la duración del conflicto y recuperar la operación ordinaria','No; la empresa queda privada de toda facultad organizativa durante la huelga aunque ésta no interfiera con el ejercicio legítimo de la libertad sindical'],0),
'pf93-dla-14-03':p('Buscan proteger bienes y necesidades legalmente relevantes mediante una continuidad limitada que no vacíe el derecho de huelga',['Buscan mantener la producción ordinaria de la empresa con una dotación equivalente a la existente antes de que comenzara la suspensión colectiva','Buscan reemplazar a quienes participan en la huelga para que el conflicto no produzca consecuencias económicas durante el período de negociación','Buscan impedir la negociación cuando la actividad empresarial presta un servicio relevante, sustituyendo el procedimiento colectivo por continuidad completa'],1),
'pf93-dla-15-01':p('Debe analizarse si la entrega constituye una interferencia antisindical o una práctica desleal según finalidad, contexto y tipo aplicable',['Debe examinarse únicamente si el beneficio tiene valor económico elevado, porque los incentivos menores carecen de aptitud para afectar libertad sindical','Debe trasladarse la cuestión a sede penal cuando el beneficio se ofrece durante negociación, sin analizar previamente el régimen de prácticas colectivas','Debe considerarse una liberalidad empresarial neutra por el solo hecho de entregarse individualmente, aunque su finalidad sea desincentivar la afiliación'],2),
'pf93-dla-15-04':p('Busca restablecer el ejercicio de libertad sindical y aplicar las consecuencias previstas frente a interferencias ilegítimas',['Busca privar al empleador de sus facultades de dirección respecto de todas las personas de la empresa aunque no exista conexión con la conducta infractora','Busca transformar la organización sindical en un órgano estatal para asegurar que sus decisiones futuras queden sujetas a control administrativo externo','Busca resolver exclusivamente diferencias individuales de remuneración y deja fuera las conductas que interfieren con organización y acción colectiva'],3),

'pf93-dpl-01-03':p('No; la competencia laboral deriva del régimen legal y no puede desplazarse libremente a cualquier tribunal por cláusula contractual',['Sí; la autonomía contractual permite elegir cualquier tribunal civil si la estipulación fue incorporada al contrato antes del surgimiento del conflicto','Sí; basta que ambas partes mantengan silencio al presentar la demanda para que un tribunal sin competencia laboral adquiera facultades sobre la materia','No; toda controversia laboral debe someterse a arbitraje y por esa razón tampoco puede radicarse convencionalmente ante un tribunal civil ordinario'],0),
'pf93-dpl-01-04':p('Debe calificar cada pretensión y aplicar las reglas especiales de competencia y acumulación que articulen sus materias',['Debe enviar la totalidad a sede penal si alguna pretensión menciona incumplimientos previsionales, aunque el objeto perseguido sea patrimonial y laboral','Debe elegir el tribunal según la pretensión de mayor cuantía económica, prescindiendo de la materia y de las reglas especiales aplicables','Debe separar necesariamente todas las pretensiones aunque el sistema admita que materias relacionadas sean conocidas o ejecutadas de forma coordinada'],1),
'pf93-dpl-02-01':p('La función jurisdiccional corresponde al juez o jueces que integran el tribunal conforme a la organización establecida',['La jurisdicción corresponde al administrador, que puede decidir el fondo cuando la controversia no exige recibir prueba testimonial en audiencia','La función jurisdiccional se distribuye entre atención de público y administración según el tipo de escrito que origine la causa laboral','La Inspección del Trabajo ejerce jurisdicción sobre el tribunal durante la etapa inicial y luego transfiere la competencia al juez para dictar sentencia'],2),
'pf93-dpl-02-02':p('Gestiona recursos y apoyo operativo del tribunal sin sustituir la potestad jurisdiccional reservada al juez',['Puede revisar y modificar sentencias cuando detecta errores que afectan los indicadores de gestión o el cumplimiento de metas institucionales','Resuelve los recursos contra decisiones judiciales de primera instancia cuando la controversia se refiere sólo a organización interna del tribunal','Puede adoptar decisiones jurisdiccionales urgentes por delegación general del juez cuando la carga de audiencias supera la capacidad diaria del tribunal'],3),
'pf93-dpl-02-03':p('La oralidad y concentración del proceso exigieron una estructura con apoyo administrativo especializado para las audiencias',['La reforma se basó en sustituir las audiencias por expedientes íntegramente escritos y en reservar el contacto con las partes para la etapa de sentencia','La organización moderna eliminó la separación entre administración y jurisdicción para que los funcionarios puedan resolver cuestiones del proceso oral','El modelo se diseñó para reemplazar al juez por mediadores privados en la mayoría de los conflictos y reservar la jurisdicción a casos excepcionales'],0),
'pf93-dpl-03-02':p('Concentra recepción de prueba, observaciones y actuaciones destinadas a dejar el litigio en estado de decisión',['Se limita a recibir la demanda y contestación, dejando la producción de los medios probatorios para una etapa escrita posterior al cierre de la audiencia','Tiene por finalidad principal ejecutar créditos reconocidos, por lo que la discusión declarativa debe haber terminado antes de iniciar esta audiencia','Reabre una mediación administrativa obligatoria y posterga el debate ante el juez hasta que las partes acrediten haber agotado una nueva instancia externa'],1),
'pf93-dpl-03-03':p('Debe aplicarse el régimen especial de caducidad y considerar las incidencias temporales que el sistema contemple para esa acción',['Debe tramitarse el fondo sin examinar el plazo porque la naturaleza laboral del derecho impide que una acción se extinga por caducidad procesal','Debe aplicarse el plazo civil ordinario a toda acción laboral, aunque el régimen especial establezca una oportunidad distinta para la pretensión ejercida','Debe convertir la presentación tardía en reclamo administrativo y suspender el proceso judicial hasta que la autoridad administrativa resuelva su procedencia'],2),
'pf93-dpl-03-04':p('La prueba se aprecia mediante sana crítica y la sentencia debe expresar las razones relevantes de esa valoración',['La prueba se somete a una tarifa rígida que asigna prevalencia necesaria a documentos firmados sobre declaraciones rendidas directamente en audiencia','El juez puede decidir según una convicción personal no explicitada si escuchó directamente toda la prueba y las partes formularon observaciones finales','La prueba aportada por el empleador posee preferencia cuando existe documentación empresarial, salvo que el trabajador presente un instrumento público contrario'],3),
'pf93-dpl-04-02':p('Busca uniformar la interpretación jurídica cuando concurren decisiones distintas sobre una materia de derecho y sus demás requisitos',['Busca repetir íntegramente la actividad probatoria para que el tribunal superior establezca nuevamente los hechos antes de interpretar la norma discutida','Busca sustituir cualquier recurso ordinario aun cuando no exista contraste entre interpretaciones jurisprudenciales sobre la materia jurídica sometida','Busca controlar actos administrativos generales de la autoridad laboral aunque no exista una sentencia laboral susceptible del mecanismo de unificación'],0),
'pf93-dpl-04-03':p('Debe identificar causal, vicio, influencia sustancial y petición concreta, además de cumplir los presupuestos procesales del recurso',['Debe expresar sólo desacuerdo con el resultado, porque corresponde al tribunal superior seleccionar la causal de nulidad que mejor se ajuste al caso','Debe incorporar hechos nuevos no debatidos para demostrar que el juez habría decidido de otro modo si hubiera conocido antecedentes posteriores al juicio','Debe solicitar una revisión completa del mérito probatorio como si se tratara de una segunda instancia ordinaria, sin vincular el agravio a una causal'],1),
'pf93-dpl-04-04':p('No; el alcance depende del recurso y causal y no configura por regla general una segunda instancia plena sobre toda la prueba',['Sí; la interposición de cualquier recurso laboral permite reabrir hechos, recibir nueva prueba y sustituir la valoración realizada por el juez de juicio','Sí; el tribunal superior puede revisar libremente el mérito de todos los antecedentes aunque el recurso se funde en una infracción jurídica específica','No; la revisión de prueba se encuentra totalmente excluida incluso cuando la causal invocada cuestiona la forma en que la sentencia razonó sobre ella'],2),
'pf93-dpl-05-02':p('Debe relacionar la conducta denunciada con el derecho afectado y aportar los antecedentes requeridos por el régimen probatorio de tutela',['Debe acreditar únicamente el monto de su remuneración, porque la existencia de una diferencia económica permite presumir vulneración de derechos fundamentales','Debe demostrar afiliación sindical como requisito común a todas las acciones de tutela, aunque el derecho invocado no tenga relación con libertad sindical','Debe acompañar una condena penal previa contra el empleador, pues la tutela sólo se abre cuando la conducta vulneratoria ya fue calificada en otra sede'],3),
'pf93-dpl-05-03':p('Permite someter la sanción administrativa al control jurisdiccional dentro del procedimiento y plazo que resulten aplicables',['Permite convertir la multa laboral en una pena privativa de libertad para que el tribunal evalúe nuevamente la gravedad de la infracción sancionada','Permite impedir que la autoridad administrativa fiscalice nuevamente a la empresa mientras exista cualquier reclamación judicial pendiente sobre una multa','Permite trasladar al tribunal una negociación colectiva no relacionada con la sanción para resolver conjuntamente todas las diferencias entre empresa y trabajadores'],0),
'pf93-dpl-06-03':p('Debe existir un título ejecutivo previsional y concurrir los demás presupuestos que habilitan el despacho de la cobranza',['Basta la afirmación del trabajador respecto de cotizaciones impagas aunque todavía no exista antecedente al que el sistema atribuya fuerza ejecutiva','Debe acompañarse una querella penal contra el empleador, porque la cobranza previsional presupone responsabilidad criminal por la falta de pago','Debe acreditarse previamente que el empleador posee inmuebles suficientes para responder, pues sin bienes raíces la obligación no puede ejecutarse'],1),
'pf93-dpl-06-04':p('Porque la cobranza presupone un título y obligación ejecutable; una controversia constitutiva puede requerir antes la vía declarativa correspondiente',['Porque el tribunal de cobranza carece de toda competencia en materia laboral y sólo puede intervenir respecto de obligaciones tributarias firmes','Porque la existencia de una relación laboral se presume negada cuando el empleador la discute y no puede declararse judicialmente por ningún procedimiento','Porque los procedimientos de cobranza se reservan a sanciones penales y no permiten perseguir obligaciones patrimoniales derivadas del trabajo'],2)
});
function patchArray(bank){if(!Array.isArray(bank))return 0;let n=0;for(let i=0;i<bank.length;i++){const patch=L11_OVERRIDES[bank[i]?.id];if(!patch)continue;bank[i]={...bank[i],...patch,fuente:{...bank[i].fuente,verificada:false},revisionOrigen:'AUDITORIA_MEDIA_LABORAL_L11',reemplazoEditorial:true,revisionL11:true};n++;}return n;}
let appliedL11=0;try{if(typeof PF93_DRAFT_LABORAL!=='undefined')appliedL11+=patchArray(PF93_DRAFT_LABORAL);}catch(_){appliedL11=-1;}
const previous=root.PF93_REVIEW_WORKFLOW||{};root.PF93_REVIEW_WORKFLOW=Object.freeze({...previous,L11_OVERRIDES,appliedL11});
})(typeof globalThis!=='undefined'?globalThis:window);