/* L10 — corrección de todas las alertas medias de Familia (DFA/DPFA).
 * Conserva el problema jurídico y la explicación/fuente de cada registro; reconstruye alternativas
 * para eliminar pistas de longitud, referencias aisladas y distractores débiles.
 * No constituye verificación jurídica humana: fuente.verificada permanece false.
 */
(function(root){'use strict';
function p(correcta,distractores,pos){const xs=distractores.slice(0,3);xs.splice(pos,0,correcta);return{opciones:xs.map((text,i)=>({id:'ABCD'[i],text})),respuesta:pos,dificultad:'media-alta'};}
const L10_OVERRIDES=Object.freeze({
'pf93-dfa-01-01':p('Deben concurrir los presupuestos de existencia y validez y no presentarse un impedimento aplicable',['Debe acreditarse una convivencia previa suficiente para demostrar estabilidad antes de celebrar el vínculo matrimonial','Debe comprobarse que las partes poseen bienes comunes que permitan organizar los efectos patrimoniales del matrimonio','Debe obtenerse una autorización jurisdiccional previa para toda celebración matrimonial entre personas plenamente capaces'],0),
'pf93-dfa-01-03':p('Debe examinarse la subsistencia del vínculo matrimonial anterior como impedimento para contraer uno nuevo',['Debe examinarse si la convivencia actual ha superado un período mínimo antes de iniciar una nueva relación matrimonial','Debe examinarse si existen bienes familiares declarados, porque su vigencia impide celebrar otro matrimonio','Debe examinarse si el nuevo matrimonio cuenta con aprobación judicial por existir previamente una relación afectiva formalizada'],1),
'pf93-dfa-01-05':p('Debe identificarse la causal de término invocada y cumplir las formalidades y comunicaciones exigibles para ella',['Basta una declaración privada entre los convivientes, aunque el mecanismo escogido requiera una actuación formal adicional','El término depende de una declaración judicial constitutiva en todas las hipótesis previstas para extinguir el acuerdo','La voluntad de una parte carece de efectos en el término del acuerdo mientras la otra no manifieste aceptación expresa'],2),
'pf93-dfa-02-01':p('Debe existir un menoscabo vinculado a menor desarrollo remunerado por dedicación al hogar o al cuidado familiar',['Debe existir una diferencia patrimonial entre los cónyuges al término de la relación, aunque no se conecte con la distribución de roles familiares','Debe existir un incumplimiento culpable de deberes matrimoniales que produzca un daño moral indemnizable al otro cónyuge','Debe existir una disminución de ingresos posterior a la separación, aunque durante el matrimonio ambos hayan desarrollado igual actividad laboral'],3),
'pf93-dfa-02-02':p('No; posee fundamento, presupuestos y criterios propios y no opera como reparación automática del fracaso matrimonial',['Sí; el término del matrimonio genera por sí solo un derecho indemnizatorio equivalente al daño moral propio de responsabilidad civil','Sí; corresponde a una modalidad de responsabilidad extracontractual que se configura por la sola diferencia patrimonial entre cónyuges','No; carece de naturaleza patrimonial y por ello sólo puede traducirse en medidas personales sin contenido económico'],0),
'pf93-dfa-02-03':p('Debe valorar las circunstancias legalmente relevantes y los hechos acreditados para decidir procedencia y cuantía',['Debe aplicar un porcentaje uniforme sobre el patrimonio de quien tenga mayores recursos para asegurar igualdad económica entre los ex cónyuges','Debe dividir por mitades el patrimonio acumulado durante la relación con independencia del régimen patrimonial que haya regido el matrimonio','Debe considerar como factor decisivo la edad de quien solicita la compensación, dejando los demás antecedentes como elementos secundarios'],1),
'pf93-dfa-03-01':p('Busca proteger la residencia principal de la familia sometiendo determinados actos a un régimen especial de disposición',['Busca transferir al cónyuge no propietario una cuota de dominio equivalente a la mitad del inmueble destinado a residencia familiar','Busca extinguir las garantías reales constituidas sobre el inmueble para asegurar que éste permanezca libre de gravámenes durante el matrimonio','Busca convertir el inmueble en un patrimonio separado administrado por el tribunal mientras subsista la vida familiar en común'],2),
'pf93-dfa-03-02':p('No; la afectación introduce limitaciones y efectos específicos sin transferir por sí sola el dominio del inmueble',['Sí; desde la declaración ambos cónyuges pasan a ser comuneros por partes iguales aunque sólo uno figure como propietario inscrito','Sí; la declaración atribuye a los hijos una participación dominical destinada a asegurar la continuidad de la residencia familiar','No; la declaración produce únicamente un efecto informativo y no altera las facultades de disposición del titular respecto del inmueble'],3),
'pf93-dfa-04-01':p('Debe identificarse el régimen patrimonial aplicable y la naturaleza u origen del bien cuya administración se discute',['Debe determinarse cuál cónyuge obtiene mayores ingresos, porque ese factor define la administración ordinaria de los bienes matrimoniales','Debe establecerse la duración del matrimonio, ya que después de cierto período todos los bienes pasan a una administración conjunta','Debe comprobarse si existen hijos comunes, porque su presencia modifica el régimen de administración patrimonial entre los cónyuges'],0),
'pf93-dfa-04-02':p('Cada cónyuge conserva en principio la administración y disposición de su propio patrimonio bajo las reglas aplicables',['Los bienes de ambos se integran en una masa común cuya administración corresponde conjuntamente a los cónyuges durante toda la vigencia','Los patrimonios permanecen separados, pero la disposición de cualquier bien requiere autorización del otro cónyuge con independencia de su origen','La separación afecta sólo los bienes adquiridos antes del matrimonio y los posteriores forman una comunidad patrimonial de pleno derecho'],1),
'pf93-dfa-04-04':p('No; el acuerdo posee un régimen patrimonial propio y no genera por sí mismo el estatuto de sociedad conyugal',['Sí; la celebración del acuerdo produce automáticamente una sociedad conyugal salvo declaración judicial posterior que disponga lo contrario','Sí; los convivientes pasan al régimen matrimonial de comunidad cuando adquieren cualquier bien durante la vigencia del acuerdo','No; el acuerdo excluye todo efecto patrimonial entre convivientes y por ello no admite ningún régimen relativo a bienes comunes'],2),
'pf93-dfa-05-01':p('Debe probarse el cese de convivencia por el período y bajo los presupuestos que correspondan a la causal ejercida',['Debe acreditarse únicamente que uno de los cónyuges desea poner término al vínculo, aunque no haya transcurrido período alguno de separación','Debe probarse la existencia de hijos comunes, porque el régimen de cese exige una relación familiar previa distinta del matrimonio mismo','Debe acompañarse una condena penal contra el otro cónyuge para que el cese de convivencia pueda producir efectos como causal de divorcio'],3),
'pf93-dfa-06-01':p('Debe examinarse una acción de reclamación de filiación atendiendo a la situación filial y legitimación del caso',['Debe utilizarse una acción reivindicatoria porque la determinación del vínculo persigue recuperar un estado civil indebidamente poseído por otro','Debe plantearse una tercería dentro de cualquier proceso patrimonial relacionado, pues la filiación opera como antecedente de derechos hereditarios','Debe ejercerse una acción de nulidad matrimonial, porque toda controversia filial exige revisar primero la validez de la relación de los progenitores'],0),
'pf93-dfa-06-04':p('Porque comprometen estado civil, identidad y relaciones familiares sometidas a reglas especiales de orden público',['Porque carecen de consecuencias patrimoniales y por ello sólo interesan a la esfera personal de quienes intervienen en el juicio','Porque pueden resolverse mediante acuerdos privados libres, sin necesidad de controlar legitimación ni efectos respecto de terceros','Porque se deciden sin actividad probatoria, atendiendo exclusivamente a la declaración de voluntad de quien reclama el vínculo'],1),
'pf93-dfa-07-02':p('No; la constitución de la adopción exige el procedimiento y la decisión de la autoridad competente en los términos aplicables',['Sí; un acuerdo privado basta cuando los adultos expresan voluntad coincidente y acreditan condiciones económicas suficientes para el cuidado','Sí; una escritura entre quienes entregan y reciben al niño produce el vínculo si posteriormente se informa administrativamente al tribunal','No; la adopción sólo puede existir respecto de personas adultas y por eso un contrato referido a un niño carece de toda consecuencia posible'],2),
'pf93-dfa-07-03':p('Debe comprobarse la situación jurídica habilitante del NNA y el cumplimiento de las garantías del procedimiento de adopción',['Debe comprobarse principalmente la capacidad económica de los solicitantes, pues ese antecedente basta para superar las restantes etapas del proceso','Debe determinarse la existencia de bienes a nombre del NNA, porque la situación patrimonial define si procede constituir una nueva filiación','Debe recabarse la opinión de terceros del entorno residencial de los solicitantes como condición sustitutiva de los presupuestos jurídicos de adopción'],3),
'pf93-dfa-07-04':p('Es incorrecto resolver la idoneidad sólo por capacidad económica, omitiendo aptitudes parentales y necesidades del NNA',['Es correcto considerar antecedentes personales y familiares que permitan valorar las capacidades de cuidado de quienes solicitan la adopción','Es correcto examinar la aptitud para ofrecer cuidado estable y responder de manera adecuada a las necesidades concretas del NNA','Es correcto orientar la evaluación por el interés superior del NNA y no por una preferencia abstracta de los adultos solicitantes'],0),
'pf93-dfa-08-01':p('Deben relacionarse las necesidades del alimentario con las facultades económicas y circunstancias del alimentante',['Debe considerarse únicamente el ingreso líquido del alimentante sin examinar necesidades ni otras circunstancias relevantes para la prestación','Debe atenderse de manera principal a la edad del alimentario, que determina por sí misma la cuantía exigible en cualquier relación alimentaria','Debe calcularse la prestación a partir del patrimonio total de ambos grupos familiares, distribuyéndolo proporcionalmente entre todos sus integrantes'],1),
'pf93-dfa-08-03':p('Debe examinarse una modificación de la pensión si variaron de modo relevante las necesidades o capacidades consideradas al fijarla',['Debe declararse nula la filiación que originó la prestación, porque el cambio de circunstancias elimina el fundamento jurídico de los alimentos','Debe mantenerse inalterada la pensión mientras subsista el mismo vínculo familiar, aunque cambien sustancialmente necesidades y capacidades económicas','Debe extinguirse la prestación y fijarse otra obligación desde cero, porque una pensión determinada previamente no admite adecuación posterior'],2),
'pf93-dfa-08-04':p('Deben utilizarse los mecanismos de cumplimiento y apremio previstos para la obligación alimentaria según sus presupuestos',['Debe crearse una medida no prevista cuando los mecanismos existentes parezcan insuficientes para asegurar el pago de las cuotas adeudadas','Debe darse por extinguida la deuda después de varios incumplimientos, pues la falta reiterada de pago transforma la obligación en inexigible','Debe convertir el incumplimiento en una sanción penal directa sin necesidad de aplicar el procedimiento y presupuestos previstos para cada consecuencia'],3),
'pf93-dfa-09-01':p('Debe primar el interés superior del niño valorado concretamente a partir de los criterios y antecedentes relevantes',['Debe preferirse al progenitor con mayores ingresos como criterio principal, porque la capacidad económica define por sí misma la calidad del cuidado','Debe aplicarse una preferencia basada en el sexo de uno de los progenitores cuando ambos presentan condiciones materiales semejantes','Debe seguirse la opinión de terceros del entorno familiar aunque no exista conexión con las necesidades y derechos concretos del niño'],0),
'pf93-dfa-09-02':p('No; el tribunal debe respetar los presupuestos y modalidades que el ordenamiento reconoce para establecer ese régimen',['Sí; el juez puede imponer cualquier modalidad que estime ideal aunque el sistema establezca condiciones específicas para su procedencia','Sí; el desacuerdo entre progenitores obliga a establecer el cuidado compartido como mecanismo ordinario para superar el conflicto parental','No; el cuidado compartido se encuentra excluido del sistema y por ello el tribunal no puede reconocerlo bajo ninguna circunstancia'],1),
'pf93-dfa-10-03':p('Debe escucharla y ponderarla según edad, madurez y circunstancias junto con los restantes antecedentes relevantes',['Debe seguir la opinión como una instrucción vinculante sin considerar otros elementos relativos al interés superior o a la protección del NNA','Debe prescindir de ella cuando exista discrepancia con la posición de alguno de los progenitores que participa en el procedimiento','Debe delegar la decisión jurídica al NNA una vez que éste expresa una preferencia suficientemente clara respecto del régimen de relación'],2),
'pf93-dfa-10-04':p('No; el conflicto patrimonial no basta para impedir la relación, que debe resolverse según sus propios presupuestos',['Sí; la existencia de deuda alimentaria produce por sí misma la suspensión del vínculo mientras no se pague íntegramente lo adeudado','Sí; el cumplimiento económico constituye la condición principal para mantener toda relación directa entre el NNA y el progenitor no cuidador','No; la relación debe mantenerse sin posibilidad de regulación aunque existan otros antecedentes serios de riesgo distintos del conflicto económico'],3),

'pf93-dpfa-01-01':p('La oficialidad y las facultades legales de dirección permiten al juez conducir activamente el procedimiento',['La pasividad judicial obliga al tribunal a limitarse a registrar las actuaciones que las partes decidan realizar en cada etapa del proceso','La autonomía privada de los litigantes permite definir las potestades de dirección que tendrá el juez para cada causa particular','La reserva procesal entrega al tribunal facultades para decidir sin audiencia cuando considere que la controversia requiere una conducción más intensa'],0),
'pf93-dpfa-01-02':p('Exige contacto directo del juez con las partes y con la prueba en las actuaciones decisivas del procedimiento',['Exige que las actuaciones relevantes se documenten sólo por escrito para que el juez pueda revisarlas sin contacto con quienes intervienen','Permite delegar la recepción de toda la prueba en funcionarios distintos del juez siempre que exista posteriormente un informe de lo actuado','Impide la comparecencia directa de las partes a las audiencias para preservar la neutralidad del tribunal respecto de sus declaraciones personales'],1),
'pf93-dpfa-01-04':p('Busca concentrar actuaciones en audiencias y reducir dispersión y demoras sin sacrificar garantías procesales',['Busca suprimir la rendición de prueba cuando el tribunal estime posible decidir con los antecedentes iniciales aportados por las partes','Busca impedir suspensiones aun cuando exista una causa legalmente justificada que haga necesaria la reprogramación de una audiencia','Busca convertir el procedimiento en una secuencia predominantemente escrita para reducir el número de comparecencias personales ante el juez'],2),
'pf93-dpfa-02-01':p('Asesora al juez con conocimiento técnico interdisciplinario sin ejercer por ello función jurisdiccional',['Sustituye al juez en la dictación de medidas cuando la controversia requiere conocimientos profesionales ajenos a la disciplina jurídica','Representa procesalmente a la parte que se encuentre en mayor situación de vulnerabilidad y formula pretensiones en su nombre durante la audiencia','Dirige de manera autónoma la investigación de los hechos y decide qué antecedentes deben excluirse antes de ser conocidos por el tribunal'],3),
'pf93-dpfa-02-03':p('Las unidades cumplen tareas de gestión y apoyo sin invadir las atribuciones jurisdiccionales reservadas al juez',['Las unidades administrativas pueden modificar resoluciones cuando la corrección permita mejorar la gestión de agenda y ejecución del tribunal','Los funcionarios de apoyo pueden decidir medidas cautelares urgentes si el juez no se encuentra disponible al momento de ingresar la solicitud','La administración puede sustituir al juez en períodos de sobrecarga para resolver cuestiones que no impliquen una sentencia definitiva'],0),
'pf93-dpfa-02-04':p('No; la recomendación técnica debe ser ponderada por el juez junto con el derecho y los demás antecedentes del caso',['Sí; el informe técnico tiene carácter vinculante porque la especialidad profesional del consejo prevalece sobre la apreciación jurisdiccional','Sí; la recomendación produce los mismos efectos de una decisión judicial cuando se adopta por acuerdo de todos los profesionales del consejo','No; el informe carece de valor para la decisión y debe excluirse del razonamiento judicial aunque verse sobre materias técnicas relevantes'],1),
'pf93-dpfa-03-01':p('Un tercero imparcial facilita que las partes construyan un acuerdo en materias disponibles dentro de los límites aplicables',['El mediador resuelve el conflicto mediante una decisión obligatoria cuando estima que las posiciones de las partes no pueden aproximarse','El procedimiento traslada al mediador la competencia del tribunal respecto de cualquier materia de familia mientras se desarrolla la instancia','El mediador representa simultáneamente a ambas partes y formula una propuesta jurídica que se presume aceptada si ninguna reclama de inmediato'],2),
'pf93-dpfa-03-02':p('Debe comprobarse el cumplimiento de la mediación previa o que concurra alguna excepción que permita demandar sin ella',['Debe verificarse que ninguna instancia de mediación haya tenido lugar, porque la intervención previa de un mediador impide acudir posteriormente a sede judicial','Debe atenderse únicamente a la voluntad del abogado demandante, quien puede optar libremente entre mediación previa y demanda directa en materias obligatorias','Debe solicitarse autorización al consejo técnico antes de presentar la demanda cuando las partes no alcanzaron un acuerdo en la instancia previa'],3),
'pf93-dpfa-03-03':p('No; existen materias mediables y otras sujetas a exclusión o a un régimen específico de mediación previa',['Sí; toda controversia de familia puede someterse a mediación siempre que las partes manifiesten voluntad coincidente de intentar un acuerdo','Sí; incluso cuestiones indisponibles pueden resolverse por acuerdo cuando el mediador estima que la solución protege adecuadamente a quienes intervienen','No; la mediación se encuentra excluida como mecanismo en materia de familia y toda controversia debe comenzar directamente ante el tribunal'],0),
'pf93-dpfa-03-04':p('Puede producir los efectos jurídicos que el sistema atribuye al acuerdo aprobado y permitir su cumplimiento en esos términos',['Produce únicamente un efecto moral entre las partes y no puede servir de fundamento para exigir el cumplimiento de las obligaciones acordadas','Produce una consecuencia punitiva equivalente a una condena cuando una parte incumple posteriormente alguna de las estipulaciones aprobadas','Produce la derogación de las reglas familiares aplicables al conflicto, pues el acuerdo sustituye definitivamente el estatuto normativo de la materia'],1),
'pf93-dpfa-04-01':p('Debe resguardar bilateralidad, contradicción y defensa, utilizando sus facultades de conducción para evitar indefensión',['Debe privilegiar a quien introdujo primero el antecedente, porque la oralidad permite ampliar libremente el objeto litigioso durante la audiencia','Debe excluir toda respuesta de la contraparte para preservar la concentración del procedimiento una vez que el hecho nuevo ya fue incorporado','Debe remitir el conflicto al mediador para que determine si el antecedente sorpresivo puede ser considerado en la decisión jurisdiccional posterior'],2),
'pf93-dpfa-04-03':p('Porque las audiencias y resoluciones quedan registradas por los medios previstos para asegurar trazabilidad y revisión',['Porque toda actuación oral debe reproducirse íntegramente en un expediente en papel antes de que pueda producir efectos dentro del procedimiento','Porque el registro queda entregado a la memoria personal del juez y sólo se formaliza por escrito cuando alguna parte anuncia una impugnación','Porque las audiencias carecen de eficacia inmediata y requieren una transcripción posterior completa para adquirir existencia procesal'],3),
'pf93-dpfa-04-04':p('Debe asegurar participación efectiva e igualdad procesal con las medidas permitidas, manteniendo imparcialidad y contradicción',['Debe favorecer a la persona vulnerable respecto del fondo de la controversia, sustituyendo la valoración jurídica por un criterio de compensación procesal','Debe limitar su participación para evitar exposición a situaciones complejas, aunque ello le impida conocer o controvertir actuaciones relevantes','Debe entregar la decisión a un organismo administrativo especializado cuando una parte requiera ajustes para participar adecuadamente en la audiencia'],0),
'pf93-dpfa-05-01':p('Ordena la controversia, resuelve cuestiones previas, explora acuerdos y prepara la prueba que llegará al juicio',['Tiene por objeto recibir toda la prueba y dictar la sentencia definitiva en la misma etapa, dejando la audiencia de juicio sólo para aclaraciones','Sustituye la demanda y contestación por una investigación dirigida de oficio por el tribunal sobre todos los hechos vinculados al grupo familiar','Se limita a ejecutar obligaciones alimentarias pendientes y no cumple funciones de delimitación del objeto ni preparación de actividad probatoria'],1),
'pf93-dpfa-05-02':p('Concentra la recepción de prueba, las alegaciones pertinentes y la decisión jurisdiccional conforme al procedimiento',['Tiene por finalidad principal reabrir una instancia obligatoria de mediación aunque ésta ya se haya cumplido antes de presentar la demanda','Se utiliza para fijar antecedentes administrativos de las partes y posterga toda actividad probatoria para una etapa escrita posterior','Se destina exclusivamente a resolver incidencias de gestión sin recibir medios probatorios ni permitir alegaciones relacionadas con el fondo'],2),
'pf93-dpfa-05-04':p('No; debe respetarse la oportunidad de prueba salvo que no existan hechos controvertidos o concurra una hipótesis que permita decidir',['Sí; la convicción anticipada del juez permite prescindir de la prueba si los antecedentes de la etapa preparatoria le parecen suficientemente claros','Sí; el carácter protector del procedimiento familiar excluye un derecho de las partes a rendir prueba cuando el tribunal estime innecesaria su producción','No; toda causa exige recibir idénticos medios probatorios aunque las partes estén de acuerdo sobre todos los hechos relevantes para resolver'],3),
'pf93-dpfa-06-02':p('Busca restituir y proteger derechos amenazados o vulnerados mediante una intervención necesaria y proporcional',['Busca sancionar a los adultos relacionados con el NNA como finalidad central, aunque la medida punitiva no contribuya a restituir el derecho comprometido','Busca resolver controversias patrimoniales entre familiares y sólo de manera secundaria considera los efectos que la disputa pueda tener para el NNA','Busca separar al NNA de su entorno habitual como respuesta ordinaria frente a cualquier antecedente de afectación, sin graduar la intervención necesaria'],0),
'pf93-dpfa-06-04':p('Debe evitar trasladar mecánicamente una lógica penal adulta y aplicar el estatuto especial con sus garantías y finalidad pertinente',['Debe evitar considerar la edad y madurez porque esas circunstancias pueden generar diferencias en el tratamiento de hechos materialmente semejantes','Debe evitar reconocer el derecho a ser oído en esta clase de procedimiento para no transformar al NNA en un interviniente de naturaleza penal','Debe evitar aplicar garantías procesales especiales, pues la finalidad protectora permite prescindir de ellas cuando el tribunal busca una respuesta rápida'],1),
'pf93-dpfa-07-01':p('La prueba se aprecia conforme a sana crítica y la decisión debe expresar las razones que sustentan esa valoración',['La prueba se somete a una tarifa rígida en que determinados documentos prevalecen necesariamente sobre testimonios, informes y otros antecedentes','La valoración depende de la impresión subjetiva del juez y no requiere exteriorizar la conexión racional entre los antecedentes y la conclusión alcanzada','La decisión se determina por el número de medios probatorios aportados por cada parte, con preferencia para quien presente una mayor cantidad'],2),
'pf93-dpfa-07-02':p('No; el informe debe valorarse racionalmente junto con los demás antecedentes y sus contradicciones dentro de sana crítica',['Sí; la especialidad del perito convierte sus conclusiones en obligatorias para el juez mientras ninguna otra pericia las contradiga directamente','No; los informes de expertos carecen de aptitud probatoria en procedimientos de familia y sólo sirven como orientación administrativa del tribunal','Sí; basta que el informe provenga de un profesional habilitado para desplazar cualquier otro antecedente no elaborado por un especialista'],3),
'pf93-dpfa-07-03':p('Su participación debe adecuarse a edad y madurez y evitar una exposición probatoria que lo convierta indebidamente en objeto del proceso',['Su opinión debe recibirse mediante el mismo interrogatorio previsto para un testigo adulto para asegurar condiciones idénticas de contradicción','La existencia de informes profesionales autoriza a omitir su participación aunque tenga edad y madurez suficientes para expresar una opinión propia','La audiencia del NNA transfiere a éste la decisión jurídica del conflicto cuando manifiesta de forma clara una preferencia sobre el resultado'],0),
'pf93-dpfa-08-04':p('No; el objeto de revisión está delimitado por el recurso y el marco procesal, salvo las hipótesis especiales que procedan',['Sí; toda impugnación abre una etapa completamente nueva en que las partes pueden reconstruir los hechos y pretensiones sin relación con lo debatido antes','Sí; basta invocar un hecho nuevo para obligar al tribunal revisor a incorporarlo aunque nunca haya sido sometido al órgano que dictó la resolución','No; los recursos sólo permiten discutir competencia orgánica y por ello ninguna controversia fáctica puede ser examinada por un tribunal superior'],1)
});
function patchArray(bank){if(!Array.isArray(bank))return 0;let n=0;for(let i=0;i<bank.length;i++){const patch=L10_OVERRIDES[bank[i]?.id];if(!patch)continue;bank[i]={...bank[i],...patch,fuente:{...bank[i].fuente,verificada:false},revisionOrigen:'AUDITORIA_MEDIA_FAMILIA_L10',reemplazoEditorial:true,revisionL10:true};n++;}return n;}
let appliedL10=0;try{if(typeof PF93_DRAFT_FAMILIA!=='undefined')appliedL10+=patchArray(PF93_DRAFT_FAMILIA);}catch(_){appliedL10=-1;}
const previous=root.PF93_REVIEW_WORKFLOW||{};root.PF93_REVIEW_WORKFLOW=Object.freeze({...previous,L10_OVERRIDES,appliedL10});
})(typeof globalThis!=='undefined'?globalThis:window);