/* L8 — corrección de todas las alertas medias de la especialidad Civil (DCI/DPC).
 * Se conserva el problema jurídico y la explicación/fuente original; se reconstruyen alternativas
 * para eliminar pistas formales, equilibrar extensión y hacer competir instituciones próximas.
 * No constituye verificación jurídica humana: fuente.verificada permanece false.
 */
(function(root){
'use strict';
function p(correcta,distractores,pos){const xs=distractores.slice(0,3);xs.splice(pos,0,correcta);return{opciones:xs.map((text,i)=>({id:'ABCD'[i],text})),respuesta:pos,dificultad:'media-alta'};}
const L8_OVERRIDES=Object.freeze({
'pf93-dci-01-03':p('Se diferencian por sus causales, personas legitimadas y posibilidades de saneamiento',['Se diferencian sólo por la cuantía económica del acto cuya validez se discute','Se distinguen porque una afecta actos patrimoniales y la otra únicamente actos familiares','Se distinguen por el tribunal competente, pero comparten causales y régimen de saneamiento'],0),
'pf93-dci-02-01':p('La aptitud de la cosa para trasladarse de un lugar a otro sin perder su individualidad',['La necesidad de publicidad registral para que la cosa pueda ser objeto de actos patrimoniales','La circunstancia de que la cosa produzca frutos o utilidades para quien ejerce su dominio','La destinación económica que el propietario declare al momento de adquirir materialmente la cosa'],1),
'pf93-dci-02-02':p('Corresponde a un derecho real, caracterizado por una relación jurídica directa con la cosa',['Corresponde a un derecho personal, porque su ejercicio requiere una prestación de un deudor determinado','Corresponde a una obligación natural, porque carece de acción para exigir su cumplimiento coactivo','Corresponde a una mera expectativa patrimonial mientras no exista un vínculo obligacional entre personas'],2),
'pf93-dci-02-03':p('Permite apreciar si una cosa puede ser sustituida por otra equivalente para ciertos efectos obligacionales',['Determina si el bien requiere inscripción para que pueda ser objeto de una transferencia entre particulares','Define si el titular puede ejercer acciones posesorias con independencia de la naturaleza del bien','Establece si el bien queda sujeto a un régimen de administración común entre varios propietarios'],3),
'pf93-dci-02-04':p('No; la clasificación del derecho atiende también a la cosa sobre la cual se ejerce o que se debe',['Sí; la naturaleza incorporal del derecho determina que deba tratarse como bien mueble para todos sus efectos','Sí; los inmuebles comprenden únicamente objetos corporales adheridos de manera permanente al suelo','No; la clasificación depende exclusivamente de que el derecho tenga o no un valor económico susceptible de estimación'],0),
'pf93-dci-03-01':p('Cumple la tradición inmobiliaria cuando existe un título traslaticio apto para transferir el dominio',['Constituye por sí misma el contrato traslaticio y reemplaza el consentimiento de quienes celebran la compraventa','Sirve sólo como medio de publicidad y deja la transferencia dominical cumplida desde la firma del contrato','Suple la ausencia de un título traslaticio cuando quien solicita inscribir demuestra la tenencia material del inmueble'],1),
'pf93-dci-04-01':p('La inscripción registral tiene un papel central para adquirir, conservar y perder la posesión del inmueble inscrito',['La ocupación material determina por sí misma la posesión, aunque subsista una inscripción a nombre de otra persona','El contrato que antecede a la tenencia desplaza la situación registral desde su celebración, aunque no se practique inscripción','La declaración unilateral de quien ocupa el inmueble basta para sustituir la posición posesoria reflejada en el registro'],2),
'pf93-dci-04-02':p('El dominio es un derecho real sobre la cosa; la posesión es una situación de hecho jurídicamente protegida con ánimo de señor o dueño',['El dominio y la posesión describen la misma relación jurídica, porque ambos requieren titularidad inscrita sobre la cosa','La posesión es un derecho personal contra el propietario, mientras el dominio corresponde a la tenencia material de la cosa','El dominio depende de la ocupación física continua, mientras la posesión existe sólo mediante una declaración formal de titularidad'],3),
'pf93-dci-04-03':p('No; la situación debe resolverse conforme al régimen especial de posesión inscrita y sus formas de cancelación',['Sí; la ocupación material desplaza la posesión registral desde que el ocupante manifiesta ánimo de señor o dueño','Sí; el control físico del inmueble prevalece sobre la inscripción cuando se mantiene de manera pública durante un período breve','No; la posesión de un inmueble inscrito sólo puede modificarse mediante una sentencia declarativa que reconozca al nuevo poseedor'],0),
'pf93-dci-05-03':p('Uso y habitación tienen una extensión vinculada a las necesidades del titular y su familia, según su régimen propio',['Uso y habitación confieren las mismas facultades de goce y aprovechamiento económico que corresponden al usufructuario','Uso y habitación permiten disponer del derecho con la misma amplitud con que puede transferirse un derecho de dominio','Uso y habitación recaen exclusivamente sobre créditos y no pueden relacionarse con el aprovechamiento material de una cosa'],1),
'pf93-dci-05-04':p('Debe precisarse el título, contenido y oponibilidad de la limitación según la institución de que se trate',['Toda limitación voluntaria transforma el dominio en mera tenencia mientras subsista el gravamen constituido','Las partes pueden configurar nuevos derechos reales con eficacia frente a terceros sólo por acuerdo contractual','Una limitación sobre el dominio produce efectos únicamente entre quienes la estipulan, aunque su régimen contemple publicidad'],2),
'pf93-dci-06-03':p('La reivindicación tutela el dominio del dueño no poseedor; la posesoria protege la posesión bajo sus propios presupuestos',['Ambas acciones protegen la titularidad dominical y se distinguen únicamente por el procedimiento en que se tramitan','La acción posesoria busca declarar el dominio del actor, mientras la reivindicación persigue conservar una mera situación posesoria','La reivindicación y la posesoria tienen el mismo objeto, pero la segunda se reserva a bienes muebles susceptibles de aprehensión'],3),
'pf93-dci-06-04':p('Debe definirse si la pretensión busca proteger posesión o hacer valer dominio sobre la cosa discutida',['Debe determinarse primero si la cosa tiene valor superior al límite cuantitativo fijado para la acción que se pretende ejercer','Debe examinarse primero la solvencia del demandado para decidir cuál acción ofrece mayores posibilidades prácticas de cumplimiento','Debe establecerse primero si existió un contrato entre las partes, porque sin vínculo previo ninguna de las dos acciones puede ejercerse'],0),
'pf93-dci-07-02':p('No; la pluralidad de deudores no basta y debe existir una fuente que atribuya solidaridad a la obligación',['Sí; cuando la prestación es divisible la pluralidad pasiva convierte a cada deudor en obligado por el total','Sí; la solidaridad surge de la existencia de una deuda común aunque cada deudor se haya obligado por una cuota distinta','No; la pluralidad convierte la obligación en indivisible y por eso cada deudor responde únicamente por su parte'],1),
'pf93-dci-08-02':p('La buena fe integra la ejecución con deberes que derivan de la naturaleza del contrato y de su contexto jurídico',['La buena fe limita la ejecución a lo escrito expresamente, evitando incorporar consecuencias que las partes no hayan redactado','La buena fe permite al deudor adaptar unilateralmente la prestación cuando estime que otra forma de cumplimiento resulta más eficiente','La buena fe convierte los deberes contractuales en obligaciones naturales cuando no han sido formulados expresamente por las partes'],2),
'pf93-dci-08-04':p('Debe buscarse la intención común de los contratantes y armonizar la cláusula con el conjunto del contrato',['Debe preferirse la interpretación que beneficie económicamente a la parte que redactó originalmente la cláusula discutida','Debe atenderse sólo al significado gramatical aislado de la cláusula, sin relacionarla con las demás estipulaciones del contrato','Debe elegirse la interpretación que produzca el mayor número de obligaciones, aunque se aparte del sentido conjunto del negocio'],3),
'pf93-dci-09-01':p('El vendedor se obliga respecto de la cosa y el comprador respecto del precio, además de los deberes propios del contrato',['El vendedor asume el pago del precio y el comprador queda obligado a transferir al primero el dominio de la cosa vendida','Ambas partes se obligan únicamente a celebrar en el futuro un segundo contrato que materialice cosa y precio','El comprador recibe sólo la tenencia temporal y el vendedor conserva íntegramente las obligaciones propias del arrendamiento'],0),
'pf93-dci-09-02':p('Debe procurar al arrendatario el goce de la cosa durante la relación contractual en los términos convenidos',['Debe transferir definitivamente el dominio al arrendatario una vez pagada la primera renta estipulada','Debe restituir al arrendatario el precio de adquisición de la cosa al finalizar la vigencia del contrato','Debe limitarse a entregar materialmente la cosa al inicio, sin obligaciones vinculadas a su goce durante la relación'],1),
'pf93-dci-09-04':p('El mutuario recibe fungibles y debe restituir otras cosas equivalentes del mismo género y calidad',['El mutuario recibe una especie individualizada y debe restituir exactamente el mismo objeto material recibido','El mutuante conserva el dominio de las especies entregadas y el mutuario adquiere únicamente una facultad de custodia','El contrato tiene por objeto principal el uso temporal de una cosa no fungible que debe conservar su identidad'],2),
'pf93-dci-10-01':p('Debe examinarse inicialmente la responsabilidad derivada del incumplimiento del vínculo contractual existente',['Debe acudirse inicialmente al régimen de daños entre personas sin vínculo contractual, prescindiendo del contrato incumplido','Debe resolverse mediante las reglas de enriquecimiento sin causa, aunque el daño provenga directamente de la obligación pactada','Debe calificarse como responsabilidad precontractual, porque todo incumplimiento posterior retrotrae sus efectos a la negociación'],3),
'pf93-dci-10-03':p('Sin un perjuicio atribuible no existe un menoscabo que la indemnización civil deba reparar',['La sola infracción de una obligación genera una suma indemnizatoria aunque no exista consecuencia perjudicial para el acreedor','El daño cumple únicamente una función probatoria, porque la responsabilidad se configura de manera completa con la conducta imputable','El daño determina la competencia del tribunal, pero no forma parte de los presupuestos sustantivos de una pretensión indemnizatoria'],0),
'pf93-dci-10-05':p('La previsibilidad puede delimitar los perjuicios resarcibles según la forma de imputación del incumplimiento',['La previsibilidad determina por sí sola la existencia del contrato y reemplaza el análisis de incumplimiento y causalidad','La previsibilidad transforma en extracontractual una pretensión indemnizatoria nacida de obligaciones válidamente pactadas','La previsibilidad permite indemnizar daños desconectados causalmente del incumplimiento cuando el deudor pudo imaginarlos'],1),
'pf93-dci-11-03':p('Restringen la libertad de disposición del causante en protección de determinados asignatarios',['Permiten al causante disponer de la totalidad del patrimonio sin atender a las posiciones sucesorias protegidas','Operan sólo como pautas interpretativas para el partidor y carecen de incidencia sobre disposiciones testamentarias incompatibles','Reemplazan la sucesión testamentaria por una sucesión intestada completa cuando existe algún asignatario protegido'],2),
'pf93-dci-12-02':p('Debe identificarse el régimen patrimonial y la naturaleza u origen de los bienes o actos involucrados',['Debe atenderse primordialmente a la duración del matrimonio, porque ese dato define el estatuto de todos los bienes adquiridos','Debe determinarse primero cuál cónyuge obtuvo mayores ingresos, pues ello decide la titularidad de los bienes discutidos','Debe establecerse la existencia de hijos comunes, porque su presencia transforma el régimen patrimonial aplicable entre los cónyuges'],3),
'pf93-dci-13-01':p('Rige la igualdad jurídica de los hijos, sin distinciones de efectos basadas en el origen de la filiación',['Los efectos sucesorios dependen de que la filiación haya sido determinada dentro o fuera del matrimonio de los progenitores','Los derechos derivados de la filiación varían según exista reconocimiento voluntario o una determinación judicial del vínculo','La filiación matrimonial produce una posición civil preferente respecto de las demás formas de determinación del vínculo'],0),
'pf93-dci-13-03':p('Es un medio probatorio especialmente relevante que debe apreciarse conforme al régimen aplicable a la filiación',['Desplaza la valoración de los demás antecedentes y obliga a decidir exclusivamente conforme al resultado técnico obtenido','Sólo puede practicarse cuando existe acuerdo previo de todas las personas que intervienen en el proceso de filiación','Tiene valor meramente orientador y no puede producir consecuencias respecto de la determinación judicial del vínculo filial'],1),
'pf93-dci-13-04':p('Debe identificarse la filiación vigente, la acción ejercida, la legitimación y la oportunidad para deducirla',['Debe determinarse ante todo el valor económico de los derechos hereditarios que podrían modificarse con la decisión sobre filiación','Debe examinarse primero la voluntad actual de los progenitores, porque el estado filial depende de su acuerdo al momento de la sentencia','Debe establecerse si existe posesión material de bienes familiares, porque ese antecedente define la acción de filiación procedente'],2),

'pf93-dpc-01-01':p('Busca asegurar que cada parte pueda conocer y controvertir oportunamente lo relevante para la decisión',['Busca entregar al tribunal la facultad de incorporar pretensiones nuevas sin comunicación a quienes puedan resultar afectados','Busca concentrar el procedimiento suprimiendo oportunidades de respuesta cuando exista prueba documental suficiente','Busca impedir que las partes conozcan anticipadamente la estrategia probatoria de su contraparte antes de dictarse sentencia'],3),
'pf93-dpc-01-02':p('Debe examinarse la preclusión de la facultad procesal asociada al vencimiento del plazo fatal',['Debe entenderse que la actuación conserva eficacia porque los plazos procesales sólo orientan la gestión del tribunal','Debe reiniciarse el plazo desde la presentación tardía si la contraparte todavía no ha solicitado una declaración sobre su vencimiento','Debe transformar la actuación extemporánea en una solicitud de ampliación del plazo para preservar el derecho de defensa'],0),
'pf93-dpc-01-03':p('Es la pérdida o consumación de una facultad procesal cuando concurre una causa que impide ejercerla después',['Es la transferencia de una facultad desde una parte hacia la contraparte cuando se modifica la carga de acreditar un hecho','Es la suspensión temporal de una facultad hasta que el tribunal resuelva todas las cuestiones accesorias del procedimiento','Es la ampliación judicial de una oportunidad procesal que ya venció, cuando la actuación tardía parece relevante para el fondo'],1),
'pf93-dpc-01-04':p('Debe evitarse equiparar todo defecto formal con nulidad sin examinar perjuicio, finalidad y posibilidad de subsanación',['Debe evitarse considerar la finalidad del acto, porque sólo la forma externa permite establecer si corresponde invalidar una actuación','Debe evitarse examinar el perjuicio sufrido por la parte, ya que la invalidez procesal depende exclusivamente del error objetivo','Debe evitarse aplicar mecanismos de subsanación cuando el acto haya cumplido su finalidad comunicativa pese al defecto denunciado'],2),
'pf93-dpc-02-02':p('Busca estabilizar lo resuelto e impedir decisiones posteriores incompatibles dentro de sus límites objetivos y subjetivos',['Busca permitir una nueva decisión sobre el mismo conflicto cuando una parte estime que dispone de mejores antecedentes probatorios','Busca extender el efecto de una sentencia a controversias distintas que no fueron sometidas al tribunal en el proceso anterior','Busca transformar el razonamiento de la sentencia en una regla general obligatoria para litigantes ajenos a la controversia resuelta'],3),
'pf93-dpc-02-03':p('Deben compararse sujetos, objeto pedido y fundamento de pedir, además del alcance de lo ya decidido',['Debe compararse la identidad de los abogados y el tribunal que tramitó ambos procesos, con independencia de las pretensiones deducidas','Debe compararse únicamente la cuantía económica de las dos causas, porque ella determina si existe identidad suficiente entre litigios','Debe compararse el número de documentos acompañados y la etapa procesal en que se produjo la sentencia del primer proceso'],0),
'pf93-dpc-02-04':p('No; el efecto depende de la naturaleza de la resolución y del contenido que haya sido efectivamente decidido',['Sí; una providencia de mera tramitación tiene el mismo efecto sustantivo que una sentencia que resuelve definitivamente la pretensión','Sí; toda decisión pronunciada durante el proceso impide discutir en otro juicio materias relacionadas aunque no hayan sido resueltas','No; las resoluciones interlocutorias carecen de efectos vinculantes incluso respecto de cuestiones que deciden de manera estable dentro del proceso'],1),
'pf93-dpc-03-02':p('Deben identificarse tipo de plazo, hito inicial, forma de cómputo y reglas especiales de suspensión o habilitación',['Debe atenderse sólo a la fecha en que una parte declara haber tomado conocimiento informal de la existencia del procedimiento','Debe contarse desde la fecha material de redacción de la resolución, aunque su eficacia dependa de una comunicación posterior','Debe aplicarse la misma forma de cómputo a todas las actuaciones, prescindiendo del carácter fatal o no fatal del plazo específico'],2),
'pf93-dpc-03-04':p('El expediente se forma electrónicamente con los registros y actuaciones incorporados conforme al sistema de tramitación',['El expediente electrónico funciona sólo como copia auxiliar y el soporte en papel conserva primacía para determinar las actuaciones válidas','Las partes pueden excluir unilateralmente del expediente actuaciones que fueron válidamente registradas en el sistema de tramitación','La formación del expediente depende de que cada escrito sea reproducido materialmente por el tribunal antes de producir efectos procesales'],3),
'pf93-dpc-03-05':p('Puede operar la notificación tácita si la conducta de la parte demuestra conocimiento y concurren sus presupuestos',['Puede entenderse saneado el defecto por la mera existencia de la resolución, aunque la parte no haya tenido conocimiento de su contenido','Puede tenerse por notificada a la parte desde la fecha de redacción interna del acto, aunque no realice conducta que revele conocimiento','Puede sustituirse la comunicación defectuosa por una presunción de conocimiento fundada únicamente en la comparecencia de su abogado en otra causa'],0),
'pf93-dpc-04-01':p('Permite que el demandado conozca la pretensión y disponga de la oportunidad procesal para ejercer defensa',['Permite radicar definitivamente el dominio de los bienes litigiosos en quien presentó primero su pretensión ante el tribunal competente','Permite al actor modificar después de la notificación el objeto de la demanda sin una oportunidad correlativa de respuesta del demandado','Permite al tribunal prescindir de la comparecencia del demandado y tener por reconocidos los hechos expuestos en el escrito inicial'],1),
'pf93-dpc-04-05':p('Debe constatarse que existió un emplazamiento válido y que transcurrió la oportunidad para contestar',['Debe verificarse que el actor haya acompañado toda su prueba con la demanda, aunque el régimen procesal permita rendirla posteriormente','Debe acreditarse que el demandado carece de bienes suficientes para cumplir una eventual sentencia favorable al demandante','Debe comprobarse que el demandado conoció informalmente el conflicto antes de que la demanda fuera presentada ante el tribunal'],2),
'pf93-dpc-05-01':p('Son objeto de prueba los hechos sustanciales, pertinentes y controvertidos que inciden en la decisión',['Son objeto de prueba todas las afirmaciones contenidas en los escritos, aunque las partes coincidan sobre ellas y no influyan en el conflicto','Son objeto de prueba únicamente los hechos reconocidos por ambas partes, porque la controversia impide establecerlos con suficiente certeza','Son objeto de prueba las reglas jurídicas nacionales aplicables al litigio, mientras los hechos se determinan por la sola alegación de las partes'],3),
'pf93-dpc-05-02':p('La carga distribuye el riesgo de falta de prueba; la valoración determina el mérito de la evidencia producida',['La carga determina qué tribunal conocerá del litigio y la valoración distribuye territorialmente las actuaciones probatorias','La carga y la valoración son etapas equivalentes, pues ambas establecen qué parte debe presentar primero sus medios de prueba','La carga fija de antemano el valor de cada medio probatorio y la valoración decide quién debe soportar las costas del proceso'],0),
'pf93-dpc-05-04':p('Fija los hechos sustanciales, pertinentes y controvertidos sobre los cuales se desarrollará la actividad probatoria',['Resuelve definitivamente los hechos discutidos antes de que las partes hayan tenido oportunidad de rendir sus medios probatorios','Sustituye la contestación de la demanda y redefine las pretensiones que integran el objeto del proceso declarativo','Determina el valor obligatorio de cada prueba que se rendirá y anticipa la conclusión que el tribunal debe extraer de ella'],1),
'pf93-dpc-06-01':p('Debe examinarse la congruencia y el deber de pronunciarse sobre las pretensiones oportunamente sometidas',['Debe examinarse la competencia territorial, porque la omisión de una pretensión equivale a una alteración del lugar donde debía tramitarse','Debe examinarse la carga probatoria del demandante, aunque la omisión recaiga sobre una acción respecto de la cual se rindió prueba suficiente','Debe examinarse la firmeza de la sentencia como cuestión previa, porque una omisión decisoria sólo puede corregirse después de ejecutoriada'],2),
'pf93-dpc-06-03':p('Permite conocer las razones fácticas y jurídicas de la decisión y controlar racionalmente su corrección',['Permite al tribunal sustituir la actividad probatoria por una explicación extensa de la conclusión que considera más adecuada al caso','Permite ampliar en la sentencia el objeto litigioso con cuestiones no debatidas, siempre que el juez exponga razones suficientes para decidirlas','Permite limitar los medios de impugnación, porque una decisión suficientemente motivada deja de producir agravio procesal a las partes'],3),
'pf93-dpc-06-04':p('La firmeza se determina atendiendo al régimen de impugnación y al estado procesal alcanzado por la resolución',['La sentencia queda firme desde su firma material, aunque todavía exista una impugnación procedente que pueda modificar lo decidido','La firmeza depende de la aceptación expresa de ambas partes y no puede producirse mientras alguna manifieste desacuerdo con la decisión','La ejecutoriedad surge desde la primera notificación practicada en la causa, porque el emplazamiento anticipa los efectos de la decisión final'],0),
'pf93-dpc-07-02':p('No; la suspensión depende de la naturaleza de la cuestión incidental y de los efectos que el régimen le atribuya',['Sí; la sola presentación de una cuestión accesoria impide al tribunal continuar con actuaciones del asunto principal hasta resolverla','Sí; la suspensión se produce por la voluntad de quien promueve el incidente, aunque la cuestión sea inconexa con la controversia principal','No; los incidentes se tramitan fuera del proceso principal y por eso carecen de toda incidencia sobre su avance o sus actuaciones'],1),
'pf93-dpc-07-03':p('Debe verificarse que exista una cuestión accesoria conectada al proceso y que se plantee en oportunidad y forma procedentes',['Debe verificarse que la cuestión accesoria tenga una cuantía superior a la pretensión principal para que merezca una decisión separada','Debe constatarse que ambas partes acepten tramitar la cuestión como incidente, porque su existencia depende de acuerdo procesal','Debe comprobarse que la cuestión modifique la competencia material del tribunal, ya que ése es el presupuesto común de toda incidencia'],2),
'pf93-dpc-07-04':p('Corresponde aplicar mecanismos contra la dilación abusiva sin privar a la parte de las incidencias legítimas que pueda promover',['Corresponde admitir reiteradamente las cuestiones aunque reproduzcan íntegramente otras ya resueltas y carezcan de conexión con el proceso','Corresponde impedir que esa parte vuelva a formular una cuestión accesoria durante el resto del proceso, cualquiera sea su fundamento posterior','Corresponde tener por perdido el juicio principal como consecuencia procesal de promover cuestiones accesorias que retrasen la tramitación'],3),
'pf93-dpc-08-01':p('Debe examinar medidas precautorias destinadas a conservar bienes o situaciones para asegurar la eficacia de la decisión futura',['Debe promover una nueva acción declarativa para obtener desde ya el mismo resultado definitivo perseguido en el litigio principal','Debe solicitar que el demandado sea privado de administrar todo su patrimonio sin vincular la medida con el riesgo concreto alegado','Debe requerir una decisión anticipada sobre el fondo, porque la protección provisional sólo procede después de reconocer el derecho reclamado'],0),
'pf93-dpc-08-02':p('Requiere antecedentes de la pretensión y un riesgo que justifique la medida, además de proporcionalidad con su finalidad',['Requiere demostrar de antemano con certeza plena que la sentencia definitiva será favorable a quien solicita la tutela provisional','Requiere sólo alegar que existe un litigio, sin necesidad de relacionar la medida solicitada con un peligro para la eficacia del proceso','Requiere que el demandado haya incumplido previamente una sentencia firme, pues antes de esa etapa no puede afectarse provisionalmente su esfera'],1),
'pf93-dpc-08-03':p('Puede tratarse de una medida prejudicial si su finalidad es preparar, asegurar o anticipar una actividad necesaria para el futuro proceso',['Corresponde a una sentencia anticipada, porque toda diligencia anterior a la demanda supone decidir parcialmente la controversia proyectada','Corresponde a un incidente, aunque todavía no exista un proceso principal en el cual la cuestión accesoria pueda suscitarse válidamente','Corresponde a una actuación de ejecución, porque preparar una demanda equivale a perseguir el cumplimiento forzado de la futura pretensión'],2),
'pf93-dpc-08-04':p('Porque su función es provisional e instrumental: asegura la eficacia del proceso sin decidir definitivamente el fondo',['Porque la medida provisional carece de efectos sobre bienes o conductas y se limita a formular una recomendación al demandado','Porque la medida sólo puede decretarse una vez resuelta la controversia, momento en que asegura el cumplimiento de la sentencia firme','Porque la tutela cautelar sustituye la sentencia cuando el riesgo es grave, pero conserva el nombre de medida provisional por razones formales'],3),
'pf93-dpc-09-01':p('Debe existir un título con fuerza ejecutiva y una obligación susceptible de cumplimiento forzado en los términos exigibles',['Basta la afirmación del acreedor acerca de una deuda, aunque no exista antecedente al que el sistema atribuya eficacia ejecutiva','Se requiere una controversia compleja sobre la existencia misma de la obligación para que el procedimiento ejecutivo pueda declararla','La ejecución exige que el deudor reconozca nuevamente la obligación al ser requerido, aunque ya exista un antecedente ejecutivo suficiente'],0),
'pf93-dpc-09-02':p('No; la oposición está sometida a causales, oportunidad y forma propias del procedimiento ejecutivo',['Sí; el ejecutado puede incorporar defensas en etapas sucesivas mientras no se haya realizado materialmente el bien embargado','Sí; la oposición no se sujeta a un marco de excepciones porque el derecho de defensa permite redefinir libremente la controversia ejecutiva','No; la estructura ejecutiva excluye defensas del deudor y limita su intervención a señalar bienes suficientes para satisfacer el crédito'],1),
'pf93-dpc-09-04':p('El embargo afecta bienes determinados al procedimiento para hacer posible la satisfacción forzada del crédito',['El embargo transfiere el dominio del bien al ejecutante desde su práctica, aunque todavía no exista realización ni adjudicación','El embargo extingue la obligación hasta el valor estimado del bien afectado, aunque el acreedor no haya recibido prestación alguna','El embargo convierte el proceso ejecutivo en declarativo y obliga a discutir nuevamente la existencia del título que fundó la ejecución'],2),
'pf93-dpc-09-05':p('Debe examinarse una tercería de dominio si el tercero sostiene ser propietario del bien embargado',['Debe plantearse una reconvención contra el ejecutante dentro del mismo escrito de oposición del deudor, aunque el tercero no sea parte','Debe solicitarse una medida prejudicial para que el tribunal declare preventivamente el dominio antes de examinar el embargo vigente','Debe formularse una excepción personal del ejecutado, porque los derechos de terceros sobre bienes afectados se hacen valer a través del deudor'],3),
'pf93-dpc-10-01':p('Debe examinarse la reposición cuando se pide al mismo tribunal reconsiderar una resolución susceptible de ese recurso',['Debe examinarse la apelación como vía dirigida al mismo tribunal para que vuelva a decidir sin intervención de un órgano superior','Debe examinarse la casación de fondo respecto de toda resolución que contenga un error corregible por quien la dictó','Debe examinarse la revisión de sentencia firme aunque la resolución cuestionada sea de tramitación y el proceso continúe pendiente'],0),
'pf93-dpc-10-03':p('Debe precisarse el tipo de vicio, la resolución recurrible, la causal invocada, la preparación pertinente y el plazo',['Debe limitarse a expresar disconformidad con el resultado, porque el tribunal superior selecciona posteriormente la causal adecuada','Debe anunciarse una revisión completa de hechos y prueba, ya que la casación abre una segunda instancia ordinaria sobre toda la controversia','Debe fundarse en hechos nuevos no debatidos en el proceso, pues el carácter extraordinario permite reconstruir la base fáctica del litigio'],1),
'pf93-dpc-10-04':p('El efecto suspensivo depende del recurso, de la resolución impugnada y de la forma en que el ordenamiento regula su concesión',['La interposición de una impugnación paraliza el cumplimiento de la resolución hasta que el tribunal superior se pronuncie sobre el fondo','La impugnación carece de incidencia sobre el cumplimiento en todos los casos, porque sólo produce un efecto devolutivo de conocimiento','La suspensión depende de que la parte vencedora consienta en diferir el cumplimiento de la resolución durante la tramitación del recurso'],2)
});
function patchArray(bank){if(!Array.isArray(bank))return 0;let n=0;for(let i=0;i<bank.length;i++){const patch=L8_OVERRIDES[bank[i]?.id];if(!patch)continue;bank[i]={...bank[i],...patch,fuente:{...bank[i].fuente,verificada:false},revisionOrigen:'AUDITORIA_MEDIA_CIVIL_L8',reemplazoEditorial:true,revisionL8:true};n++;}return n;}
let appliedL8=0;try{if(typeof PF93_DRAFT_CIVIL!=='undefined')appliedL8+=patchArray(PF93_DRAFT_CIVIL);}catch(_){appliedL8=-1;}
const previous=root.PF93_REVIEW_WORKFLOW||{};root.PF93_REVIEW_WORKFLOW=Object.freeze({...previous,L8_OVERRIDES,appliedL8});
})(typeof globalThis!=='undefined'?globalThis:window);
