/* Banco PF93 — especialidad civil. Borrador para revisión humana. */
const PF93_DRAFT_CIVIL = (() => {
  const out=[]; const seq={};
  function add(tema,pregunta,correcta,distractores,explicacion,fuente){seq[tema]=(seq[tema]||0)+1;const pos=(out.length+seq[tema])%4;const opciones=distractores.slice(0,3);opciones.splice(pos,0,correcta);out.push({id:`pf93-${tema.toLowerCase()}-${String(seq[tema]).padStart(2,'0')}`,temaPF93:tema,pregunta,opciones:opciones.map((text,i)=>({id:'ABCD'[i],text})),respuesta:pos,explicacion,fuente:{cita:fuente,verificada:false,revisadaEn:null},estado:'revision_humana',dificultad:'media',tipo:'alternativa'});}

  // DCI-01 Acto jurídico
  add('DCI-01','Una persona celebra un contrato careciendo absolutamente de la aptitud que la ley exige para obligarse por sí misma. ¿Qué aspecto del acto jurídico debe examinarse principalmente?','La capacidad del autor o de las partes',['La tradición del bien','La competencia del tribunal','La inscripción conservatoria como requisito de todo contrato'],'La capacidad es un requisito de validez cuya infracción produce las consecuencias que establece el Código Civil.','Código Civil, reglas sobre actos y declaraciones de voluntad');
  add('DCI-01','Si el consentimiento contractual se obtiene mediante una amenaza grave que reúne los requisitos legales, ¿qué institución resulta pertinente?','Un vicio del consentimiento por fuerza',['La inexistencia de objeto por definición','La tradición ficta','La prescripción adquisitiva'],'La fuerza puede viciar el consentimiento cuando cumple los presupuestos legales.','Código Civil, vicios del consentimiento');
  add('DCI-01','¿Cuál afirmación distingue correctamente nulidad absoluta y relativa?','Protegen presupuestos distintos y poseen causales, legitimación y saneamiento regulados de manera diferente',['Son nombres equivalentes para una misma sanción sin diferencias','La nulidad relativa puede declararse siempre de oficio','La nulidad absoluta sólo protege intereses privados disponibles'],'El Código Civil establece regímenes diferenciados para nulidad absoluta y relativa.','Código Civil, Título sobre nulidad y rescisión');
  add('DCI-01','Un contrato recae sobre una prestación prohibida por el ordenamiento. ¿Qué requisito del acto jurídico debe analizarse especialmente?','La licitud del objeto',['La posesión inscrita','La competencia relativa','La notificación por cédula'],'La licitud del objeto integra los requisitos de validez del acto o contrato.','Código Civil, objeto y causa de los actos y contratos');

  // DCI-02 Bienes
  add('DCI-02','¿Qué criterio distingue bienes muebles de inmuebles por naturaleza?','La posibilidad de transportarlos de un lugar a otro sin detrimento, frente a las cosas que no pueden transportarse en esos términos',['La existencia de inscripción registral en todo caso','El valor económico del bien','La voluntad unilateral del propietario sin límite legal'],'El Código Civil clasifica los bienes según su movilidad y contempla además categorías de inmuebles por adherencia o destinación.','Código Civil, clasificación de los bienes');
  add('DCI-02','Un derecho real recae directamente sobre una cosa y puede hacerse valer en los términos que la ley reconoce. ¿Qué clasificación jurídica resulta pertinente?','Derecho real, en contraste con un derecho personal o crédito',['Obligación natural','Hecho jurídico no patrimonial','Competencia absoluta'],'Los derechos reales y personales son categorías patrimoniales distintas en el Código Civil.','Código Civil, arts. 577 y 578');
  add('DCI-02','¿Cuál es una consecuencia relevante de distinguir cosas fungibles y no fungibles?','Permite determinar si la obligación puede cumplirse con otra cosa del mismo género, calidad y cantidad',['Determina por sí sola la competencia del tribunal','Convierte todo bien fungible en inmueble','Elimina la necesidad de título en la transferencia del dominio'],'La fungibilidad atiende a la sustituibilidad de la cosa y repercute en diversos negocios y obligaciones.','Código Civil, clasificación de las cosas');
  add('DCI-02','Un derecho sobre un inmueble ¿se clasifica necesariamente como mueble por ser incorporal?','No; los derechos y acciones pueden reputarse muebles o inmuebles según la cosa en que han de ejercerse o que se debe',['Sí; todo derecho incorporal es siempre mueble','Sí; porque sólo las cosas corporales pueden ser inmuebles','No; porque todo derecho personal es inmueble'],'El Código Civil aplica reglas específicas para clasificar derechos y acciones.','Código Civil, bienes incorporales');

  // DCI-03 Modos de adquirir
  add('DCI-03','En la compraventa de un inmueble, ¿qué función cumple la inscripción conservatoria dentro del sistema chileno?','Opera, por regla general, como tradición del dominio del inmueble cuando existe título traslaticio válido',['Reemplaza al contrato de compraventa y constituye por sí sola el título','Es irrelevante para la transferencia de inmuebles','Transfiere dominio aun cuando no exista ningún título jurídico'],'En el sistema de título y modo, la compraventa es título y la inscripción cumple la tradición inmobiliaria.','Código Civil, tradición de bienes raíces');
  add('DCI-03','Una persona adquiere el dominio por el transcurso del tiempo unido a posesión con los requisitos legales. ¿Qué modo de adquirir opera?','La prescripción adquisitiva',['La accesión procesal','La novación','La representación sucesoria'],'La prescripción adquisitiva permite adquirir el dominio y otros derechos reales en los casos y bajo requisitos legales.','Código Civil, prescripción adquisitiva');
  add('DCI-03','¿Qué modo de adquirir explica que el dueño de una cosa pase a ser dueño de lo que ella produce o de lo que se junta a ella conforme a la ley?','La accesión',['La tradición simbólica de toda cosa','La compensación','La resciliación'],'La accesión es un modo de adquirir asociado a productos de una cosa o a incorporaciones reguladas legalmente.','Código Civil, accesión');
  add('DCI-03','Al fallecer una persona, la transmisión de sus derechos y obligaciones transmisibles a sus sucesores se vincula a ¿qué modo de adquirir?','La sucesión por causa de muerte',['La ocupación','La tradición entre vivos','La especificación contractual'],'La sucesión por causa de muerte es un modo de adquirir regulado por el Código Civil.','Código Civil, sucesión por causa de muerte');

  // DCI-04 Posesión inscrita
  add('DCI-04','Tratándose de un inmueble sujeto al régimen registral, ¿qué elemento posee especial relevancia para adquirir y conservar la posesión en el sistema de posesión inscrita?','La inscripción en el Registro de Propiedad, conforme a las reglas del Código Civil',['La sola ocupación material clandestina','Un contrato verbal sin antecedente registral en todo caso','La mera declaración unilateral ante testigos'],'La teoría de la posesión inscrita atribuye a la inscripción un papel central respecto de inmuebles inscritos.','Código Civil, posesión de bienes raíces inscritos');
  add('DCI-04','¿Qué diferencia conceptual existe entre dominio y posesión?','El dominio es un derecho real; la posesión es la tenencia con ánimo de señor o dueño en los términos legales',['Son siempre exactamente la misma situación jurídica','La posesión sólo puede existir respecto de créditos','El dominio es un mero hecho sin protección jurídica'],'El Código Civil distingue propiedad de posesión, aunque puedan concurrir en una misma persona.','Código Civil, arts. 582 y 700');
  add('DCI-04','¿Puede la mera aprehensión material de un inmueble inscrito desplazar automáticamente la posesión inscrita de su titular?','No; deben aplicarse las reglas especiales del régimen de posesión inscrita y cancelación de la inscripción',['Sí, toda ocupación material cancela la inscripción anterior','Sí, si dura más de una semana','No, porque los inmuebles jamás pueden cambiar de poseedor'],'El sistema registral limita el efecto de actos materiales respecto de la posesión de inmuebles inscritos.','Código Civil, reglas de posesión inscrita');
  add('DCI-04','Para estudiar si una posesión es regular, ¿qué elementos deben revisarse?','Justo título, buena fe y, cuando el título es traslaticio, tradición',['Sólo la duración material de la ocupación','Exclusivamente la inscripción, incluso para muebles','La existencia de una sentencia judicial previa en todo caso'],'La posesión regular se define por requisitos establecidos en el Código Civil.','Código Civil, posesión regular');

  // DCI-05 Limitaciones derechos reales
  add('DCI-05','El propietario constituye a favor de otra persona el derecho de usar y gozar una cosa conservando su sustancia, en los términos legales. ¿Qué derecho real describe?','Usufructo',['Hipoteca como derecho de goce','Novación','Mandato judicial'],'El usufructo confiere uso y goce temporal de cosa ajena con los límites legales.','Código Civil, usufructo');
  add('DCI-05','Un predio soporta en beneficio de otro predio un gravamen destinado, por ejemplo, al tránsito. ¿Qué institución resulta pertinente?','Servidumbre predial',['Fianza personal','Compraventa condicional','Compensación legal'],'La servidumbre es un gravamen impuesto sobre un predio en utilidad de otro predio de distinto dueño.','Código Civil, servidumbres');
  add('DCI-05','¿Cuál rasgo distingue el derecho de uso y habitación del usufructo?','Su extensión está limitada a las necesidades personales del usuario o habitador y su familia conforme al título y la ley',['Confiere siempre facultad ilimitada de disposición','Es un derecho personal de crédito sin relación con cosa alguna','Sólo puede existir sobre bienes incorporales'],'Uso y habitación son derechos reales con alcance más restringido que el usufructo.','Código Civil, uso y habitación');
  add('DCI-05','¿Qué criterio debe aplicarse a una limitación convencional o legal del dominio?','Determinar su título, contenido, duración y oponibilidad conforme al tipo de derecho real o gravamen',['Presumir que toda limitación extingue el dominio','Entender que puede crearse cualquier derecho real sin habilitación legal','Considerar que las limitaciones nunca afectan a terceros'],'Los derechos reales y gravámenes se rigen por tipos y requisitos definidos por el ordenamiento.','Código Civil, derechos reales y limitaciones del dominio');

  // DCI-06 Acciones posesorias y reivindicatoria (sentido amplio)
  add('DCI-06','El dueño no poseedor de una cosa singular pretende recuperarla de quien la posee sin ser dueño. ¿Qué acción es paradigmáticamente pertinente?','La acción reivindicatoria',['La acción de nulidad procesal','La querella de amparo constitucional','La acción de indemnización laboral'],'La reivindicación protege el dominio permitiendo al dueño reclamar la cosa singular que no posee.','Código Civil, acción reivindicatoria');
  add('DCI-06','Una persona busca conservar o recuperar la posesión de un bien raíz frente a una perturbación o despojo, sin discutir necesariamente el dominio. ¿Qué grupo de acciones debe examinar?','Las acciones posesorias',['Sólo la acción reivindicatoria','Exclusivamente la nulidad absoluta','La acción penal pública'],'Las acciones posesorias tutelan la posesión de bienes raíces y derechos reales constituidos en ellos bajo los requisitos legales.','Código Civil, acciones posesorias');
  add('DCI-06','¿Qué diferencia central existe entre reivindicación y acción posesoria?','La reivindicación se funda en el dominio; la acción posesoria tutela la posesión en los términos legales',['Ambas exigen siempre acreditar dominio inscrito','La acción posesoria sólo protege créditos','La reivindicación tiene por objeto exclusivo sancionar delitos'],'Las acciones protegen posiciones jurídicas distintas y exigen presupuestos propios.','Código Civil, reivindicación y acciones posesorias');
  add('DCI-06','Antes de escoger entre una acción posesoria y reivindicatoria, ¿qué pregunta debe resolverse primero?','Si el actor pretende tutelar la posesión o hacer valer su derecho de dominio sobre la cosa',['Cuál tribunal tiene el edificio más cercano','Si el demandado reconoce una deuda de dinero','Si existe un contrato de trabajo entre las partes'],'La pretensión y el derecho invocado determinan el remedio sustantivo adecuado.','Código Civil, acciones reales y posesorias');

  // DCI-07 Obligaciones
  add('DCI-07','Una obligación consiste en entregar una cosa determinada. ¿Qué debe hacer el deudor para cumplir correctamente?','Realizar la prestación debida en la forma, tiempo y lugar que correspondan conforme al título y la ley',['Entregar cualquier cosa de valor semejante sin acuerdo','Sustituir unilateralmente la prestación por dinero en todo caso','Esperar siempre una sentencia judicial antes de cumplir'],'El pago es la prestación de lo que se debe y debe ajustarse al contenido de la obligación.','Código Civil, pago efectivo');
  add('DCI-07','Dos personas son deudoras de una misma prestación divisible. ¿Se presume solidaridad por el solo hecho de existir varios deudores?','No; la solidaridad debe provenir de la ley, testamento o convención en los casos permitidos',['Sí; toda pluralidad de deudores es solidaria','Sí; pero sólo si la obligación es civil','No; porque la solidaridad está prohibida en Chile'],'La solidaridad no se presume y requiere fuente jurídica.','Código Civil, obligaciones solidarias');
  add('DCI-07','¿Qué efecto caracteriza a una condición suspensiva pendiente?','Mientras no se cumpla, suspende el nacimiento o exigibilidad del derecho condicionado según el régimen aplicable',['Extingue definitivamente toda obligación desde el inicio','Convierte automáticamente la obligación en solidaria','Produce siempre novación'],'Las modalidades modifican los efectos normales de la obligación según su tipo.','Código Civil, obligaciones condicionales');
  add('DCI-07','Si el deudor incurre en incumplimiento imputable de una obligación contractual, ¿qué debe analizar el acreedor antes de exigir indemnización?','Los presupuestos de responsabilidad contractual, incluida imputabilidad, daño y relación causal, además del régimen de mora cuando corresponda',['Sólo la existencia formal del contrato, pues el daño se presume siempre','Exclusivamente la voluntad posterior del deudor','La posesión inscrita del acreedor'],'La indemnización contractual exige los presupuestos previstos por el régimen de obligaciones.','Código Civil, efectos de las obligaciones');
  add('DCI-07','Una deuda se extingue porque acreedor y deudor pasan a ser la misma persona respecto de la misma obligación. ¿Qué modo de extinguir opera?','La confusión',['La tradición','La lesión enorme','La accesión'],'La confusión extingue la obligación cuando concurren en una persona las calidades incompatibles de acreedor y deudor.','Código Civil, modos de extinguir las obligaciones');

  // DCI-08 Teoría contratos
  add('DCI-08','Dos partes celebran válidamente un contrato. ¿Qué principio expresa que, por regla general, deben cumplirlo como una ley para ellas?','La fuerza obligatoria del contrato',['La libre revocación unilateral de todo contrato','La inexistencia de buena fe contractual','La relatividad de la competencia judicial'],'Los contratos legalmente celebrados obligan a quienes los celebran y no pueden invalidarse sino por causas legales o consentimiento mutuo cuando proceda.','Código Civil, art. 1545');
  add('DCI-08','¿Qué exige la buena fe en la ejecución contractual?','Ejecutar el contrato atendiendo no sólo a lo expresamente pactado sino también a aquello que emana de su naturaleza, la ley o la costumbre en los términos legales',['Interpretar siempre contra cualquier deber implícito','Permitir el incumplimiento si resulta económicamente conveniente','Eliminar toda consecuencia de la culpa'],'La buena fe objetiva integra la ejecución contractual.','Código Civil, art. 1546');
  add('DCI-08','Un contrato genera, por regla general, derechos y obligaciones entre quienes lo celebran. ¿Qué principio explica que no imponga sin más obligaciones contractuales a terceros ajenos?','El efecto relativo de los contratos',['La accesión','La indivisibilidad procesal','La competencia absoluta'],'Los efectos contractuales se predican primariamente de las partes, sin perjuicio de figuras y excepciones reconocidas por el derecho.','Código Civil, teoría general del contrato');
  add('DCI-08','Al interpretar una cláusula ambigua, ¿qué debe buscarse prioritariamente conforme al régimen civil?','La intención común de los contratantes, cuando es claramente conocida, por sobre el tenor literal aislado',['La voluntad unilateral posterior de una sola parte','La solución que siempre anule el contrato','La interpretación más extensa posible sin atender al contexto'],'Las reglas de interpretación contractual privilegian la intención común y la lectura sistemática del contrato.','Código Civil, interpretación de los contratos');

  // DCI-09 Contratos particulares
  add('DCI-09','En una compraventa, ¿cuáles son las prestaciones principales de las partes?','El vendedor debe dar la cosa y el comprador pagar el precio, además de las obligaciones accesorias legales',['Ambas partes sólo deben custodiar la cosa','El comprador transfiere la cosa y el vendedor paga el precio','El vendedor sólo promete negociar en el futuro'],'La compraventa genera obligaciones recíprocas típicas en torno a cosa y precio.','Código Civil, compraventa');
  add('DCI-09','En el arrendamiento de una cosa, ¿qué obligación caracteriza al arrendador?','Proporcionar el goce de la cosa al arrendatario en los términos del contrato y la ley',['Transferir necesariamente el dominio al arrendatario','Pagar siempre la renta al arrendatario','Renunciar a toda facultad sobre la cosa de manera perpetua'],'El arrendamiento concede goce temporal a cambio de un precio sin transferir por sí mismo el dominio.','Código Civil, arrendamiento');
  add('DCI-09','Una persona encarga a otra la gestión de uno o más negocios por su cuenta. ¿Qué contrato debe analizarse?','El mandato',['La permuta necesariamente','El depósito irregular en todo caso','La hipoteca como contrato de gestión'],'El mandato encarga la gestión de negocios a otra persona, con el alcance previsto por el contrato y la ley.','Código Civil, mandato');
  add('DCI-09','Al estudiar un mutuo de dinero, ¿qué característica resulta central?','El mutuario recibe cosas fungibles con obligación de restituir otras tantas del mismo género y calidad, según el régimen aplicable',['Debe restituir exactamente las mismas especies entregadas','El contrato transfiere únicamente tenencia y nunca dominio de lo fungible','Sólo puede existir entre comerciantes'],'El mutuo recae sobre fungibles y genera obligación de restitución por equivalencia.','Código Civil, mutuo');

  // DCI-10 Responsabilidad civil
  add('DCI-10','Una parte incumple culpablemente un contrato válido y causa un daño a su contraparte. ¿Qué estatuto debe examinarse inicialmente?','La responsabilidad contractual derivada del incumplimiento',['La responsabilidad extracontractual como única vía posible','La prescripción adquisitiva','La tutela laboral'],'La existencia de vínculo contractual y el incumplimiento orientan inicialmente al régimen contractual, sin perjuicio de problemas de concurrencia que deban estudiarse.','Código Civil, responsabilidad contractual');
  add('DCI-10','Una persona causa culpablemente un daño a otra sin que entre ellas exista un contrato que regule esa conducta. ¿Qué régimen resulta paradigmáticamente pertinente?','La responsabilidad extracontractual',['La resolución por incumplimiento contractual','La evicción de la compraventa','La novación subjetiva'],'Los delitos y cuasidelitos civiles fundan responsabilidad extracontractual cuando concurren sus presupuestos.','Código Civil, arts. 2314 y siguientes');
  add('DCI-10','¿Por qué el daño es un elemento indispensable de la responsabilidad civil indemnizatoria?','Porque la indemnización busca reparar un perjuicio jurídicamente atribuible; sin daño no existe objeto indemnizable',['Porque basta cualquier ilegalidad aunque no produzca perjuicio','Porque el daño reemplaza el nexo causal','Porque sólo se indemnizan sanciones penales'],'La responsabilidad civil exige daño y los demás presupuestos del estatuto aplicable.','Código Civil, responsabilidad civil');
  add('DCI-10','Si el daño se habría producido de igual modo sin la conducta imputada, ¿qué elemento de responsabilidad debe examinarse críticamente?','La relación de causalidad',['La capacidad sucesoria','La tradición','La competencia relativa'],'Debe existir un nexo jurídicamente relevante entre conducta y daño para atribuir responsabilidad.','Código Civil; doctrina y jurisprudencia sobre causalidad');
  add('DCI-10','En responsabilidad contractual, ¿qué función cumple la previsibilidad del daño según el régimen de imputación aplicable?','Delimita, en ciertos supuestos, la extensión de los perjuicios indemnizables conforme a las reglas del Código Civil',['Convierte todo daño remoto en indemnizable','Elimina siempre la necesidad de incumplimiento','Determina la competencia del tribunal por sí sola'],'El Código Civil contempla reglas sobre daños previstos o previsibles y tratamiento distinto cuando existe dolo.','Código Civil, efectos de las obligaciones');

  // DCI-11 Sucesión
  add('DCI-11','Una persona muere sin testamento válido. ¿Qué régimen determina quiénes son llamados a sucederla?','Las reglas de sucesión intestada',['Las reglas de tradición entre vivos','La prescripción extintiva','La sociedad conyugal automáticamente'],'La sucesión intestada opera cuando falta disposición testamentaria eficaz en los casos previstos por la ley.','Código Civil, sucesión intestada');
  add('DCI-11','¿Qué diferencia básica existe entre heredero y legatario?','El heredero sucede a título universal; el legatario, por regla general, a título singular',['El legatario sucede siempre en todas las deudas hereditarias como heredero universal','El heredero sólo recibe cosas corporales individualizadas','No existe diferencia jurídica entre ambos'],'La sucesión distingue asignaciones a título universal y singular.','Código Civil, asignaciones por causa de muerte');
  add('DCI-11','¿Qué función cumplen las asignaciones forzosas?','Limitan la libertad de disposición del causante en favor de quienes la ley protege en los términos legales',['Permiten al testador excluir libremente toda regla sucesoria','Sólo se aplican a sucesiones abiertas en el extranjero','Son recomendaciones sin efecto jurídico'],'El Código Civil reserva porciones o derechos a determinados asignatarios conforme a su estatuto.','Código Civil, asignaciones forzosas');
  add('DCI-11','Para determinar la ley aplicable y los derechos sucesorios, ¿qué hecho marca la apertura de la sucesión?','La muerte del causante',['La inscripción de la posesión efectiva como único hecho constitutivo','El otorgamiento de cualquier mandato','La primera venta de un bien hereditario'],'La sucesión se abre al momento de la muerte, sin perjuicio de actuaciones posteriores de posesión efectiva y partición.','Código Civil, apertura de la sucesión');

  // DCI-12 Matrimonio/AUC patrimonial
  add('DCI-12','Un cónyuge solicita declarar un inmueble residencia principal de la familia como bien familiar. ¿Qué institución debe estudiarse?','El régimen de bienes familiares',['La prescripción adquisitiva extraordinaria','La servidumbre legal de tránsito','La sociedad colectiva civil'],'Los bienes familiares protegen determinados bienes vinculados al hogar bajo presupuestos y efectos legales específicos.','Código Civil, bienes familiares');
  add('DCI-12','¿Qué debe identificarse primero para resolver un conflicto patrimonial entre cónyuges?','El régimen patrimonial aplicable al matrimonio y los actos o bienes concretos involucrados',['La edad del tribunal que conocerá','La sola duración del matrimonio, sin revisar el régimen','La existencia de hijos como único criterio patrimonial'],'Sociedad conyugal, separación de bienes y participación en los gananciales tienen reglas distintas.','Código Civil, regímenes patrimoniales del matrimonio');
  add('DCI-12','En un Acuerdo de Unión Civil, ¿es correcto aplicar automáticamente todas las reglas patrimoniales del matrimonio?','No; deben aplicarse las normas propias del AUC y las remisiones legales que correspondan',['Sí; matrimonio y AUC son jurídicamente idénticos en todo aspecto','Sí; porque toda convivencia genera sociedad conyugal','No; porque el AUC carece de cualquier efecto patrimonial'],'El AUC tiene un estatuto propio que debe distinguirse del matrimonio.','Ley N° 20.830');
  add('DCI-12','Al terminar un matrimonio, una parte invoca compensación económica. ¿Qué debe evitarse?','Tratarla como consecuencia automática de todo término; deben acreditarse sus presupuestos legales',['Analizar el menoscabo económico y las circunstancias legales','Distinguirla de una indemnización general de perjuicios','Considerar el trabajo doméstico y de cuidados cuando sea jurídicamente pertinente'],'La compensación económica tiene requisitos y criterios específicos y no nace por el solo hecho del divorcio o nulidad.','Ley de Matrimonio Civil');

  // DCI-13 Filiación
  add('DCI-13','¿Qué principio orienta actualmente los efectos jurídicos de la filiación, cualquiera sea su origen?','La igualdad jurídica de los hijos en los términos establecidos por la ley',['La existencia de categorías de hijos con distinta dignidad civil','La ausencia de derechos sucesorios para hijos no matrimoniales','La subordinación de toda filiación a un contrato entre los padres'],'El derecho chileno eliminó discriminaciones entre categorías de hijos y regula efectos comunes de filiación.','Código Civil, filiación');
  add('DCI-13','Una persona pretende obtener judicialmente la determinación de una filiación controvertida. ¿Qué institución corresponde estudiar?','Las acciones de filiación y su régimen probatorio',['La acción reivindicatoria','La tercería de prelación','La querella posesoria'],'El Código Civil regula acciones destinadas a reclamar o impugnar la filiación, con reglas probatorias específicas.','Código Civil, acciones de filiación');
  add('DCI-13','¿Qué relevancia tiene la prueba biológica en un juicio de filiación?','Constituye un medio probatorio de especial importancia dentro del régimen legal y debe valorarse conforme a sus reglas',['Es jurídicamente inadmisible en toda acción de filiación','Vincula al tribunal aunque se haya obtenido ilícitamente en cualquier circunstancia','Sólo puede utilizarse si ambas partes renuncian a la acción'],'El régimen de filiación contempla pruebas biológicas y consecuencias procesales reguladas por ley.','Código Civil; Ley N° 19.968, según corresponda');
  add('DCI-13','Antes de resolver una impugnación de filiación, ¿qué debe determinarse?','La acción concreta ejercida, legitimación, plazo y estado de filiación que se pretende controvertir',['Únicamente el interés patrimonial del demandante','La competencia de un árbitro privado elegido después del juicio','La existencia de un contrato de compraventa'],'Las acciones de filiación poseen presupuestos y legitimaciones propias que deben identificarse con precisión.','Código Civil, acciones de filiación');

  // DPC-01 Proceso y actos procesales
  add('DPC-01','¿Qué finalidad cumple el principio de bilateralidad de la audiencia?','Dar a las partes oportunidad efectiva de conocer y controvertir las pretensiones y antecedentes relevantes',['Permitir que una parte decida sin conocimiento de la otra en todo caso','Eliminar las reglas de notificación','Impedir al tribunal dirigir el procedimiento'],'La contradicción integra las garantías del proceso y admite las modulaciones expresamente previstas por ley.','Código de Procedimiento Civil; garantías del debido proceso');
  add('DPC-01','Un acto procesal se ejecuta fuera del plazo fatal que la ley establece. ¿Qué debe analizarse?','El efecto preclusivo asociado al vencimiento del plazo y las excepciones legales aplicables',['La validez automática por tratarse de un acto procesal','La adquisición del dominio por prescripción','La transformación del acto en sentencia'],'Los plazos y la preclusión ordenan el avance del procedimiento.','Código de Procedimiento Civil, reglas generales');
  add('DPC-01','¿Qué significa, en términos procesales, la preclusión?','La pérdida, extinción o consumación de una facultad procesal por las causas reconocidas por el sistema',['La posibilidad de repetir ilimitadamente cualquier actuación','La facultad del juez de modificar una ley','La transferencia de competencia a un órgano administrativo'],'La preclusión impide retrocesos o reiteraciones incompatibles con la estructura del proceso.','Derecho procesal civil; Código de Procedimiento Civil');
  add('DPC-01','Al evaluar la invalidez de un acto procesal, ¿qué criterio debe evitarse?','Suponer que cualquier defecto formal produce necesariamente nulidad, sin examinar perjuicio, finalidad y régimen aplicable',['Identificar la norma infringida','Examinar si hubo indefensión','Considerar mecanismos de subsanación previstos por la ley'],'La nulidad procesal responde a presupuestos específicos y no a un formalismo automático.','Código de Procedimiento Civil; doctrina de nulidad procesal');

  // DPC-02 Cosa juzgada
  add('DPC-02','Una sentencia firme decide el fondo de una controversia entre las mismas partes. Luego se intenta un nuevo juicio idéntico. ¿Qué institución debe examinarse?','La excepción y autoridad de cosa juzgada',['La prórroga de competencia','La conciliación obligatoria administrativa','La acumulación posesoria'],'La cosa juzgada impide volver a discutir lo decidido cuando concurren sus presupuestos.','Código de Procedimiento Civil, cosa juzgada');
  add('DPC-02','¿Qué finalidad persigue la cosa juzgada material?','Otorgar estabilidad a lo decidido e impedir una nueva decisión incompatible sobre el mismo conflicto dentro de sus límites',['Permitir revisar indefinidamente toda sentencia firme','Transformar una sentencia en ley general','Eliminar cualquier recurso antes de que la sentencia quede firme'],'La cosa juzgada asegura certeza y estabilidad dentro de los límites subjetivos y objetivos definidos por el derecho.','Código de Procedimiento Civil');
  add('DPC-02','Para oponer cosa juzgada, ¿qué debe compararse entre el proceso anterior y el nuevo?','Los elementos de identidad exigidos por la ley y el contenido efectivamente decidido',['Sólo el número de rol de ambas causas','Únicamente si ambos juicios se tramitan en el mismo edificio','La identidad de abogados, aunque las partes sean distintas'],'La excepción requiere revisar las identidades y alcance de la sentencia previa conforme al CPC.','Código de Procedimiento Civil, excepción de cosa juzgada');
  add('DPC-02','¿Es correcto afirmar que toda resolución interlocutoria produce exactamente la misma cosa juzgada material que una sentencia definitiva sobre el fondo?','No; deben distinguirse naturaleza, contenido y efectos de la resolución conforme al régimen procesal',['Sí; toda resolución produce idéntico efecto material','Sí; incluso un simple decreto impide cualquier juicio futuro','No; porque sólo los acuerdos privados producen cosa juzgada'],'Los efectos dependen del tipo de resolución y de aquello que efectivamente decidió.','Código de Procedimiento Civil, resoluciones judiciales y cosa juzgada');

  // DPC-03 Reglas comunes
  add('DPC-03','Una resolución debe ponerse en conocimiento de una parte para producir efectos procesales respecto de ella. ¿Qué institución cumple esa función?','La notificación judicial',['La tradición civil','La prescripción adquisitiva','La inscripción posesoria'],'Las notificaciones comunican resoluciones conforme a formas y efectos previstos por el CPC y la tramitación electrónica.','Código de Procedimiento Civil; Ley N° 20.886');
  add('DPC-03','¿Qué debe verificarse antes de concluir que un plazo procesal venció?','La naturaleza del plazo, su forma de cómputo, notificación que lo inicia y reglas sobre días hábiles o suspensión aplicables',['Sólo la fecha que estime razonable una parte','La cuantía de la pretensión como único factor','Si el abogado recibió una llamada informal'],'El cómputo correcto exige identificar la regla específica del plazo y el hito inicial.','Código de Procedimiento Civil; reglas de cómputo');
  add('DPC-03','Una parte comparece mediante mandatario judicial. ¿Qué debe revisarse para saber qué actuaciones puede realizar éste?','La suficiencia del mandato y las facultades ordinarias o especiales requeridas por la ley',['La antigüedad profesional del mandatario como único requisito','La voluntad del adversario','La inscripción de dominio del cliente'],'El patrocinio y poder judicial se rigen por reglas que distinguen facultades ordinarias y especiales.','Código de Procedimiento Civil; Ley N° 18.120');
  add('DPC-03','¿Qué criterio rige la formación del expediente en la tramitación judicial electrónica?','Debe atenderse al expediente electrónico y a las reglas de ingreso, firma, registro y disponibilidad establecidas por la ley y auto acordados',['Todo expediente debe mantenerse exclusivamente en papel','Los escritos electrónicos carecen de valor jurídico','Cada parte decide unilateralmente qué actuaciones integran el expediente'],'La Ley N° 20.886 reconoce y regula la tramitación electrónica de procedimientos judiciales.','Ley N° 20.886');
  add('DPC-03','Una notificación presenta un defecto, pero la parte realiza actuaciones que demuestran conocimiento inequívoco de la resolución. ¿Qué institución puede ser relevante según el caso?','La notificación tácita, si concurren sus presupuestos legales',['La prescripción adquisitiva','La nulidad absoluta del contrato','La cosa juzgada penal'],'El CPC reconoce supuestos en que el conocimiento manifestado mediante actuaciones puede producir efectos de notificación.','Código de Procedimiento Civil, notificación tácita');

  // DPC-04 Ordinario
  add('DPC-04','¿Qué función cumple el emplazamiento del demandado en un juicio declarativo?','Asegurar su conocimiento de la demanda y la oportunidad legal de defenderse',['Transferir automáticamente el dominio de lo demandado','Transformar la demanda en sentencia','Impedir toda comparecencia del demandado'],'El emplazamiento es esencial para la bilateralidad y defensa.','Código de Procedimiento Civil, juicio ordinario');
  add('DPC-04','El demandado contesta y además formula una pretensión propia contra el demandante bajo los requisitos legales. ¿Qué figura utiliza?','La reconvención',['La reposición administrativa','La tercería posesoria','La recusación del tribunal como pretensión de fondo'],'La reconvención permite deducir una demanda del demandado contra el actor dentro del mismo proceso cuando procede.','Código de Procedimiento Civil, juicio ordinario');
  add('DPC-04','¿Cuál es la función principal de los escritos de réplica y dúplica en el procedimiento ordinario?','Permitir precisiones y respuestas dentro de los límites que la ley establece para la fase de discusión',['Abrir automáticamente un nuevo juicio','Sustituir siempre la demanda y contestación por otras completamente distintas','Dictar sentencia sin recibir la causa a prueba'],'Forman parte de la etapa de discusión y cumplen funciones delimitadas por el CPC.','Código de Procedimiento Civil, juicio ordinario');
  add('DPC-04','¿Qué finalidad tiene la conciliación judicial dentro del procedimiento ordinario cuando corresponde?','Explorar una solución acordada del conflicto bajo la intervención judicial prevista por la ley',['Obligar al juez a imponer un contrato a las partes','Reemplazar la sentencia aun si nadie acepta acuerdo','Eliminar el derecho de defensa'],'La conciliación es un mecanismo autocompositivo promovido procesalmente en la oportunidad legal.','Código de Procedimiento Civil, conciliación');
  add('DPC-04','Antes de declarar al demandado en rebeldía por no contestar, ¿qué debe verificarse especialmente?','La regularidad del emplazamiento y el vencimiento del plazo para defenderse',['La existencia de un contrato de compraventa','La propiedad del inmueble del demandado','El acuerdo del actor con el secretario'],'La rebeldía presupone una oportunidad procesal válida no ejercida.','Código de Procedimiento Civil, juicio ordinario');

  // DPC-05 Prueba
  add('DPC-05','¿Qué hechos son, por regla general, objeto de prueba en un proceso civil?','Los hechos sustanciales, pertinentes y controvertidos relevantes para decidir',['Todo hecho mencionado aunque sea pacífico e irrelevante','Sólo las normas jurídicas nacionales','Únicamente la opinión personal de los abogados'],'La actividad probatoria se concentra en hechos relevantes controvertidos conforme al procedimiento.','Código de Procedimiento Civil, prueba');
  add('DPC-05','¿Qué diferencia existe entre carga de la prueba y valoración de la prueba?','La carga distribuye el riesgo de falta de acreditación; la valoración determina el mérito de la evidencia rendida',['Son expresiones idénticas','La carga sólo se refiere a competencia y la valoración a notificaciones','La valoración decide quién debe demandar antes de iniciar el juicio'],'Son problemas distintos: quién debe acreditar y cómo se aprecia lo efectivamente probado.','Código Civil, art. 1698; Código de Procedimiento Civil');
  add('DPC-05','Una prueba fue obtenida y rendida infringiendo una regla procesal. ¿Debe considerarse automáticamente válida por ser útil?','No; deben examinarse admisibilidad, forma de incorporación y consecuencias de la infracción conforme al régimen aplicable',['Sí; toda prueba útil es siempre admisible','Sí; el fin probatorio elimina cualquier garantía','No; porque ningún error probatorio puede subsanarse jamás'],'La utilidad no sustituye las reglas legales de admisión y producción probatoria.','Código de Procedimiento Civil; garantías procesales');
  add('DPC-05','¿Qué función cumple la resolución que recibe la causa a prueba en el juicio ordinario?','Delimita los hechos sustanciales, pertinentes y controvertidos sobre los que debe recaer la prueba',['Decide definitivamente el fondo','Reemplaza la demanda','Declara prescrita toda acción no probada ese mismo día'],'La resolución fija el marco fáctico de la actividad probatoria en el procedimiento ordinario.','Código de Procedimiento Civil');

  // DPC-06 Sentencia
  add('DPC-06','Una sentencia omite decidir una acción oportunamente sometida al tribunal. ¿Qué principio o exigencia procesal debe examinarse?','La congruencia y el deber de resolver las cuestiones sometidas a decisión',['La prórroga de competencia','La tradición de bienes','La solidaridad pasiva'],'La sentencia debe guardar correspondencia con las pretensiones y defensas y resolver lo que jurídicamente corresponda.','Código de Procedimiento Civil, requisitos de sentencia');
  add('DPC-06','¿Qué diferencia básica existe entre parte considerativa y parte resolutiva de una sentencia?','La primera contiene fundamentos; la segunda expresa la decisión y sus efectos concretos',['La parte considerativa es siempre opcional y la resolutiva sólo cita doctrina','La resolutiva contiene exclusivamente prueba testimonial','No existe diferencia jurídica entre ellas'],'Las sentencias deben expresar fundamentos y decisión conforme a requisitos legales.','Código de Procedimiento Civil; Auto Acordado sobre forma de las sentencias');
  add('DPC-06','¿Por qué la motivación de una sentencia es relevante para el debido proceso?','Permite comprender la justificación fáctica y jurídica de la decisión y someterla a control mediante los mecanismos procedentes',['Porque autoriza al juez a decidir sin prueba','Porque reemplaza todos los recursos','Porque permite omitir las pretensiones de las partes'],'La fundamentación hace racional y controlable la decisión jurisdiccional.','Constitución Política de la República; Código de Procedimiento Civil');
  add('DPC-06','¿Cuándo una sentencia definitiva adquiere firmeza o ejecutoriedad según el régimen procesal?','Cuando se cumplen los presupuestos legales relativos a recursos y certificación o estado procesal correspondiente',['Desde que el juez comienza a redactarla','Sólo diez años después de dictada','Únicamente si ambas partes celebran un contrato posterior'],'La firmeza depende del régimen de recursos y de las reglas sobre ejecutoria.','Código de Procedimiento Civil, sentencias firmes o ejecutoriadas');

  // DPC-07 Incidentes
  add('DPC-07','Durante un juicio surge una cuestión accesoria que requiere pronunciamiento especial del tribunal. ¿Qué institución debe analizarse?','Un incidente',['Una sucesión intestada','Una tradición inmueble','Una negociación colectiva'],'Los incidentes son cuestiones accesorias que se suscitan durante el proceso y requieren decisión especial.','Código de Procedimiento Civil, incidentes');
  add('DPC-07','¿Puede cualquier cuestión presentada por una parte paralizar automáticamente el procedimiento principal?','No; los efectos suspensivos dependen de la naturaleza del incidente y de las reglas legales aplicables',['Sí; todo escrito incidental suspende por sí solo el juicio','Sí; incluso cuestiones manifiestamente inconexas','No; porque los incidentes nunca producen efecto alguno'],'El CPC distingue tratamiento y efectos de los incidentes según su naturaleza.','Código de Procedimiento Civil, incidentes');
  add('DPC-07','Antes de tramitar una cuestión como incidente, ¿qué debe verificarse?','Su conexión con el asunto principal, oportunidad y régimen procesal aplicable',['La existencia de una hipoteca','La nacionalidad del abogado como regla decisiva','La inscripción de un testamento'],'La admisibilidad y tramitación incidental exigen presupuestos legales.','Código de Procedimiento Civil, incidentes');
  add('DPC-07','Una parte promueve reiteradamente incidentes manifiestamente dilatorios. ¿Qué enfoque procesal es correcto?','Aplicar los mecanismos legales destinados a evitar abuso y dilación, respetando a la vez el derecho de defensa',['Aceptar cualquier incidencia sin control','Rechazar de plano toda cuestión accesoria futura','Sancionar con pérdida automática del juicio principal'],'El procedimiento contempla herramientas para disciplina y economía procesal sin eliminar la contradicción.','Código de Procedimiento Civil, incidentes y medidas contra dilación');

  // DPC-08 Cautelares/prejudiciales
  add('DPC-08','Una parte teme que durante el juicio el demandado disponga de bienes y frustre el resultado práctico de una eventual sentencia favorable. ¿Qué categoría de medidas debe examinar?','Medidas precautorias destinadas a asegurar el resultado de la acción',['Acciones de filiación','Recursos de nulidad penal','Medidas disciplinarias judiciales'],'Las medidas precautorias buscan conservar la eficacia práctica de la tutela jurisdiccional bajo requisitos legales.','Código de Procedimiento Civil, medidas precautorias');
  add('DPC-08','¿Qué exige normalmente una medida cautelar para justificar una afectación anticipada de la esfera del demandado?','Antecedentes que sustenten la pretensión y el riesgo que la medida busca evitar, en el marco de los requisitos legales',['La certeza absoluta de la sentencia futura','La simple preferencia del actor sin antecedentes','Una condena penal previa del demandado'],'La tutela cautelar exige justificación proporcional y presupuestos establecidos por el procedimiento.','Código de Procedimiento Civil, medidas precautorias');
  add('DPC-08','Una diligencia se solicita antes de presentar demanda con el objeto de preparar el juicio. ¿Qué institución puede resultar aplicable?','Una medida prejudicial preparatoria, probatoria o precautoria según su finalidad',['Una sentencia definitiva anticipada','Una transacción forzosa','Una recusación automática'],'El CPC regula medidas prejudiciales con finalidades y requisitos diversos.','Código de Procedimiento Civil, medidas prejudiciales');
  add('DPC-08','¿Por qué una medida precautoria no debe confundirse con la decisión definitiva del litigio?','Porque busca asegurar provisionalmente la eficacia del proceso sin resolver por sí sola el fondo',['Porque carece de todo efecto jurídico','Porque sólo puede dictarse después de sentencia firme','Porque transfiere siempre el dominio de los bienes afectados'],'La cautela es instrumental y provisoria respecto de la pretensión principal.','Código de Procedimiento Civil, tutela cautelar');

  // DPC-09 Ejecutivo y sumario
  add('DPC-09','Para iniciar un juicio ejecutivo de obligación de dar, ¿qué presupuesto debe examinarse especialmente?','La existencia de un título ejecutivo y una obligación que reúna los requisitos legales de exigibilidad y determinación',['La mera afirmación del acreedor sin documento o antecedente alguno','Una sentencia penal condenatoria en todo caso','La inscripción de cualquier bien del deudor'],'La ejecución requiere un título al que la ley atribuya fuerza ejecutiva y una obligación ejecutable.','Código de Procedimiento Civil, juicio ejecutivo');
  add('DPC-09','El ejecutado pretende oponerse a la ejecución. ¿Puede invocar cualquier argumento en cualquier momento?','No; la oposición se somete a plazo, forma y catálogo de excepciones previsto por el procedimiento ejecutivo',['Sí; no existe plazo ni catálogo alguno','Sí; basta una objeción verbal en cualquier etapa','No; porque el ejecutado carece de derecho a defensa'],'La oposición ejecutiva es concentrada y reglada.','Código de Procedimiento Civil, excepciones del juicio ejecutivo');
  add('DPC-09','¿Qué finalidad distingue al procedimiento sumario frente al ordinario?','Proporcionar una tramitación más breve y concentrada para los casos en que la ley lo dispone o la naturaleza de la acción requiere rapidez',['Eliminar totalmente el derecho de defensa','Resolver sólo asuntos penales','Servir exclusivamente para ejecutar sentencias firmes'],'El procedimiento sumario busca rapidez y concentración sin prescindir de garantías procesales.','Código de Procedimiento Civil, juicio sumario');
  add('DPC-09','En un ejecutivo, ¿qué función cumple el embargo?','Afectar bienes del ejecutado al cumplimiento forzado de la obligación dentro del procedimiento',['Transferir de inmediato y gratuitamente el dominio al ejecutante','Declarar extinguida la obligación','Convertir el juicio en declarativo ordinario automáticamente'],'El embargo individualiza y afecta bienes para la realización forzada conforme a las reglas de ejecución.','Código de Procedimiento Civil, embargo');
  add('DPC-09','Un tercero afirma ser dueño del bien embargado y pretende excluirlo de la ejecución. ¿Qué institución procesal debe analizarse?','Una tercería fundada en el derecho que el tercero invoca, según su clase y requisitos',['Una reconvención penal','Una acción de inaplicabilidad constitucional','Una recusación del receptor como única defensa'],'Las tercerías permiten a terceros hacer valer determinados derechos en la ejecución bajo el estatuto del CPC.','Código de Procedimiento Civil, tercerías');

  // DPC-10 Recursos
  add('DPC-10','Una parte pide al mismo tribunal que dictó una resolución que la modifique por existir un error susceptible de esa impugnación. ¿Qué recurso debe examinarse primero según la naturaleza de la resolución?','La reposición, cuando la ley la hace procedente',['La casación ante la Contraloría','La revisión administrativa del contrato','La acción reivindicatoria'],'La reposición busca que el mismo tribunal reconsidere determinadas resoluciones conforme al CPC.','Código de Procedimiento Civil, reposición');
  add('DPC-10','¿Qué función cumple la apelación?','Permitir que el tribunal superior revise la resolución impugnada dentro de la competencia que abre el recurso',['Iniciar siempre un juicio completamente nuevo','Derogar la ley aplicada','Convertir automáticamente cualquier resolución en sentencia firme'],'La apelación activa revisión por el superior según resoluciones, agravios y efectos legalmente regulados.','Código de Procedimiento Civil, apelación');
  add('DPC-10','Antes de interponer casación, ¿qué debe determinarse con precisión?','La naturaleza del vicio, la resolución impugnable, causal, preparación cuando corresponda y plazo',['Sólo si la parte perdió por cualquier motivo','La conveniencia de repetir toda la prueba','La posibilidad de agregar libremente hechos nuevos en sede de casación'],'La casación es un recurso extraordinario sometido a presupuestos estrictos.','Código de Procedimiento Civil, casación');
  add('DPC-10','¿Por qué no puede afirmarse que todos los recursos suspenden automáticamente el cumplimiento de la resolución?','Porque los efectos de cada recurso dependen de su régimen legal y de cómo sea concedido',['Porque ningún recurso produce efecto alguno','Porque sólo el demandante puede suspender sentencias','Porque la suspensión depende exclusivamente del secretario'],'Los efectos devolutivo y suspensivo deben determinarse para cada recurso y resolución.','Código de Procedimiento Civil, recursos');

  return out;
})();
