/* Banco PF93 — especialidad familia. Borrador para revisión humana. */
const PF93_DRAFT_FAMILIA = (() => {
  const out=[]; const seq={};
  function add(tema,pregunta,correcta,distractores,explicacion,fuente){seq[tema]=(seq[tema]||0)+1;const pos=(out.length+seq[tema])%4;const opciones=distractores.slice(0,3);opciones.splice(pos,0,correcta);out.push({id:`pf93-${tema.toLowerCase()}-${String(seq[tema]).padStart(2,'0')}`,temaPF93:tema,pregunta,opciones:opciones.map((text,i)=>({id:'ABCD'[i],text})),respuesta:pos,explicacion,fuente:{cita:fuente,verificada:false,revisadaEn:null},estado:'revision_humana',dificultad:'media',tipo:'alternativa'});}

  // DFA-01 Matrimonio y AUC
  add('DFA-01','Dos personas pretenden contraer matrimonio. Antes de analizar sus efectos, ¿qué debe verificarse jurídicamente?','Que concurran los requisitos de existencia y validez y no exista impedimento legal aplicable',['Que hayan celebrado previamente un AUC','Que posean bienes en común','Que cuenten con autorización judicial en todos los casos'],'La validez matrimonial exige examinar capacidad, consentimiento y demás requisitos e impedimentos legales.','Ley de Matrimonio Civil, texto vigente');
  add('DFA-01','¿Qué diferencia metodológica debe mantenerse entre matrimonio y Acuerdo de Unión Civil?','Son instituciones distintas, con estatutos propios, aunque la ley pueda atribuirles efectos semejantes en materias determinadas',['Son jurídicamente idénticos en todos sus efectos','El AUC genera siempre sociedad conyugal','El matrimonio carece de efectos patrimoniales'],'Cada institución tiene requisitos, efectos y formas de término regulados específicamente.','Ley de Matrimonio Civil; Ley N° 20.830');
  add('DFA-01','Una persona casada pretende celebrar un nuevo matrimonio sin que el anterior haya terminado. ¿Qué cuestión debe examinarse?','La existencia de un vínculo matrimonial vigente como impedimento para un nuevo matrimonio',['La duración mínima de la convivencia','La autorización del empleador','La inscripción de bienes familiares'],'El vínculo matrimonial vigente afecta la posibilidad de contraer válidamente otro matrimonio.','Ley de Matrimonio Civil');
  add('DFA-01','¿Qué debe distinguirse al estudiar el término de un matrimonio?','Las causales y efectos de muerte, nulidad y divorcio, según corresponda',['Un único mecanismo llamado revocación unilateral','La prescripción adquisitiva del vínculo','La mera separación de hecho como extinción automática en cualquier plazo'],'Las formas de terminación matrimonial poseen requisitos y efectos diferenciados.','Ley de Matrimonio Civil');
  add('DFA-01','En un AUC, una parte consulta cómo puede terminar el acuerdo. ¿Qué respuesta es jurídicamente adecuada?','Debe identificarse la causal legal de término y cumplirse las formalidades y comunicaciones que correspondan',['Basta cualquier manifestación privada no comunicada en todo caso','El AUC sólo termina por sentencia penal','El AUC es indisoluble'],'La Ley N° 20.830 establece causales y formalidades específicas de término.','Ley N° 20.830');

  // DFA-02 Compensación económica
  add('DFA-02','¿Qué hecho constituye el núcleo de la compensación económica matrimonial?','Un menoscabo económico derivado de que uno de los cónyuges no pudo desarrollar actividad remunerada o lo hizo en menor medida por dedicarse al cuidado de hijos o al hogar, bajo los presupuestos legales',['La existencia de divorcio por sí sola','Cualquier diferencia de ingresos entre cónyuges sin relación con la vida familiar','Una sanción automática al cónyuge con mayor patrimonio'],'La compensación atiende al menoscabo económico conectado con la distribución de roles familiares.','Ley de Matrimonio Civil, compensación económica');
  add('DFA-02','¿Es la compensación económica una indemnización automática de perjuicios por el fracaso matrimonial?','No; es una institución con fundamento, requisitos y criterios propios definidos por la ley',['Sí; todo divorcio genera indemnización por daño moral','Sí; equivale exactamente a responsabilidad extracontractual','No; porque nunca puede tener contenido patrimonial'],'Su fundamento no coincide sin más con la responsabilidad civil común.','Ley de Matrimonio Civil');
  add('DFA-02','Al fijar procedencia y cuantía de compensación económica, ¿qué debe hacer el tribunal?','Considerar las circunstancias y criterios que la ley establece, atendidos los hechos acreditados',['Aplicar siempre un porcentaje fijo del patrimonio','Dividir todos los bienes por mitades sin revisar el régimen patrimonial','Usar sólo la edad de quien demanda'],'La ley entrega criterios para determinar menoscabo y cuantía, que requieren fundamentación.','Ley de Matrimonio Civil');
  add('DFA-02','¿Pueden los cónyuges acordar la compensación económica?','Sí, dentro de los requisitos, formalidades y control que la ley contempla',['No; sólo puede fijarla de oficio la Corte Suprema','Sí, sin ninguna formalidad ni control incluso si la ley exige aprobación','No; porque la compensación carece de contenido disponible'],'La ley admite acuerdo sujeto a condiciones y control jurídico.','Ley de Matrimonio Civil');
  add('DFA-02','Una persona pide compensación económica, pero no acredita conexión entre su menor desarrollo laboral y la dedicación familiar invocada. ¿Qué problema surge?','Puede faltar un presupuesto causal del menoscabo económico exigido por la institución',['La compensación debe concederse igual por existir matrimonio','La ausencia de prueba aumenta automáticamente la cuantía','El tribunal debe presumir todos los hechos sin antecedentes'],'La compensación requiere acreditar sus presupuestos fácticos y jurídicos.','Ley de Matrimonio Civil; reglas probatorias aplicables');

  // DFA-03 Bienes familiares
  add('DFA-03','¿Qué finalidad cumple la declaración de un inmueble como bien familiar?','Proteger el inmueble que sirve de residencia principal de la familia y limitar ciertos actos de disposición conforme a la ley',['Transferir automáticamente el dominio al cónyuge no propietario','Convertir el inmueble en bien nacional de uso público','Extinguir todas las deudas garantizadas con el inmueble'],'La institución protege la residencia familiar sin transferir por sí sola el dominio.','Código Civil, bienes familiares');
  add('DFA-03','¿La declaración de bien familiar altera por sí sola quién es dueño del inmueble?','No; impone efectos y limitaciones específicos sin cambiar automáticamente la titularidad dominical',['Sí; el dominio pasa siempre al cónyuge solicitante','Sí; cada hijo adquiere una cuota','No; porque la declaración carece de todo efecto jurídico'],'La institución afecta facultades de disposición, no la titularidad por el solo hecho de declararse.','Código Civil, bienes familiares');
  add('DFA-03','Antes de autorizar un acto respecto de un bien familiar, ¿qué debe revisarse?','La naturaleza del acto y los consentimientos o autorizaciones que el Código Civil exige',['Sólo la voluntad del tercero adquirente','La existencia de sentencia penal previa','La duración del matrimonio como único elemento'],'Los bienes familiares tienen un régimen especial de actos y autorizaciones.','Código Civil, bienes familiares');
  add('DFA-03','¿Qué hecho puede justificar pedir el cese de la calidad de bien familiar?','Que hayan desaparecido los presupuestos que justificaban esa afectación, conforme al régimen legal',['La mera voluntad unilateral del propietario en cualquier momento y sin control','Que el inmueble aumente de valor','La existencia de cualquier deuda personal'],'El cese debe analizarse a partir de las causales y procedimiento previstos.','Código Civil, bienes familiares');

  // DFA-04 Regímenes patrimoniales
  add('DFA-04','Una pareja casada consulta quién administra determinados bienes. ¿Qué dato debe identificarse primero?','El régimen patrimonial del matrimonio y la naturaleza u origen del bien',['La profesión de los cónyuges','El lugar de celebración como único criterio','La cantidad de hijos sin revisar el régimen'],'La administración y titularidad varían entre sociedad conyugal, separación y participación en los gananciales.','Código Civil, regímenes matrimoniales');
  add('DFA-04','¿Qué caracteriza a la separación total de bienes?','Cada cónyuge conserva, en principio, administración y disposición de su patrimonio propio conforme a la ley',['Todos los bienes pasan a un patrimonio común administrado por el juez','Se crea necesariamente una sociedad conyugal','Ninguno de los cónyuges puede adquirir bienes'],'La separación excluye la masa común propia de la sociedad conyugal, sin perjuicio de otras instituciones familiares.','Código Civil, separación de bienes');
  add('DFA-04','¿Qué debe evitarse al analizar la sociedad conyugal?','Suponer que todo bien de cualquiera de los cónyuges ingresa de idéntica forma al haber social',['Distinguir haber absoluto, relativo y bienes propios cuando corresponda','Examinar origen y fecha de adquisición','Revisar recompensas al liquidar'],'El régimen contiene masas patrimoniales y reglas de administración y liquidación diferenciadas.','Código Civil, sociedad conyugal');
  add('DFA-04','¿Puede aplicarse al AUC automáticamente el régimen de sociedad conyugal?','No; el AUC se rige por su estatuto patrimonial propio y las opciones que la ley contempla',['Sí; todo AUC crea sociedad conyugal','Sí; salvo que exista sentencia penal','No; porque el AUC nunca produce efectos patrimoniales'],'El acuerdo de unión civil posee regulación patrimonial propia.','Ley N° 20.830');

  // DFA-05 Divorcio
  add('DFA-05','¿Qué debe acreditarse para obtener divorcio por cese de convivencia?','El cese de convivencia durante el tiempo y bajo las condiciones que correspondan a la causal invocada',['Sólo la voluntad de un cónyuge sin requisito temporal alguno en cualquier caso','La existencia de hijos comunes','Una condena penal previa del otro cónyuge'],'Las causales de divorcio y sus presupuestos están definidas por la Ley de Matrimonio Civil.','Ley de Matrimonio Civil');
  add('DFA-05','¿Qué diferencia central existe entre divorcio sanción y divorcio por cese de convivencia?','El primero se funda en una falta imputable grave que haga intolerable la vida en común; el segundo en el cese durante el período legal',['Son nombres distintos para la misma causal sin diferencias probatorias','El divorcio sanción exige siempre acuerdo de ambos','El cese de convivencia nunca requiere prueba'],'Las causales poseen hechos constitutivos y exigencias probatorias distintas.','Ley de Matrimonio Civil');
  add('DFA-05','¿Qué efecto produce el divorcio respecto del vínculo matrimonial?','Pone término al matrimonio para el futuro, con los efectos personales y patrimoniales que la ley establece',['Declara que el matrimonio jamás existió','Borra automáticamente toda obligación ya devengada','Convierte a los ex cónyuges en convivientes civiles'],'El divorcio disuelve el vínculo, a diferencia de la nulidad, y genera efectos legales propios.','Ley de Matrimonio Civil');
  add('DFA-05','Al tramitar un divorcio, ¿qué materias familiares conexas pueden requerir regulación o consideración?','Alimentos, cuidado personal, relación directa y regular, régimen patrimonial y compensación económica, según el caso',['Sólo la propiedad de vehículos','Exclusivamente materias penales','Ninguna; el divorcio está aislado de todo efecto familiar'],'La legislación busca abordar integralmente relaciones familiares pendientes cuando corresponda.','Ley de Matrimonio Civil; legislación de familia');

  // DFA-06 Filiación
  add('DFA-06','Una persona pretende obtener la determinación judicial de su vínculo filial. ¿Qué acción debe examinarse?','Una acción de reclamación de filiación, según el estado civil y supuesto concreto',['La acción reivindicatoria','La tercería de prelación','La acción de tutela laboral'],'El Código Civil regula acciones de reclamación e impugnación de filiación con legitimaciones propias.','Código Civil, filiación');
  add('DFA-06','¿Qué principio debe orientar la interpretación de los efectos de la filiación?','La igualdad de los hijos y el respeto de su identidad y derechos conforme al ordenamiento',['La creación de categorías de hijos con distinta dignidad','La preferencia automática por la filiación matrimonial en todo efecto','La disponibilidad contractual total del estado civil'],'La filiación se regula bajo igualdad y protección de identidad, con acciones legalmente determinadas.','Código Civil; Convención sobre los Derechos del Niño');
  add('DFA-06','En un juicio de filiación, una parte se niega injustificadamente a una prueba biológica ordenada conforme a la ley. ¿Qué debe hacer el tribunal?','Aplicar las consecuencias probatorias que el régimen legal atribuya a esa negativa, valorándolas en el conjunto del proceso',['Declarar automáticamente una condena penal','Considerar la negativa jurídicamente irrelevante en todo caso','Transferir el cuidado personal a la contraparte sin procedimiento'],'Las pruebas biológicas y la negativa a practicarlas poseen consecuencias reguladas específicamente.','Código Civil; Ley N° 19.968');
  add('DFA-06','¿Por qué las acciones de filiación no pueden tratarse como simples litigios patrimoniales?','Porque inciden en estado civil, identidad y relaciones familiares, sujetos a reglas de orden público y protección de derechos',['Porque nunca producen efectos patrimoniales','Porque sólo pueden resolverse por acuerdo privado','Porque carecen de prueba judicial'],'La filiación posee dimensión personal, familiar y patrimonial, con régimen especial.','Código Civil; legislación de familia');

  // DFA-07 Adopción
  add('DFA-07','¿Qué principio debe ocupar una posición central en todo procedimiento de adopción de un niño, niña o adolescente?','Su interés superior y la protección integral de sus derechos',['La conveniencia económica exclusiva de los adultos','La rapidez del procedimiento por sobre toda garantía','La preferencia automática de cualquier solicitante primero en tiempo'],'La adopción es una medida de protección y filiación orientada primordialmente a los derechos del NNA.','Legislación de adopción vigente; Convención sobre los Derechos del Niño');
  add('DFA-07','¿Puede la adopción constituirse válidamente sólo mediante un contrato privado entre adultos?','No; exige el procedimiento y decisión de autoridad competente establecidos por la legislación vigente',['Sí; basta una escritura privada','Sí; si existe transferencia de dinero','No; porque la adopción está prohibida en Chile'],'La adopción es una institución de filiación sometida a procedimiento y control judicial.','Legislación de adopción vigente');
  add('DFA-07','Antes de declarar una adopción, ¿qué debe verificarse respecto de la situación jurídica del NNA?','Los presupuestos legales de adoptabilidad o situación equivalente y el cumplimiento del procedimiento protector correspondiente',['Sólo la edad de los solicitantes','La existencia de bienes del NNA','La preferencia de vecinos del domicilio'],'La adopción requiere una situación jurídica habilitante definida por la ley y garantías del procedimiento.','Legislación de adopción vigente');
  add('DFA-07','¿Qué enfoque es incorrecto al evaluar idoneidad adoptiva?','Resolver únicamente por capacidad económica, ignorando aptitudes parentales y necesidades del NNA',['Examinar antecedentes personales y familiares relevantes','Considerar la capacidad para asumir cuidado estable','Priorizar el interés superior del NNA'],'La idoneidad no es un análisis exclusivamente patrimonial y debe centrarse en protección integral.','Legislación de adopción vigente; estándares de derechos de infancia');

  // DFA-08 Alimentos
  add('DFA-08','¿Qué dos variables estructuran la determinación de alimentos?','Las necesidades del alimentario y las facultades económicas y circunstancias del alimentante, dentro de las reglas legales',['Sólo los ingresos nominales del alimentante','Únicamente la edad del alimentario','El patrimonio del juez'],'La obligación alimenticia se determina atendiendo necesidad y capacidad, junto con parámetros legales.','Código Civil; Ley N° 14.908');
  add('DFA-08','¿Qué debe distinguirse respecto de alimentos devengados y alimentos futuros?','Su exigibilidad, modificación y eventual transacción se sujetan a reglas distintas',['Son jurídicamente idénticos para todo efecto','Los alimentos devengados nunca pueden cobrarse','Los alimentos futuros pueden renunciarse libremente en cualquier caso'],'El estatuto alimenticio protege especialmente prestaciones futuras y regula cobro de las devengadas.','Código Civil; Ley N° 14.908');
  add('DFA-08','Una pensión fijada años atrás ya no refleja las necesidades del alimentario ni capacidad del alimentante. ¿Qué institución debe examinarse?','La modificación, aumento, rebaja o cese según el cambio sustancial y requisitos legales',['La nulidad automática de la filiación','La prescripción adquisitiva','La casación penal'],'Las obligaciones de alimentos pueden variar si cambian las circunstancias jurídicamente relevantes.','Código Civil; Ley N° 14.908');
  add('DFA-08','Frente a incumplimiento reiterado de una pensión, ¿qué enfoque es correcto?','Aplicar los mecanismos de cumplimiento y apremio establecidos por la legislación alimentaria, respetando sus presupuestos',['Inventar medidas no previstas por la ley','Dar por extinguida automáticamente la deuda','Transformar la deuda en una pena criminal sin procedimiento'],'La Ley N° 14.908 y reformas vigentes contemplan herramientas específicas de cobro y cumplimiento.','Ley N° 14.908, texto vigente');

  // DFA-09 Cuidado personal
  add('DFA-09','Al resolver cuidado personal de un niño, ¿qué consideración debe ser primordial?','Su interés superior, evaluado concretamente con los criterios legales y antecedentes del caso',['La preferencia automática por uno de los padres por razón de sexo','La mayor renta como criterio único','La voluntad de terceros ajenos como regla decisiva'],'El cuidado personal se determina desde derechos y necesidades del NNA, no mediante preferencias abstractas.','Código Civil; Ley N° 21.430; Convención sobre los Derechos del Niño');
  add('DFA-09','¿Puede el tribunal establecer cuidado personal compartido simplemente porque lo considere ideal, sin atender al marco legal que regula su procedencia?','No; debe respetar los presupuestos legales de la modalidad y las posibilidades que el ordenamiento reconoce',['Sí; puede imponer cualquier modalidad sin norma','Sí; porque todo desacuerdo parental obliga a cuidado compartido','No; porque el cuidado compartido está prohibido en Chile'],'La modalidad compartida exige aplicar cuidadosamente el estatuto legal vigente y no una preferencia abstracta.','Código Civil, cuidado personal, texto vigente');
  add('DFA-09','Un acuerdo parental sobre cuidado personal perjudica gravemente al NNA. ¿Debe homologarse sólo por existir consentimiento de ambos padres?','No; el interés superior y las reglas de protección limitan la autonomía parental',['Sí; todo acuerdo parental es inmune a control','Sí; los derechos del NNA son disponibles por sus padres','No; porque ningún acuerdo sobre cuidado personal es admisible'],'La autonomía de los adultos se encuentra limitada por los derechos del NNA.','Código Civil; Ley N° 21.430');
  add('DFA-09','¿Qué relevancia tiene la opinión del NNA en una decisión de cuidado personal?','Debe ser oída y considerada conforme a su edad, madurez y derecho a participación, sin convertirla mecánicamente en la única regla de decisión',['Carece siempre de relevancia','Vincula automáticamente al tribunal cualquiera sea edad o contexto','Sólo puede oírse después de los 18 años'],'El derecho a ser oído es una garantía sustantiva y procesal de infancia.','Convención sobre los Derechos del Niño; Ley N° 21.430; Ley N° 19.968');

  // DFA-10 Relación directa y regular
  add('DFA-10','¿Cuál es la finalidad principal de un régimen de relación directa y regular?','Favorecer el vínculo del NNA con el progenitor con quien no vive, de modo compatible con su interés superior',['Satisfacer exclusivamente un derecho del adulto','Castigar al progenitor cuidador','Asegurar un número idéntico de horas en todo caso'],'La relación directa y regular se concibe desde derechos y bienestar del NNA.','Código Civil; legislación de infancia');
  add('DFA-10','Ante antecedentes serios de riesgo para un NNA durante visitas, ¿qué puede hacer el tribunal dentro del marco legal?','Regular, restringir o suspender el régimen si es necesario para proteger al NNA y se cumplen los presupuestos',['Mantenerlo sin cambios porque nunca puede limitarse','Extinguir automáticamente la filiación','Imponer una sanción penal sin procedimiento'],'El régimen puede adaptarse a la seguridad e interés superior mediante decisión fundada.','Código Civil; Ley N° 19.968');
  add('DFA-10','¿Qué debe hacer el tribunal si el NNA expresa una opinión clara sobre el régimen de relación?','Escucharla y ponderarla según edad, madurez y circunstancias junto con los demás antecedentes',['Ignorarla siempre por ser menor de edad','Aplicarla como orden absoluta sin ponderación','Delegar la decisión exclusivamente a uno de los padres'],'El derecho a ser oído exige participación efectiva, no obediencia mecánica ni exclusión.','Convención sobre los Derechos del Niño; Ley N° 21.430');
  add('DFA-10','¿Puede un conflicto económico entre progenitores justificar por sí solo impedir la relación del NNA con uno de ellos?','No; alimentos y relación directa y regular son instituciones distintas y deben resolverse según sus propios presupuestos',['Sí; toda deuda alimentaria extingue automáticamente el vínculo','Sí; el cuidado personal depende del pago puntual como única condición','No; porque los alimentos nunca pueden exigirse judicialmente'],'Las controversias deben tratarse separadamente, protegiendo el interés superior del NNA.','Código Civil; legislación de familia');

  // DPFA-01 Principios
  add('DPFA-01','¿Qué principio procesal permite al juez de familia adoptar un rol activo en la conducción del procedimiento dentro de la ley?','La oficialidad, junto con las facultades de dirección que el sistema reconoce',['La pasividad absoluta del tribunal','La autonomía contractual del juez','La reserva total de toda audiencia'],'El procedimiento de familia combina iniciativa de partes con amplias potestades de dirección judicial.','Ley N° 19.968, principios del procedimiento');
  add('DPFA-01','¿Qué exige el principio de inmediación en familia?','Que el juez tenga contacto directo con las partes y la prueba en las actuaciones decisivas conforme al procedimiento',['Que todo se resuelva sólo mediante informes escritos','Que el juez delegue siempre la recepción de prueba','Que las partes nunca comparezcan a audiencia'],'La estructura por audiencias privilegia contacto directo del juez con intervinientes y prueba.','Ley N° 19.968');
  add('DPFA-01','En una causa que afecta directamente a un NNA, ¿qué principio debe orientar transversalmente el procedimiento?','El interés superior del NNA y su derecho a participación',['La conveniencia administrativa exclusiva','La preferencia automática del adulto demandante','La reserva de toda información incluso para el propio NNA'],'El proceso de familia debe integrar estándares sustantivos y procesales de derechos de infancia.','Ley N° 19.968; Ley N° 21.430');
  add('DPFA-01','¿Qué finalidad tiene la concentración en los procedimientos de familia?','Reunir actuaciones procesales de manera eficiente en audiencias, evitando dispersión y dilaciones innecesarias',['Eliminar la posibilidad de rendir prueba','Impedir cualquier suspensión justificada','Convertir todas las causas en procedimientos escritos'],'La oralidad y concentración buscan decisiones oportunas sin sacrificar garantías.','Ley N° 19.968');

  // DPFA-02 Tribunal/Consejo Técnico
  add('DPFA-02','¿Qué función cumple el Consejo Técnico en un tribunal de familia?','Asesorar al juez en materias de su especialidad, aportando conocimiento técnico interdisciplinario',['Dictar sentencias en reemplazo del juez','Representar jurídicamente a una de las partes','Dirigir la investigación penal'],'El Consejo Técnico presta asesoría especializada sin ejercer jurisdicción.','Ley N° 19.968, organización de tribunales de familia');
  add('DPFA-02','¿Quién ejerce la función jurisdiccional dentro del Juzgado de Familia?','El juez o jueces del tribunal conforme a la competencia legal',['El Consejo Técnico por mayoría','El administrador del tribunal','Los funcionarios de atención de público'],'Las unidades administrativas apoyan el funcionamiento, pero la jurisdicción corresponde a los jueces.','Ley N° 19.968; Código Orgánico de Tribunales');
  add('DPFA-02','¿Qué criterio debe aplicarse a las unidades administrativas de un tribunal de familia?','Cumplen funciones de apoyo y gestión definidas por la ley, sin invadir potestades jurisdiccionales',['Pueden modificar sentencias por razones de gestión','Pueden resolver libremente cautelares','Sustituyen al juez cuando aumenta la carga de trabajo'],'La separación entre función jurisdiccional y gestión administrativa protege el diseño orgánico.','Ley N° 19.968; Código Orgánico de Tribunales');
  add('DPFA-02','Un informe del Consejo Técnico recomienda una medida. ¿Está el juez obligado a resolver siempre exactamente como recomienda?','No; es asesoría técnica que el juez debe ponderar junto con antecedentes y derecho aplicable, fundamentando su decisión',['Sí; el Consejo Técnico ejerce superioridad jerárquica sobre el juez','Sí; sus informes equivalen a sentencia firme','No; porque el Consejo Técnico no puede intervenir nunca en causas'],'La decisión jurisdiccional corresponde al juez, aunque la asesoría técnica pueda ser relevante.','Ley N° 19.968');

  // DPFA-03 Mediación
  add('DPFA-03','¿Qué característica es esencial de la mediación familiar?','Un tercero imparcial facilita que las propias partes busquen un acuerdo dentro de materias disponibles y límites legales',['El mediador impone una sentencia obligatoria','La mediación reemplaza toda competencia judicial','El mediador representa jurídicamente a ambas partes'],'La mediación es autocompositiva y el mediador facilita, no decide.','Ley N° 19.968, mediación familiar');
  add('DPFA-03','Antes de demandar en una materia sujeta a mediación previa obligatoria, ¿qué debe verificarse?','El cumplimiento de la instancia previa o la concurrencia de una excepción legal',['Que nunca exista mediación en familia','Sólo la voluntad del abogado demandante','La autorización del Consejo Técnico'],'La ley define materias de mediación previa y excepciones.','Ley N° 19.968, mediación');
  add('DPFA-03','¿Puede mediarse cualquier materia de familia?','No; la ley distingue materias mediables, de mediación previa y materias excluidas',['Sí; incluso el estado civil es totalmente disponible','Sí; toda medida de protección puede transarse sin control','No; porque la mediación familiar está prohibida'],'La disponibilidad y protección de derechos limitan el objeto de mediación.','Ley N° 19.968');
  add('DPFA-03','Un acuerdo de mediación aprobado judicialmente cuando la ley lo exige, ¿qué efecto puede producir?','Los efectos jurídicos que el ordenamiento reconoce a los acuerdos aprobados, incluido su exigibilidad en los términos legales',['Sólo una recomendación moral sin efectos','Una condena penal','La derogación de las normas familiares aplicables'],'La aprobación judicial puede dotar al acuerdo de fuerza jurídica según el régimen de mediación.','Ley N° 19.968');

  // DPFA-04 Reglas comunes/rol juez
  add('DPFA-04','En una audiencia de familia, una parte intenta introducir hechos sorpresivos que impiden defensa de la contraparte. ¿Qué debe resguardar el juez?','La bilateralidad, contradicción y derecho de defensa, usando sus facultades de dirección conforme a la ley',['La ventaja estratégica de quien habló primero','La prohibición absoluta de escuchar a la otra parte','La reserva de competencia del mediador'],'El rol activo judicial no elimina igualdad procesal ni derecho a contradecir.','Ley N° 19.968; debido proceso');
  add('DPFA-04','¿Qué significa que el juez de familia tenga facultades de oficio en determinadas materias?','Puede adoptar actuaciones previstas por la ley para proteger derechos y conducir el proceso, sin sustituir arbitrariamente las reglas del procedimiento',['Puede crear cualquier pretensión no discutida','Puede condenar sin oír a las partes','Puede ignorar límites de competencia'],'Las facultades oficiosas son legales y deben ejercerse respetando garantías.','Ley N° 19.968');
  add('DPFA-04','¿Por qué la oralidad no significa ausencia de registro procesal?','Porque las audiencias y resoluciones deben quedar registradas por los medios que el sistema establece',['Porque toda actuación debe repetirse íntegramente en papel','Porque el registro sólo depende de la memoria del juez','Porque las audiencias carecen de efectos jurídicos'],'La oralidad convive con sistemas de registro que permiten trazabilidad y revisión.','Ley N° 19.968; normativa de tramitación electrónica');
  add('DPFA-04','Una de las partes comparece en situación de especial vulnerabilidad. ¿Qué debe hacer el tribunal?','Aplicar las reglas procesales con enfoque de acceso efectivo a la justicia, igualdad y protección, sin perder imparcialidad',['Favorecerla automáticamente en el fondo','Negarle participación para evitar estrés','Delegar la sentencia a un organismo administrativo'],'La dirección judicial debe garantizar participación efectiva e igualdad procesal.','Ley N° 19.968; estándares de acceso a justicia');

  // DPFA-05 Ordinario
  add('DPFA-05','¿Qué función cumple la audiencia preparatoria en el procedimiento ordinario de familia?','Delimitar el conflicto, resolver cuestiones previas, promover acuerdos y preparar la prueba para el juicio',['Dictar necesariamente sentencia definitiva sin prueba','Reemplazar la demanda por una investigación penal','Ejecutar alimentos adeudados como única finalidad'],'La audiencia preparatoria ordena la controversia y prepara el juicio.','Ley N° 19.968, procedimiento ordinario');
  add('DPFA-05','¿Qué función cumple la audiencia de juicio?','Recibir la prueba admitida, oír alegaciones pertinentes y permitir al tribunal adoptar la decisión conforme al procedimiento',['Iniciar obligatoriamente mediación previa','Fijar sólo el domicilio de las partes','Resolver exclusivamente incidencias administrativas'],'La audiencia de juicio concentra la actividad probatoria y decisoria.','Ley N° 19.968');
  add('DPFA-05','Una demanda de familia carece de antecedentes indispensables para comprender la pretensión. ¿Qué debe hacer el tribunal?','Aplicar las reglas de admisibilidad y subsanación que correspondan antes de avanzar, resguardando acceso a justicia y defensa',['Dictar sentencia favorable de inmediato','Rechazar siempre y sin posibilidad de corrección','Enviar automáticamente el asunto a sede penal'],'El procedimiento contempla control inicial y herramientas para ordenar correctamente la controversia.','Ley N° 19.968');
  add('DPFA-05','¿Puede el juez omitir toda oportunidad de prueba porque considera evidente el caso desde la audiencia preparatoria?','No, salvo que jurídicamente no existan hechos controvertidos o concurra una hipótesis legal que permita decidir; debe respetarse el derecho a prueba',['Sí; la convicción inicial del juez reemplaza la prueba','Sí; en familia nunca existe derecho a rendir prueba','No; porque toda causa exige idéntica prueba aunque los hechos sean pacíficos'],'La dirección activa no autoriza prejuzgar ni suprimir indebidamente actividad probatoria.','Ley N° 19.968; debido proceso');

  // DPFA-06 VIF/protección/contravencional
  add('DPFA-06','En una causa de protección, existen antecedentes de riesgo grave e inmediato para un NNA. ¿Qué puede hacer el tribunal?','Adoptar medidas cautelares o de protección legalmente previstas, proporcionales al riesgo y sujetas a revisión',['Esperar siempre sentencia definitiva antes de proteger','Separar permanentemente al NNA sin audiencia ni control en todo caso','Delegar toda decisión a un particular'],'La protección urgente permite medidas provisionales, pero exige base legal, proporcionalidad y control.','Ley N° 19.968; Ley N° 21.430');
  add('DPFA-06','¿Cuál es el foco de un procedimiento de protección de derechos de NNA?','Restituir y proteger derechos amenazados o vulnerados, atendiendo al interés superior y a la intervención necesaria y proporcional',['Sancionar civilmente a cualquier adulto como fin principal','Resolver exclusivamente disputas patrimoniales','Privar de cuidado personal como respuesta automática'],'La finalidad protectora debe distinguirse de una lógica punitiva.','Ley N° 19.968; Ley N° 21.430');
  add('DPFA-06','Ante una denuncia de violencia intrafamiliar con riesgo actual, ¿qué enfoque procesal corresponde?','Evaluar el riesgo y adoptar oportunamente las medidas cautelares que la ley autoriza, asegurando audiencia y control posterior cuando corresponda',['Exigir sentencia penal firme antes de cualquier medida','Rechazar toda medida por ser provisoria','Transformar automáticamente el conflicto en divorcio'],'La legislación de VIF y familia contempla protección cautelar urgente.','Ley N° 20.066; Ley N° 19.968');
  add('DPFA-06','En procedimiento contravencional respecto de adolescentes o NNA, ¿qué debe evitarse?','Aplicar mecánicamente una lógica penal adulta sin atender al estatuto especial, garantías y finalidad protectora o educativa pertinente',['Respetar derecho a ser oído','Aplicar garantías del procedimiento','Considerar edad y madurez'],'El sistema especial exige respuestas adecuadas a edad y estatuto jurídico aplicable.','Ley N° 19.968; legislación especial de infancia');

  // DPFA-07 Prueba
  add('DPFA-07','¿Cómo se valora la prueba en los procedimientos de familia?','Conforme a las reglas de sana crítica y con fundamentación de la decisión',['Mediante tarifa legal rígida para toda prueba','Según la intuición del juez sin explicación','Por mayoría de votos de los testigos'],'La Ley N° 19.968 adopta sana crítica y exige expresar razones de valoración.','Ley N° 19.968, prueba');
  add('DPFA-07','Un informe pericial contradice otros antecedentes relevantes. ¿Debe el juez aceptarlo automáticamente por provenir de un experto?','No; debe valorarlo racionalmente junto con el resto de la prueba conforme a sana crítica',['Sí; todo peritaje vincula al tribunal','No; porque los peritajes nunca son admisibles en familia','Sí; salvo que una parte no esté de acuerdo'],'La pericia aporta conocimiento especializado, pero su mérito debe ser fundamentadamente valorado.','Ley N° 19.968');
  add('DPFA-07','¿Qué relevancia tiene el derecho del NNA a ser oído en la actividad probatoria?','Su participación debe organizarse de manera adecuada a edad y madurez, evitando convertirlo indebidamente en objeto de prueba o exposición dañina',['Obliga a interrogarlo siempre como testigo adulto','Autoriza ignorar su opinión si hay informes técnicos','Permite delegar en él la decisión jurídica final'],'La participación del NNA debe ser efectiva y compatible con protección contra revictimización.','Ley N° 21.430; Ley N° 19.968');
  add('DPFA-07','¿Puede el tribunal basar su decisión en un antecedente decisivo que ninguna parte pudo conocer ni controvertir?','Debe respetar contradicción y debido proceso; si el antecedente influye decisivamente, su incorporación debe permitir control conforme a la ley',['Sí; toda información reservada puede fundar la sentencia sin límites','Sí; la sana crítica elimina la bilateralidad','No; porque el tribunal sólo puede usar confesión de las partes'],'La valoración libre dentro de sana crítica no elimina garantías de contradicción.','Ley N° 19.968; debido proceso');

  // DPFA-08 Recursos
  add('DPFA-08','Antes de apelar una resolución de familia, ¿qué debe determinarse?','Si la resolución es apelable, el plazo, forma y efectos que la Ley N° 19.968 y normas supletorias establecen',['Que toda resolución sea apelable por regla absoluta','Sólo si la parte perdió completamente','Que el Consejo Técnico autorice el recurso'],'El régimen de recursos de familia tiene reglas propias y supletoriedad específica.','Ley N° 19.968, recursos');
  add('DPFA-08','¿Por qué no basta aplicar automáticamente las reglas del Código de Procedimiento Civil a cualquier recurso de familia?','Porque la Ley N° 19.968 contiene régimen especial y define la supletoriedad compatible',['Porque el CPC está derogado','Porque en familia no existen recursos','Porque sólo se aplican normas penales'],'La especialidad procesal condiciona la aplicación supletoria del CPC.','Ley N° 19.968');
  add('DPFA-08','Una sentencia de familia presenta un vicio grave de fundamentación. ¿Qué debe hacer la parte antes de escoger el recurso?','Identificar la naturaleza del vicio y la causal y recurso que el régimen especial hace procedentes',['Interponer simultáneamente todos los recursos existentes sin fundamento','Solicitar al Consejo Técnico que anule la sentencia','Presentar una denuncia administrativa como sustituto obligatorio'],'Los recursos son mecanismos reglados y requieren correlación entre resolución, vicio y causal.','Ley N° 19.968; normas procesales supletorias');
  add('DPFA-08','¿Puede el recurso utilizarse para introducir libremente una controversia fáctica completamente nueva que nunca fue sometida al tribunal inferior?','En principio no; la revisión se desarrolla dentro del marco procesal y de las competencias que abre el recurso, salvo reglas especiales',['Sí; la segunda instancia siempre reinicia todo desde cero','Sí; cualquier hecho nuevo debe admitirse sin límite','No; porque los recursos sólo discuten competencia orgánica'],'La congruencia y el diseño recursivo limitan el objeto de revisión.','Ley N° 19.968; principios procesales');

  return out;
})();
