/* Banco PF93 — área común. Borrador para revisión humana.
 * Cada ítem se vincula al blueprint oficial. Las fuentes NO se marcan verificadas.
 */
const PF93_DRAFT_COMMON = (() => {
  const out = []; const seq = {};
  function add(tema, pregunta, correcta, distractores, explicacion, fuente) {
    seq[tema] = (seq[tema] || 0) + 1;
    const pos = (out.length + seq[tema]) % 4;
    const opciones = distractores.slice(0,3); opciones.splice(pos,0,correcta);
    out.push({id:`pf93-${tema.toLowerCase()}-${String(seq[tema]).padStart(2,'0')}`,temaPF93:tema,pregunta,opciones:opciones.map((text,i)=>({id:'ABCD'[i],text})),respuesta:pos,explicacion,fuente:{cita:fuente,verificada:false,revisadaEn:null},estado:'revision_humana',dificultad:'media',tipo:'alternativa'});
  }

  // DCO-01 Bases de la institucionalidad
  add('DCO-01','Una autoridad adopta una decisión que trata a una persona como un mero instrumento para alcanzar una meta administrativa. ¿Qué principio constitucional resulta directamente comprometido?','La primacía de la persona y su dignidad como límite de la actuación estatal',['La autonomía reglamentaria absoluta de la autoridad','La supremacía presupuestaria sobre los derechos','La subordinación de toda garantía a la eficiencia administrativa'],'Las bases de la institucionalidad sitúan a la persona y su dignidad como referencia de la actuación estatal.','Constitución Política de la República, Capítulo I');
  add('DCO-01','¿Cuál afirmación describe mejor la relación entre Estado y persona en las bases de la institucionalidad?','El Estado está al servicio de la persona y debe promover el bien común',['La persona existe al servicio de los fines del Estado','El bien común autoriza a prescindir de derechos fundamentales','El Estado sólo debe abstenerse y carece de deberes de promoción'],'La Constitución formula un deber estatal orientado al bien común respetando derechos y garantías.','Constitución Política de la República, art. 1');
  add('DCO-01','Una ley atribuye a un órgano público potestades sin sujeción a la Constitución. ¿Qué regla básica impide entender válida esa atribución?','La sujeción de los órganos del Estado a la Constitución y a las normas dictadas conforme a ella',['La autonomía contractual de los órganos públicos','La costumbre administrativa contra legem','La prevalencia de instrucciones internas sobre la Constitución'],'La juridicidad constitucional obliga a todos los órganos estatales.','Constitución Política de la República, arts. 6 y 7');
  add('DCO-01','¿Cuál de estas proposiciones es compatible con las bases constitucionales chilenas?','El ejercicio de la soberanía reconoce límites derivados del respeto a los derechos esenciales',['La soberanía permite suspender permanentemente todo derecho por decisión administrativa','Los derechos esenciales sólo obligan a los tribunales','Los tratados de derechos humanos carecen de toda relevancia para el ejercicio de la soberanía'],'El ejercicio de la soberanía reconoce como límite el respeto a derechos esenciales y los deberes estatales establecidos constitucionalmente.','Constitución Política de la República, art. 5');

  // DCO-02 Funciones estatales
  add('DCO-02','El Congreso aprueba una norma general y abstracta siguiendo el procedimiento constitucional. ¿Qué función estatal ejerce principalmente?','La función legislativa',['La función jurisdiccional','La función contralora','La función administrativa de ejecución'],'La creación de leyes mediante el procedimiento constitucional corresponde a la función legislativa.','Constitución Política de la República, capítulos IV y V');
  add('DCO-02','Un tribunal resuelve con autoridad un conflicto jurídico sometido a su conocimiento. ¿Qué función desarrolla?','La función jurisdiccional',['La potestad reglamentaria autónoma','La función de control financiero externo','La función administrativa de gestión'],'La jurisdicción consiste en conocer y resolver asuntos sometidos a los tribunales y hacer ejecutar lo juzgado.','Constitución Política de la República, art. 76');
  add('DCO-02','La Contraloría examina la juridicidad de un acto de la Administración dentro de sus atribuciones. ¿Qué función se manifiesta principalmente?','Una función de control o contralora',['Una función jurisdiccional ordinaria','Una función legislativa delegada','Una potestad constituyente derivada'],'El control de juridicidad administrativa es una manifestación característica de la función contralora.','Constitución Política de la República, Capítulo X');
  add('DCO-02','Un ministerio ejecuta una política pública mediante actos dictados dentro de sus competencias. ¿Qué función estatal predomina?','La función administrativa',['La función jurisdiccional','La función constituyente','La función legislativa propiamente tal'],'La ejecución concreta y continua de fines públicos por órganos administrativos corresponde primariamente a la función administrativa.','Constitución Política de la República; Ley N° 18.575');

  // DCO-03 Forma de gobierno y Estado
  add('DCO-03','¿Cuál afirmación caracteriza correctamente la forma de Estado chilena conforme a la Constitución vigente?','Chile es un Estado unitario cuya administración puede ser funcional y territorialmente descentralizada o desconcentrada',['Chile es un Estado federal compuesto por entidades soberanas','Chile es una confederación de regiones autónomas','La descentralización transforma a cada región en un Estado federado'],'La Constitución define a Chile como Estado unitario y admite descentralización o desconcentración administrativa.','Constitución Política de la República, art. 3');
  add('DCO-03','¿Qué rasgo corresponde a la forma de gobierno establecida constitucionalmente en Chile?','Un gobierno republicano y democrático',['Una monarquía constitucional hereditaria','Un sistema confederal de gobiernos soberanos','Un directorio administrativo sin legitimidad electoral'],'La Constitución caracteriza a Chile como república democrática.','Constitución Política de la República, art. 4');
  add('DCO-03','La creación de una municipalidad con personalidad jurídica y patrimonio propio ¿es incompatible, por sí sola, con el carácter unitario del Estado?','No; la descentralización administrativa es compatible con un Estado unitario',['Sí; toda personalidad jurídica territorial supone federalismo','Sí; un Estado unitario sólo admite órganos centrales','No; porque las municipalidades ejercen soberanía propia'],'Unidad estatal y descentralización administrativa son categorías compatibles.','Constitución Política de la República, arts. 3 y 118 y siguientes');
  add('DCO-03','¿Cuál afirmación diferencia correctamente descentralización de desconcentración administrativa?','La descentralización supone radicar competencias en entidades distintas del Fisco; la desconcentración distribuye competencias dentro de una misma persona jurídica',['Ambas expresiones designan necesariamente autonomía política soberana','La desconcentración crea siempre una nueva persona jurídica','La descentralización sólo puede existir mediante reforma constitucional'],'La distinción se vincula a la personalidad jurídica y a la distribución de competencias administrativas.','Constitución Política de la República, art. 3; Ley N° 18.575');

  // DCO-04 Ejecutivo y potestad reglamentaria
  add('DCO-04','El Presidente dicta un reglamento para ejecutar una ley sin alterar su contenido. ¿Qué potestad ejerce principalmente?','La potestad reglamentaria de ejecución',['La potestad jurisdiccional','La potestad constituyente originaria','La potestad contralora'],'La potestad reglamentaria de ejecución permite desarrollar la ley para su aplicación, dentro de sus límites.','Constitución Política de la República, art. 32');
  add('DCO-04','¿Qué límite general rige la potestad reglamentaria presidencial?','Debe ejercerse dentro de la Constitución y respetando las materias reservadas a la ley',['Puede contradecir una ley si existe urgencia administrativa','Puede crear delitos y penas por decreto sin habilitación legal','Prevalece siempre sobre las leyes anteriores'],'La potestad reglamentaria está subordinada a la Constitución y al sistema de reserva legal.','Constitución Política de la República, arts. 32 y 63');
  add('DCO-04','Una materia está entregada constitucionalmente a la ley. ¿Puede regularse íntegramente por un reglamento autónomo presidencial?','No, la potestad autónoma no puede invadir materias reservadas a la ley',['Sí, siempre que el reglamento sea posterior','Sí, si lo solicita un ministerio','Sí, porque todo reglamento tiene rango legal'],'La potestad reglamentaria autónoma opera fuera de las materias comprendidas en el dominio legal y no desplaza la reserva de ley.','Constitución Política de la República, arts. 32 y 63');
  add('DCO-04','¿Cuál enunciado describe adecuadamente al Presidente en el proceso legislativo?','Participa como colegislador mediante atribuciones constitucionales como iniciativa, observaciones y promulgación',['Carece de intervención en la formación de la ley','Puede reemplazar al Congreso por reglamentos en toda materia','Sólo interviene después de que la ley entra en vigencia'],'El Presidente participa constitucionalmente en diversas etapas de formación de la ley.','Constitución Política de la República, Capítulo V');

  // DCO-05 Bases Administración
  add('DCO-05','Un servicio duplica trámites sin justificación y omite coordinarse con otro órgano competente, generando decisiones contradictorias. ¿Qué principios administrativos resultan especialmente relevantes?','Eficiencia, eficacia y coordinación',['Irresponsabilidad y secreto','Autotutela jurisdiccional y cosa juzgada','Independencia judicial e inamovilidad'],'La Administración debe actuar coordinadamente y orientar su actividad al cumplimiento eficiente y eficaz de sus fines.','Ley N° 18.575, bases generales de la Administración del Estado');
  add('DCO-05','¿Cuál afirmación refleja el principio de probidad administrativa?','El ejercicio de la función pública exige conducta funcionaria intachable y desempeño honesto y leal, con preeminencia del interés general',['Autoriza privilegiar intereses privados si no existe perjuicio fiscal','Se limita exclusivamente al manejo contable de fondos','Permite omitir conflictos de interés cuando la decisión sea eficiente'],'La probidad impone un estándar de conducta y primacía del interés general.','Constitución Política de la República, art. 8; Ley N° 18.575');
  add('DCO-05','¿Qué consecuencia general se sigue del principio de responsabilidad de los órganos estatales?','La actuación contraria al ordenamiento puede generar responsabilidades en los términos que determine la ley',['Los órganos públicos están exentos de toda responsabilidad','Sólo existe responsabilidad si hay enriquecimiento personal','La responsabilidad puede excluirse mediante instrucciones internas'],'La juridicidad se complementa con responsabilidad por infracciones conforme al régimen aplicable.','Constitución Política de la República, arts. 6 y 7; Ley N° 18.575');
  add('DCO-05','En materia de publicidad administrativa, ¿cuál es la regla constitucional de partida?','Son públicos los actos y resoluciones de los órganos del Estado, sus fundamentos y procedimientos, salvo excepciones establecidas conforme a la Constitución',['Todo antecedente administrativo es secreto por defecto','La publicidad depende exclusivamente de la voluntad del jefe de servicio','Sólo son públicos los actos dictados por tribunales'],'La Constitución establece publicidad como regla y admite reserva o secreto bajo presupuestos constitucionales.','Constitución Política de la República, art. 8');

  // DCO-06 Poder Judicial
  add('DCO-06','El legislador ordena a un tribunal cómo debe resolver un litigio pendiente. ¿Qué principio constitucional se compromete de manera directa?','La independencia judicial',['La voluntariedad de la jurisdicción','La autonomía de la voluntad','La publicidad registral'],'La función jurisdiccional corresponde exclusivamente a los tribunales establecidos por ley y no puede ser interferida en un caso concreto.','Constitución Política de la República, art. 76');
  add('DCO-06','Un tribunal competente se niega a decidir porque la ley no regula expresamente un detalle del caso. ¿Qué principio impide esa negativa?','La inexcusabilidad',['La delegabilidad general de la jurisdicción','La reserva reglamentaria','La autotutela administrativa'],'Reclamada legalmente su intervención en asuntos de su competencia, los tribunales no pueden excusarse de ejercerla ni aun por falta de ley.','Constitución Política de la República, art. 76');
  add('DCO-06','¿Qué busca proteger la inamovilidad judicial?','La independencia del juez frente a remociones ajenas a las causales y procedimientos constitucionales o legales',['La inmunidad frente a toda responsabilidad','El derecho a escoger libremente cualquier competencia','La facultad de delegar la jurisdicción'],'La inamovilidad es una garantía institucional vinculada a la independencia judicial y no elimina los regímenes de responsabilidad.','Constitución Política de la República, estatuto del Poder Judicial');
  add('DCO-06','¿Qué tribunal ejerce, en los términos constitucionales, la superintendencia directiva, correccional y económica sobre los tribunales de la Nación, con las excepciones previstas?','La Corte Suprema',['El Tribunal Constitucional','La Contraloría General de la República','El Ministerio de Justicia'],'La Constitución atribuye esa superintendencia a la Corte Suprema, salvo las exclusiones constitucionales.','Constitución Política de la República, art. 82');

  // DCO-07 Tribunal Constitucional
  add('DCO-07','Durante la tramitación de una gestión judicial se sostiene que aplicar un precepto legal determinado produciría un resultado contrario a la Constitución. ¿Qué mecanismo constitucional es pertinente, si concurren sus requisitos?','El requerimiento de inaplicabilidad por inconstitucionalidad ante el Tribunal Constitucional',['El recurso de casación en el fondo ante la Contraloría','La invalidación administrativa del precepto legal','La acusación constitucional contra el juez'],'La inaplicabilidad permite al Tribunal Constitucional pronunciarse sobre la aplicación de un precepto legal en una gestión pendiente.','Constitución Política de la República, art. 93');
  add('DCO-07','¿Qué efecto caracteriza a una sentencia de inaplicabilidad respecto del precepto cuestionado?','Impide su aplicación en la gestión judicial concreta en los términos decididos, sin derogarlo por ese solo hecho',['Deroga automáticamente el precepto para todos los casos','Transforma el precepto en reglamento','Anula todas las sentencias anteriores dictadas con esa norma'],'La inaplicabilidad es un control concreto y no equivale por sí sola a expulsión general de la norma del ordenamiento.','Constitución Política de la República, art. 93');
  add('DCO-07','¿Cuál afirmación distingue el control preventivo de constitucionalidad de la inaplicabilidad?','El control preventivo opera antes de la entrada en vigencia del precepto sometido a control; la inaplicabilidad se vincula a una gestión judicial pendiente',['Ambos mecanismos requieren siempre sentencia ejecutoriada previa','La inaplicabilidad sólo puede ejercerse antes de promulgar la ley','El control preventivo corresponde exclusivamente a tribunales ordinarios'],'La oportunidad y objeto de ambos controles son diferentes.','Constitución Política de la República, art. 93');
  add('DCO-07','¿Puede un tribunal ordinario declarar por sí mismo, con efectos generales, la inconstitucionalidad y expulsión de una ley vigente?','No; el sistema constitucional distribuye el control y reserva al Tribunal Constitucional las atribuciones que la Constitución le confiere',['Sí, todo juez puede derogar leyes por sentencia','Sí, siempre que exista acuerdo de las partes','No, porque ninguna ley puede ser controlada una vez vigente'],'Los jueces interpretan y aplican el derecho, pero la expulsión general de normas por inconstitucionalidad se rige por mecanismos constitucionales específicos.','Constitución Política de la República, arts. 76 y 93');

  // DCO-08 Derechos fundamentales
  add('DCO-08','Una diferencia de trato legal carece de fundamento razonable y establece una distinción arbitraria entre personas en igual situación. ¿Qué garantía se encuentra directamente comprometida?','La igualdad ante la ley y la prohibición de diferencias arbitrarias',['El derecho real de dominio inscrito','La potestad reglamentaria autónoma','La superintendencia económica'],'La igualdad constitucional no impide toda diferenciación, pero sí las distinciones arbitrarias.','Constitución Política de la República, art. 19 N° 2');
  add('DCO-08','¿Qué exige, en términos generales, la garantía del debido proceso respecto de una decisión jurisdiccional?','Un procedimiento y una investigación racionales y justos, dentro de las garantías constitucionales',['Que toda decisión sea adoptada administrativamente','Que se eliminen las posibilidades de defensa para acelerar el proceso','Que el juez pueda modificar libremente la competencia legal'],'La Constitución exige garantías de racionalidad y justicia procedimental y reserva a la ley la determinación de tribunales y procedimientos.','Constitución Política de la República, art. 19 N° 3');
  add('DCO-08','Una autoridad registra y difunde comunicaciones privadas sin habilitación legal ni autorización competente. ¿Qué esfera constitucional resulta primariamente afectada?','La vida privada y la inviolabilidad de las comunicaciones privadas',['La libertad de enseñanza','La libertad de adquirir bienes','El derecho a sindicalización'],'La Constitución protege la vida privada y las comunicaciones frente a injerencias que no satisfagan los presupuestos jurídicos aplicables.','Constitución Política de la República, art. 19');
  add('DCO-08','Ante una colisión entre dos derechos fundamentales, ¿qué enfoque es jurídicamente más adecuado?','Identificar el ámbito protegido de cada derecho y justificar una solución que respete sus límites constitucionales y legales',['Declarar siempre absoluto el derecho invocado primero','Aplicar automáticamente el derecho con mayor antigüedad histórica','Prescindir de los hechos concretos y resolver sólo por jerarquía nominal'],'Los conflictos de derechos requieren identificar ámbitos de protección, límites y justificación de la solución en el caso concreto.','Constitución Política de la República, art. 19; doctrina constitucional');

  // DCO-09 Amparo y protección
  add('DCO-09','Una persona es privada de libertad por una orden manifiestamente ilegal. ¿Qué acción constitucional está específicamente diseñada para tutelar su libertad personal y seguridad individual?','La acción de amparo',['La acción reivindicatoria','El recurso de casación en la forma','La reclamación tributaria'],'El amparo protege la libertad personal y seguridad individual frente a privaciones, perturbaciones o amenazas ilegales en los términos constitucionales.','Constitución Política de la República, art. 21');
  add('DCO-09','Un acto arbitrario de una autoridad amenaza una garantía comprendida en el ámbito del artículo 20 de la Constitución. ¿Qué acción resulta, en principio, pertinente?','La acción de protección',['La querella posesoria en todo caso','La nulidad procesal penal','La acción popular de inconstitucionalidad'],'La protección tutela las garantías enumeradas constitucionalmente frente a actos u omisiones ilegales o arbitrarios.','Constitución Política de la República, art. 20');
  add('DCO-09','¿Cuál afirmación distingue adecuadamente protección y amparo?','La protección tutela las garantías constitucionales señaladas en el artículo 20; el amparo se centra en libertad personal y seguridad individual',['Ambas acciones tienen exactamente el mismo objeto','El amparo sólo protege derechos patrimoniales','La protección sólo procede contra sentencias penales condenatorias'],'Las acciones tienen ámbitos materiales distintos aunque ambas constituyen tutelas constitucionales urgentes.','Constitución Política de la República, arts. 20 y 21');
  add('DCO-09','Al analizar la procedencia de una acción de protección, ¿qué metodología es más correcta?','Identificar el acto u omisión, su ilegalidad o arbitrariedad, la garantía protegida y la afectación concreta',['Presumir que toda ilegalidad administrativa vulnera necesariamente todas las garantías','Exigir siempre una sentencia previa de otro tribunal','Rechazarla automáticamente si existe cualquier otra vía jurídica posible'],'La procedencia requiere conectar conducta, reproche jurídico y garantía afectada; la existencia de otras vías no se transforma sin más en una regla absoluta de improcedencia.','Constitución Política de la República, art. 20; Auto Acordado sobre tramitación del recurso de protección');

  // DAD-01 Legalidad y juridicidad
  add('DAD-01','Un jefe de servicio ordena una actuación que ninguna norma entrega al órgano, argumentando que es útil para el interés público. ¿Qué principio impide fundar la competencia sólo en esa utilidad?','El principio de juridicidad: los órganos actúan previa investidura regular, dentro de su competencia y en la forma prescrita por la ley',['La autonomía de la voluntad administrativa','La regla de competencia universal del Fisco','La costumbre como fuente ilimitada de potestades públicas'],'La finalidad pública no sustituye la habilitación jurídica necesaria para ejercer potestades.','Constitución Política de la República, arts. 6 y 7');
  add('DAD-01','¿Cuál afirmación describe mejor una potestad administrativa?','Es una atribución conferida por el ordenamiento para perseguir fines públicos dentro de límites y condiciones jurídicas',['Es una facultad privada que el órgano puede ampliar por contrato','Es una competencia ilimitada derivada de la personalidad jurídica del Estado','Es una recomendación sin consecuencias jurídicas aunque la ley la establezca'],'Las potestades públicas se fundan en el ordenamiento y están funcionalizadas a fines públicos.','Constitución Política de la República; Ley N° 18.575');
  add('DAD-01','Si una autoridad ejerce una competencia legal para un fin distinto del previsto por el ordenamiento, ¿qué problema jurídico puede configurarse?','Un vicio en el ejercicio de la potestad por apartarse de su finalidad jurídica',['Una ampliación tácita de competencia','Una derogación administrativa de la ley','Una inmunidad por actuar formalmente dentro del órgano'],'La habilitación competencial no autoriza utilizar la potestad para fines ajenos a aquellos que justifican su otorgamiento.','Ley N° 18.575; principios de derecho administrativo');
  add('DAD-01','¿Qué diferencia básica existe entre un particular y un órgano público frente al principio de legalidad?','El órgano público requiere habilitación jurídica para ejercer potestades; el particular se mueve, en general, dentro del ámbito de libertad que el derecho no prohíbe',['Ambos sólo pueden realizar actos expresamente enumerados por ley','El órgano público posee libertad general y el particular competencia tasada','No existe diferencia relevante entre potestad pública y autonomía privada'],'La competencia pública es atribuida por el ordenamiento y no nace de una libertad general de actuación.','Constitución Política de la República, arts. 6 y 7');

  // DAD-02 Acto administrativo
  add('DAD-02','¿Cuál descripción se aproxima al concepto legal de acto administrativo en la Ley N° 19.880?','Una decisión formal emitida por un órgano de la Administración en ejercicio de una potestad pública y que contiene una declaración de voluntad, juicio, constancia o conocimiento en los términos legales',['Todo hecho material realizado por un funcionario, aun sin decisión alguna','Cualquier contrato privado celebrado entre particulares','Exclusivamente las sentencias de los tribunales de justicia'],'La Ley N° 19.880 contiene un concepto funcional de acto administrativo y reconoce distintas formas de declaración.','Ley N° 19.880, art. 3');
  add('DAD-02','Una resolución administrativa ha sido dictada y comunicada conforme al régimen aplicable. ¿Qué regla general debe considerarse al analizar sus efectos?','Los actos administrativos gozan de presunción de legalidad, imperio y exigibilidad desde su entrada en vigencia, sin perjuicio de su impugnación',['Carecen siempre de efectos hasta una sentencia judicial que los confirme','Son irrevocables aunque sean ilegales','Sólo obligan si el destinatario los acepta expresamente'],'La Ley N° 19.880 reconoce presunción de legalidad, imperio y exigibilidad, sin eliminar mecanismos de revisión.','Ley N° 19.880, art. 3');
  add('DAD-02','Una resolución afecta derechos de una persona y la ley exige notificación. ¿Puede la Administración tratarla como plenamente oponible al destinatario antes de cumplir esa comunicación?','Debe atenderse al régimen de eficacia y notificación; la sola firma no reemplaza los requisitos de comunicación exigidos',['Sí, toda resolución produce efectos frente a terceros desde que se redacta','Sí, porque la notificación es siempre voluntaria','No, porque ningún acto administrativo puede producir efectos antes de un año'],'La eficacia frente al interesado debe analizarse conforme a las reglas de notificación y entrada en vigencia aplicables.','Ley N° 19.880, reglas sobre eficacia y notificación');
  add('DAD-02','¿Qué criterio debe aplicarse al interpretar la presunción de legalidad del acto administrativo?','Es una presunción que permite su eficacia y ejecución, pero no impide su revisión administrativa o jurisdiccional conforme al ordenamiento',['Convierte todo acto en jurídicamente inatacable','Impide a la propia Administración corregir actos ilegales','Equivale a una sentencia judicial con cosa juzgada material absoluta'],'La presunción facilita eficacia administrativa, pero coexiste con recursos, invalidación y control judicial.','Ley N° 19.880; principios de control administrativo');

  // DAD-03 Procedimiento administrativo
  add('DAD-03','Una persona solicita ser oída antes de una decisión administrativa que puede afectarla. ¿Qué principio del procedimiento respalda especialmente esa participación?','El principio contradictorio y el derecho de los interesados a formular alegaciones y aportar antecedentes',['La reserva absoluta del expediente','La prohibición de intervención de interesados','La irrevisabilidad de los antecedentes'],'El procedimiento administrativo contempla participación y contradicción de los interesados en los términos legales.','Ley N° 19.880');
  add('DAD-03','¿Qué regla general busca evitar que formalidades no esenciales impidan resolver el fondo de una solicitud administrativa?','El principio de no formalización, sin perjuicio de las exigencias esenciales establecidas por el ordenamiento',['La nulidad automática por cualquier defecto de forma','La prohibición de subsanar presentaciones','La exigencia de escritura pública para toda actuación'],'La Ley N° 19.880 procura un procedimiento sencillo y eficaz, sin sacrificar requisitos esenciales.','Ley N° 19.880, principios del procedimiento');
  add('DAD-03','Un órgano mantiene un procedimiento indefinidamente sin actividad ni decisión. ¿Qué deber general resulta relevante?','El deber de impulsar y concluir el procedimiento dentro de los plazos y conforme a los principios de celeridad y conclusividad',['La facultad de suspender todo procedimiento sin fundamento','El derecho del órgano a no resolver solicitudes','La regla de duración indefinida por defecto'],'La Administración debe conducir el procedimiento a una decisión, respetando los principios y plazos aplicables.','Ley N° 19.880');
  add('DAD-03','¿Qué función cumple la motivación de una decisión administrativa que afecta derechos?','Permite conocer las razones de hecho y de derecho que sustentan la decisión y facilita su control',['Sustituye la competencia del órgano','Evita toda posibilidad de impugnación','Autoriza a omitir los antecedentes del expediente'],'La fundamentación hace controlable la decisión y es especialmente relevante cuando se afectan derechos o intereses.','Ley N° 19.880, reglas sobre motivación');

  // DAD-04 Control y revisión
  add('DAD-04','Una persona impugna un acto ante el mismo órgano que lo dictó para que lo reconsidere. ¿Qué mecanismo administrativo describe, en términos generales?','Un recurso de reposición',['Una acción de amparo','Una casación en el fondo','Una contienda de competencia'],'La reposición se dirige al mismo órgano que dictó el acto, según el régimen previsto en la Ley N° 19.880 y leyes especiales.','Ley N° 19.880, recursos administrativos');
  add('DAD-04','¿Qué finalidad común tienen los mecanismos de revisión administrativa?','Permitir que la propia Administración examine la juridicidad o mérito de sus decisiones dentro de las potestades que la ley reconoce',['Eliminar todo control judicial posterior','Convertir cualquier instrucción interna en ley','Impedir que los interesados formulen alegaciones'],'La revisión administrativa coexiste con controles jurisdiccionales y se ejerce dentro de competencias legales.','Ley N° 19.880');
  add('DAD-04','La Administración advierte que uno de sus actos es contrario a derecho y considera dejarlo sin efecto por esa razón. ¿Qué institución debe distinguir de la mera revocación por razones de mérito?','La invalidación',['La conciliación judicial','La novación civil','La prescripción adquisitiva'],'Invalidación y revocación responden a fundamentos distintos y tienen presupuestos propios.','Ley N° 19.880, arts. 53 y 61');
  add('DAD-04','¿Cuál afirmación sobre control administrativo y judicial es más adecuada?','Pueden coexistir según el diseño legal; los recursos administrativos no transforman a la Administración en tribunal ni excluyen por regla general todo control jurisdiccional',['Todo recurso administrativo elimina definitivamente la competencia judicial','Sólo los tribunales pueden corregir cualquier acto administrativo, incluso cuando la ley confiere potestad de invalidación','Una reclamación judicial convierte automáticamente el acto en inexistente'],'El sistema combina autocontrol administrativo y control jurisdiccional de acuerdo con las normas aplicables.','Ley N° 19.880 y legislación especial');

  // DAD-05 Nulidad de derecho público
  add('DAD-05','Un órgano actúa fuera de la competencia que la Constitución y la ley le han conferido. ¿Qué fundamento constitucional es central para analizar la validez de esa actuación?','Las reglas de juridicidad y competencia de los artículos 6 y 7 de la Constitución',['La autonomía privada del funcionario','La libertad contractual del órgano','La presunción de que toda actuación incompetente se transforma en ley'],'La nulidad de derecho público se conecta doctrinal y jurisprudencialmente con la infracción a requisitos constitucionales de actuación estatal.','Constitución Política de la República, arts. 6 y 7');
  add('DAD-05','¿Por qué no es correcto afirmar que cualquier irregularidad formal produce necesariamente la misma consecuencia invalidante?','Porque deben examinarse la norma infringida, la entidad del vicio, sus efectos y el régimen jurídico aplicable',['Porque los actos administrativos nunca pueden ser inválidos','Porque todo defecto se sanea automáticamente al día siguiente','Porque sólo importa si existe perjuicio patrimonial del Estado'],'La invalidez administrativa exige un análisis jurídico del vicio y del régimen aplicable, no una fórmula automática para toda irregularidad.','Constitución Política de la República; Ley N° 19.880; jurisprudencia aplicable');
  add('DAD-05','En una acción que pretende obtener la nulidad de una actuación estatal, ¿qué debe identificar primero quien la examina?','El acto o actuación impugnada, la competencia, forma y norma infringida, y el efecto jurídico que se solicita',['Únicamente la conveniencia política del acto','Sólo si el demandante está de acuerdo con el resultado','La antigüedad del órgano, sin revisar el acto concreto'],'El control de validez exige concretar el vicio y la consecuencia pretendida.','Constitución Política de la República, arts. 6 y 7; jurisprudencia');
  add('DAD-05','¿Cuál afirmación es metodológicamente correcta al estudiar nulidad de derecho público?','Debe distinguirse entre la base constitucional de juridicidad, la construcción jurisprudencial de la acción y los regímenes especiales de impugnación',['Existe una única regla legal que resuelve de idéntica forma cualquier vicio','La nulidad puede decidirse sin considerar jurisprudencia ni legislación especial','Todo conflicto administrativo se resuelve exclusivamente por nulidad de derecho público'],'La institución requiere integrar Constitución, legislación y jurisprudencia, atendiendo además a remedios especiales.','Constitución Política de la República; jurisprudencia de tribunales superiores');

  // DAD-06 Contratación administrativa
  add('DAD-06','En una licitación pública, las bases establecen requisitos conocidos por todos los oferentes. ¿Qué exigencia es esencial al evaluar las ofertas?','Aplicar criterios y condiciones previamente establecidos, respetando igualdad de los oferentes y estricta sujeción a las bases',['Modificar los criterios después de abrir las ofertas para favorecer la propuesta más conveniente','Permitir requisitos distintos para cada oferente sin fundamento','Resolver sólo por preferencia personal de la comisión'],'La contratación pública exige igualdad, transparencia y observancia de las reglas del procedimiento.','Ley N° 19.886 y su reglamentación vigente');
  add('DAD-06','¿Qué función cumplen las bases de licitación en un procedimiento de contratación pública?','Definen reglas, requisitos y criterios que vinculan a la entidad y a los participantes durante el procedimiento',['Son simples sugerencias que la entidad puede ignorar sin motivación','Reemplazan a toda la legislación de contratación pública','Sólo obligan al adjudicatario una vez firmado el contrato'],'Las bases estructuran el procedimiento y deben ajustarse al ordenamiento.','Ley N° 19.886 y reglamentación vigente');
  add('DAD-06','Una entidad adjudica a un oferente que no cumplía una exigencia esencial que sí aplicó estrictamente a los demás. ¿Qué principio se ve especialmente comprometido?','La igualdad de los oferentes y la estricta sujeción a las bases',['La inamovilidad judicial','La cosa juzgada material','La territorialidad penal'],'Tratos asimétricos carentes de fundamento dentro de una licitación pueden vulnerar igualdad y las reglas del procedimiento.','Ley N° 19.886');
  add('DAD-06','Al revisar una contratación directa o trato directo, ¿qué debe verificarse prioritariamente?','Que concurra una causal legal o reglamentaria habilitante y que la decisión esté debidamente fundada',['Que la autoridad prefiera personalmente al proveedor','Que nunca exista constancia escrita de la decisión','Que el monto sea irrelevante para el régimen aplicable'],'Las modalidades excepcionales de contratación requieren habilitación y fundamentación conforme al régimen vigente.','Ley N° 19.886 y reglamentación vigente');

  // DAD-07 Responsabilidad del Estado
  add('DAD-07','Una persona demanda reparación por daños causados por el funcionamiento de un servicio público. ¿Qué debe determinarse antes de afirmar responsabilidad estatal?','El régimen jurídico aplicable, la conducta u omisión imputada, el daño y el nexo causal, además del factor de atribución que corresponda',['Sólo que el daño haya ocurrido en un edificio público','Únicamente que exista un funcionario identificado','Que la Administración reconozca voluntariamente todos los hechos'],'La responsabilidad del Estado exige analizar sus presupuestos conforme al régimen específico aplicable.','Constitución Política de la República; Ley N° 18.575 y leyes especiales');
  add('DAD-07','¿Por qué es incorrecto aplicar automáticamente un único estatuto de responsabilidad a todos los órganos estatales?','Porque existen regímenes generales y especiales cuya aplicabilidad depende del órgano, función y normas pertinentes',['Porque el Estado nunca responde por daños','Porque sólo existe responsabilidad contractual estatal','Porque todas las entidades públicas son jurídicamente idénticas'],'El análisis debe identificar primero el estatuto aplicable y luego sus presupuestos.','Ley N° 18.575; legislación especial; jurisprudencia');
  add('DAD-07','Si el daño alegado no guarda relación causal con la conducta atribuida al órgano, ¿qué ocurre con una pretensión indemnizatoria basada en esa conducta?','Falta uno de los presupuestos necesarios para atribuir ese daño a la actuación estatal',['La responsabilidad surge igualmente por el solo hecho de existir daño','La causalidad puede presumirse de modo irrebatible en todo caso','La ausencia de causalidad sólo aumenta el monto de la indemnización'],'El nexo causal es un presupuesto central de la responsabilidad, junto con los demás elementos del régimen aplicable.','Derecho de la responsabilidad del Estado; jurisprudencia aplicable');
  add('DAD-07','¿Qué criterio metodológico es correcto frente a un caso de responsabilidad extracontractual del Estado?','Identificar primero la función y el órgano involucrados, luego el estatuto aplicable y finalmente comprobar sus presupuestos',['Partir de la indemnización deseada y luego buscar cualquier norma','Aplicar siempre sin más las reglas de un contrato privado','Omitir el régimen especial aunque la ley lo establezca'],'La responsabilidad estatal no se resuelve correctamente sin identificar el estatuto normativo aplicable al órgano y función.','Constitución Política de la República; Ley N° 18.575; legislación especial');

  // DPO-01 Organización judicial
  add('DPO-01','¿Qué criterio distingue, en términos generales, a los tribunales ordinarios de los especiales?','La fuente legal y el ámbito de competencia que el ordenamiento asigna a cada categoría',['La cantidad de escritos presentados en una causa','La voluntad de las partes de cambiar la naturaleza del tribunal','El edificio físico en que funciona el órgano'],'La organización judicial clasifica tribunales según su estatuto y competencia legal.','Código Orgánico de Tribunales');
  add('DPO-01','¿Qué órgano se sitúa en la cúspide de la estructura de los tribunales ordinarios del Poder Judicial?','La Corte Suprema',['La Contraloría General de la República','El Ministerio Público','El Tribunal Constitucional'],'La Corte Suprema es el máximo tribunal de la estructura ordinaria, sin perjuicio de órganos constitucionales externos al Poder Judicial.','Constitución Política de la República; Código Orgánico de Tribunales');
  add('DPO-01','Una Corte de Apelaciones conoce un asunto que la ley entrega a su competencia. ¿Qué característica organizacional resulta relevante?','Es un tribunal colegiado superior con competencia determinada legalmente',['Es un órgano administrativo dependiente de la Contraloría','Es un tribunal arbitral constituido por las partes','Es un órgano legislativo regional'],'Las Cortes de Apelaciones integran el Poder Judicial y ejercen jurisdicción conforme a la competencia que les atribuye la ley.','Código Orgánico de Tribunales');
  add('DPO-01','¿Cuál afirmación sobre organización judicial es correcta?','La competencia y estructura de los tribunales deben estar establecidas por el ordenamiento y no dependen de la sola voluntad de litigantes o jueces',['Cada juez puede crear un tribunal especial para un caso','Las partes pueden transformar por acuerdo una Corte de Apelaciones en tribunal arbitral','La competencia orgánica surge exclusivamente por costumbre'],'La organización de tribunales y su competencia descansan en normas legales y constitucionales.','Constitución Política de la República; Código Orgánico de Tribunales');

  // DPO-02 Deberes, prohibiciones, responsabilidad
  add('DPO-02','Un juez utiliza información reservada de una causa para favorecer un interés personal. ¿Qué dimensiones de su estatuto pueden verse comprometidas?','Deberes de probidad e imparcialidad y, según los hechos, los regímenes de responsabilidad correspondientes',['Sólo una regla de etiqueta sin efecto jurídico','Exclusivamente su competencia territorial','Únicamente el régimen de propiedad inmueble'],'El estatuto judicial contempla deberes, prohibiciones y diversas formas de responsabilidad, que deben analizarse según la conducta concreta.','Código Orgánico de Tribunales; principios de ética y probidad judicial');
  add('DPO-02','¿Cuál afirmación describe mejor la responsabilidad judicial?','La independencia no elimina la responsabilidad; los jueces están sujetos a los regímenes constitucionales y legales aplicables',['La independencia equivale a inmunidad absoluta','Todo desacuerdo con una sentencia genera responsabilidad disciplinaria','La responsabilidad judicial sólo puede ser contractual'],'Independencia y responsabilidad son compatibles; una sentencia adversa por sí sola no configura responsabilidad.','Constitución Política de la República; Código Orgánico de Tribunales');
  add('DPO-02','Antes de calificar una conducta de un juez como prohibida, ¿qué debe hacerse?','Identificar la prohibición legal o reglamentaria aplicable y verificar que los hechos encajen en su supuesto',['Aplicar por analogía cualquier prohibición prevista para otra profesión','Presumir prohibición de toda actividad extrajudicial','Atender sólo a la apariencia pública sin norma aplicable'],'Las prohibiciones requieren interpretación precisa de su fuente y supuesto, especialmente por sus consecuencias estatutarias.','Código Orgánico de Tribunales y normativa complementaria');
  add('DPO-02','¿Qué criterio es correcto al analizar responsabilidad disciplinaria de un juez?','Distinguir el desacuerdo jurisdiccional de una conducta disciplinariamente reprochable y aplicar el estatuto correspondiente',['Sancionar todo fallo revocado por un tribunal superior','Equiparar automáticamente error jurídico y falta disciplinaria','Prescindir del procedimiento disciplinario cuando exista crítica pública'],'La función jurisdiccional admite revisión por recursos, mientras la responsabilidad disciplinaria exige sus propios presupuestos.','Constitución Política de la República; Código Orgánico de Tribunales');

  // DPO-03 Implicancia y recusación
  add('DPO-03','¿Cuál es la finalidad central de las causales de implicancia y recusación?','Resguardar la imparcialidad del juzgador frente a circunstancias legalmente relevantes',['Permitir escoger al juez por conveniencia estratégica','Modificar la competencia material del tribunal','Sustituir cualquier recurso contra la sentencia'],'Las inhabilidades buscan asegurar imparcialidad y deben aplicarse conforme a causales y procedimientos legales.','Código Orgánico de Tribunales, reglas sobre implicancias y recusaciones');
  add('DPO-03','Un litigante afirma que existe amistad con una persona relacionada con el proceso. ¿Basta esa afirmación para tener al juez automáticamente por inhabilitado?','No; debe verificarse la causal legal específica, su sujeto, intensidad y demás presupuestos',['Sí; cualquier vínculo social con cualquier persona produce inhabilidad automática','Sí; basta que una parte lo solicite sin expresar causal','No; porque la amistad nunca puede ser jurídicamente relevante'],'Las causales son legales y no deben ampliarse mediante fórmulas genéricas; importa el supuesto concreto de cada norma.','Código Orgánico de Tribunales, implicancias y recusaciones');
  add('DPO-03','¿Qué diferencia metodológica debe mantenerse al estudiar implicancia y recusación?','Identificar si la circunstancia corresponde a una causal legal y aplicar el régimen y efectos propios de cada institución',['Tratarlas como sinónimos perfectos en todos sus efectos','Sustituir las causales legales por una apreciación libre del litigante','Entender que sólo existen después de dictada sentencia'],'Aunque ambas protegen imparcialidad, poseen regulación y consecuencias que deben verificarse específicamente.','Código Orgánico de Tribunales');
  add('DPO-03','Si un juez tiene un interés personal directo en el resultado del litigio, ¿qué análisis corresponde primero?','Comprobar si el hecho encuadra en una causal legal de inhabilidad y activar el procedimiento previsto',['Resolver el fondo antes de examinar la inhabilidad','Considerar irrelevante cualquier interés del juez','Permitir que las partes creen una causal nueva por contrato'],'La imparcialidad se tutela mediante causales y procedimientos legales, no por decisiones ad hoc.','Código Orgánico de Tribunales');

  // DPO-04 Competencia
  add('DPO-04','Dos tribunales podrían conocer un asunto. ¿Qué debe examinarse para determinar cuál es competente?','Las reglas legales de competencia absoluta y relativa aplicables al caso',['La preferencia personal del demandante como único criterio','La cercanía física del edificio del tribunal','El orden en que los jueces fueron nombrados'],'La competencia se determina mediante reglas legales que atienden a factores y naturaleza del asunto.','Código Orgánico de Tribunales');
  add('DPO-04','¿Cuál afirmación describe correctamente la relación entre jurisdicción y competencia?','La jurisdicción es la potestad de juzgar atribuida a los tribunales; la competencia delimita qué asuntos corresponden a cada tribunal',['Son conceptos absolutamente idénticos','La competencia existe sólo en órganos administrativos','La jurisdicción depende exclusivamente de acuerdo privado'],'La competencia distribuye el ejercicio de la jurisdicción entre los tribunales según reglas legales.','Código Orgánico de Tribunales');
  add('DPO-04','¿Puede la voluntad de las partes alterar cualquier regla de competencia?','No; la posibilidad de prórroga existe sólo en los casos y materias permitidos por el ordenamiento',['Sí; toda competencia es disponible por acuerdo','Sí; incluso la competencia absoluta puede modificarse libremente','No; porque ninguna regla de competencia admite jamás prórroga'],'Debe distinguirse entre reglas prorrogables y aquellas indisponibles según la ley.','Código Orgánico de Tribunales');
  add('DPO-04','Una cuestión surge después de que un tribunal comenzó válidamente a conocer de una causa. ¿Qué principio ayuda a mantener la competencia ya radicada, salvo excepciones legales?','La radicación o fijeza',['La delegación legislativa','La avocación administrativa','La derogación tácita de la jurisdicción'],'Las reglas generales de competencia contemplan la radicación del asunto ante el tribunal competente, sin perjuicio de excepciones legales.','Código Orgánico de Tribunales, reglas generales de competencia');

  // DPO-05 Jurisdicción y equivalentes
  add('DPO-05','¿Qué rasgo distingue a la jurisdicción frente a una mera opinión jurídica?','La potestad pública de conocer, juzgar y hacer ejecutar lo juzgado en asuntos de competencia del tribunal',['La posibilidad de sugerir soluciones sin efectos jurídicos','La facultad contractual de asesorar a una parte','La elaboración de informes administrativos no vinculantes'],'La jurisdicción es una potestad estatal atribuida a tribunales por la Constitución y la ley.','Constitución Política de la República, art. 76; Código Orgánico de Tribunales');
  add('DPO-05','Las partes ponen término a un litigio mediante un acuerdo que produce los efectos que la ley reconoce. ¿Por qué puede estudiarse como equivalente jurisdiccional?','Porque permite solucionar el conflicto por una vía reconocida jurídicamente sin una sentencia que decida el fondo',['Porque convierte a las partes en jueces del Poder Judicial','Porque deroga las normas de competencia','Porque elimina cualquier requisito de validez del acuerdo'],'Los equivalentes jurisdiccionales son mecanismos jurídicos que pueden componer el conflicto sin sentencia sobre el fondo, con efectos definidos por la ley.','Derecho procesal orgánico; legislación procesal aplicable');
  add('DPO-05','¿Qué diferencia esencial existe entre jurisdicción y competencia?','La primera es la función o potestad de juzgar; la segunda determina el ámbito concreto en que cada tribunal puede ejercerla',['La competencia es más amplia que toda jurisdicción y no tiene límites legales','La jurisdicción corresponde a particulares y la competencia sólo al Ejecutivo','No existe diferencia conceptual entre ambas'],'La distinción es básica para analizar validez del ejercicio jurisdiccional y distribución de asuntos.','Constitución Política de la República; Código Orgánico de Tribunales');
  add('DPO-05','Al estudiar un mecanismo como conciliación o transacción, ¿qué debe revisarse antes de atribuirle efecto de cierre del conflicto?','Sus requisitos legales, materias disponibles y efectos procesales o sustantivos en el caso concreto',['Sólo que una parte lo denomine equivalente jurisdiccional','Que exista siempre intervención de la Corte Suprema','Que el acuerdo se celebre necesariamente después de sentencia firme'],'Los efectos de cada mecanismo dependen de su régimen legal y de la disponibilidad del objeto litigioso.','Código Civil; Código de Procedimiento Civil y leyes especiales');

  return out;
})();
