/* Banco PF93 — especialidad penal. Borrador para revisión humana. */
const PF93_DRAFT_PENAL = (() => {
  const out=[]; const seq={};
  function add(tema,pregunta,correcta,distractores,explicacion,fuente){seq[tema]=(seq[tema]||0)+1;const pos=(out.length+seq[tema])%4;const opciones=distractores.slice(0,3);opciones.splice(pos,0,correcta);out.push({id:`pf93-${tema.toLowerCase()}-${String(seq[tema]).padStart(2,'0')}`,temaPF93:tema,pregunta,opciones:opciones.map((text,i)=>({id:'ABCD'[i],text})),respuesta:pos,explicacion,fuente:{cita:fuente,verificada:false,revisadaEn:null},estado:'revision_humana',dificultad:'media',tipo:'alternativa'});}

  // DPP-01 Principios y garantías
  add('DPP-01','Una persona es tratada como culpable antes de que exista una sentencia condenatoria firme. ¿Qué principio procesal penal resulta directamente comprometido?','La presunción de inocencia',['La oficialidad registral','La cosa juzgada civil','La autonomía de la voluntad contractual'],'El imputado debe ser tratado como inocente mientras no exista condena firme en los términos del sistema procesal penal.','Constitución Política de la República; Código Procesal Penal');
  add('DPP-01','¿Qué exige el principio de juez natural en materia penal?','Que el juzgamiento corresponda al tribunal establecido por ley con anterioridad y competente conforme al ordenamiento',['Que las partes escojan libremente al juez después del hecho','Que el fiscal pueda sustituir al tribunal','Que un órgano administrativo imponga la pena'],'La competencia penal debe radicarse en tribunales establecidos por la ley y respetar las garantías constitucionales.','Constitución Política de la República; Código Procesal Penal');
  add('DPP-01','Una condena se funda exclusivamente en antecedentes secretos que la defensa nunca pudo conocer ni controvertir. ¿Qué garantía se ve especialmente afectada?','El derecho de defensa y contradicción',['La prescripción adquisitiva','La publicidad registral inmobiliaria','La libertad contractual'],'El proceso penal acusatorio exige defensa efectiva y posibilidad de controvertir la prueba usada para condenar.','Constitución Política de la República; Código Procesal Penal');
  add('DPP-01','¿Qué función cumple el principio de legalidad procesal respecto de medidas que restringen derechos fundamentales?','Exige fundamento normativo y cumplimiento de presupuestos y controles previstos por la ley',['Autoriza cualquier restricción que parezca útil a la investigación','Permite al fiscal crear cautelares nuevas sin ley','Elimina el control judicial de las diligencias invasivas'],'Las restricciones intensas de derechos requieren habilitación legal y, cuando corresponde, control judicial.','Constitución Política de la República; Código Procesal Penal');
  add('DPP-01','¿Por qué la imparcialidad judicial es especialmente relevante en un sistema acusatorio?','Porque quien decide debe mantener independencia respecto de las funciones de investigar y acusar',['Porque el juez debe asumir la estrategia del Ministerio Público','Porque la defensa no puede controvertir al acusador','Porque la investigación reemplaza al juicio oral'],'La separación de funciones y la imparcialidad del tribunal son garantías estructurales del proceso penal.','Código Procesal Penal; garantías del debido proceso');

  // DPP-02 Sujetos/intervinientes
  add('DPP-02','¿Quién dirige en forma exclusiva la investigación de los hechos constitutivos de delito, de los que determinen participación y de los que acrediten inocencia, conforme al diseño constitucional?','El Ministerio Público',['El tribunal de juicio oral','La Defensoría Penal Pública','La Contraloría General de la República'],'La Constitución entrega al Ministerio Público la dirección exclusiva de la investigación penal, sin ejercer jurisdicción.','Constitución Política de la República, Ministerio Público');
  add('DPP-02','Una persona adquiere calidad de imputada. ¿Desde cuándo puede ejercer los derechos y garantías que el ordenamiento le reconoce como tal?','Desde la primera actuación del procedimiento dirigida en su contra en los términos legales',['Sólo después de la formalización','Únicamente cuando se dicta acusación','Sólo al comenzar el juicio oral'],'La calidad de imputado y sus derechos no dependen exclusivamente de la formalización.','Código Procesal Penal, derechos del imputado');
  add('DPP-02','¿Qué función institucional cumple la Defensoría Penal Pública?','Proporcionar defensa penal a imputados que carecen de abogado en los términos establecidos por la ley',['Dirigir la investigación penal','Dictar sentencias condenatorias','Representar necesariamente a la víctima'],'La defensa penal pública garantiza asistencia letrada conforme a su estatuto.','Ley N° 19.718; Código Procesal Penal');
  add('DPP-02','La víctima desea intervenir activamente mediante una acusación particular. ¿Qué calidad procesal puede adquirir si cumple los requisitos?','Querellante',['Perito del tribunal','Juez de garantía','Defensor público'],'La querella habilita participación procesal de la víctima u otros legitimados conforme al CPP.','Código Procesal Penal, querella');
  add('DPP-02','¿Qué rol corresponde al juez de garantía durante la investigación?','Controlar la legalidad de actuaciones y cautelar derechos, además de ejercer las demás competencias que la ley le entrega',['Dirigir estratégicamente todas las diligencias del fiscal','Asumir la defensa del imputado','Dictar el veredicto del juicio oral ordinario como regla general'],'El juez de garantía ejerce funciones jurisdiccionales de control y decisión durante etapas previas al juicio oral.','Código Procesal Penal');

  // DPP-03 Inicio y desarrollo
  add('DPP-03','¿Cuál de las siguientes puede constituir una forma de inicio del procedimiento penal según el caso?','Denuncia, querella o actuación de oficio del Ministerio Público en los supuestos legales',['Únicamente una sentencia civil previa','Sólo una orden de la Contraloría','Exclusivamente una confesión judicial del imputado'],'El CPP contempla diversas vías de conocimiento e inicio de la persecución penal.','Código Procesal Penal, inicio del procedimiento');
  add('DPP-03','Una persona es detenida en una hipótesis de flagrancia legal. ¿Qué debe ocurrir respecto del control judicial de esa detención?','Debe ser puesta a disposición del tribunal dentro de los plazos y condiciones legales para controlar la detención',['Puede permanecer indefinidamente detenida por decisión policial','La policía puede imponer directamente la pena','El control judicial sólo procede si el fiscal lo desea meses después'],'La detención está sometida a límites temporales y control jurisdiccional.','Código Procesal Penal, detención y control');
  add('DPP-03','¿Qué debe distinguirse al evaluar una denuncia penal?','El deber o facultad de denunciar, la forma de recepción y la decisión posterior del órgano persecutor conforme a la ley',['La denuncia como equivalente automático a una condena','La denuncia como sentencia firme','La denuncia como contrato entre víctima y fiscal'],'La denuncia comunica hechos; no acredita por sí sola responsabilidad ni sustituye la investigación.','Código Procesal Penal, denuncia');
  add('DPP-03','¿Qué efecto tiene, por sí sola, una declaración de ilegalidad de la detención sobre la continuidad de una investigación penal?','Debe aplicarse el régimen legal específico; la ilegalidad de la detención no equivale automáticamente al término de toda investigación',['Extingue necesariamente la acción penal en cualquier caso','Obliga al tribunal a absolver de inmediato sin juicio','Convierte al detenido en querellante'],'Las consecuencias deben determinarse conforme al CPP y no mediante una regla automática de terminación.','Código Procesal Penal; jurisprudencia sobre control de detención');

  // DPP-04 Formalización e investigación
  add('DPP-04','¿Qué función cumple la formalización de la investigación?','Comunicar al imputado, ante el juez de garantía, que se desarrolla una investigación en su contra por uno o más hechos determinados',['Declarar al imputado culpable','Sustituir la acusación y el juicio oral','Imponer por sí sola una pena'],'La formalización es un acto de comunicación procesal con efectos regulados por el CPP.','Código Procesal Penal, formalización');
  add('DPP-04','¿Puede la formalización describir hechos de manera tan indeterminada que impida al imputado comprender el núcleo de la imputación?','No; debe permitir conocer los hechos que se atribuyen para ejercer defensa',['Sí; basta señalar que existe una investigación sin hechos','Sí; porque la defensa sólo comienza en el juicio oral','No; porque la formalización debe contener ya toda la prueba de condena'],'La imputación comunicada debe ser suficientemente determinada para cumplir su función garantista.','Código Procesal Penal; derecho de defensa');
  add('DPP-04','Después de formalizar, el tribunal fija un plazo judicial para cerrar la investigación inferior al máximo legal. ¿Es conceptualmente posible?','Sí, el juez puede fijar un plazo judicial de investigación dentro del marco legal cuando corresponda',['No, toda investigación debe durar necesariamente el máximo legal','No, el fiscal fija unilateralmente un plazo inmodificable','Sí, pero sólo después de sentencia condenatoria'],'El CPP permite fijar plazo judicial para cierre de investigación dentro de sus reglas.','Código Procesal Penal, plazo de investigación');
  add('DPP-04','Una diligencia investigativa afecta intensamente un derecho fundamental y la ley exige autorización judicial previa. ¿Puede el fiscal omitirla sólo por considerar útil la diligencia?','No; debe obtener la autorización o actuar dentro de una excepción legal expresa',['Sí; la dirección de la investigación elimina todo control judicial','Sí; basta informar después de la acusación','No; porque ninguna diligencia puede afectar derechos bajo ninguna circunstancia'],'La dirección investigativa coexiste con controles judiciales para diligencias intrusivas.','Código Procesal Penal, diligencias que requieren autorización judicial');

  // DPP-05 Medidas cautelares
  add('DPP-05','¿Qué carácter debe tener la prisión preventiva dentro del sistema cautelar penal?','Excepcional y fundada en presupuestos legales, con control judicial y proporcionalidad',['Automático para todo delito formalizado','Una pena anticipada equivalente a condena','Una decisión exclusiva del fiscal sin control judicial'],'La prisión preventiva es cautelar, no punitiva, y exige presupuestos y necesidad cautelar.','Código Procesal Penal, prisión preventiva');
  add('DPP-05','Al decidir una medida cautelar personal, ¿qué debe relacionarse con la intensidad de la restricción?','La finalidad cautelar concreta y la necesidad y proporcionalidad de la medida',['La presión mediática sobre el caso','La preferencia personal del querellante','La gravedad moral abstracta sin antecedentes del caso'],'Las cautelares deben justificarse por necesidades procesales y ser proporcionales.','Código Procesal Penal, medidas cautelares personales');
  add('DPP-05','¿Qué diferencia básica existe entre prisión preventiva y pena privativa de libertad?','La primera es cautelar y provisoria; la segunda presupone una condena conforme al procedimiento',['Son exactamente la misma institución','La prisión preventiva sólo puede imponerse después de la pena','La pena es una medida puramente cautelar'],'La distinta finalidad impide usar la cautelar como castigo anticipado.','Código Procesal Penal; Constitución Política de la República');
  add('DPP-05','Si desaparecen los presupuestos que justificaron una cautelar personal, ¿qué debe ocurrir?','Debe revisarse su mantención conforme al régimen legal y cesar o modificarse cuando ya no resulte procedente',['Debe mantenerse hasta sentencia por el solo hecho de haber sido decretada','Se transforma automáticamente en pena','Sólo puede modificarse por acuerdo privado entre fiscal e imputado'],'Las medidas cautelares están sujetas a revisión por su carácter instrumental y provisional.','Código Procesal Penal');

  // DPP-06 Nulidad procesal
  add('DPP-06','¿Qué idea expresa el principio de trascendencia en nulidad procesal penal?','No basta una infracción puramente formal; debe existir un perjuicio reparable únicamente con la invalidación, salvo hipótesis legales',['Toda irregularidad produce nulidad automática','Sólo el fiscal puede alegar nulidad','La nulidad nunca requiere perjuicio'],'El CPP vincula la nulidad a perjuicio y garantías afectadas, con reglas específicas.','Código Procesal Penal, nulidades procesales');
  add('DPP-06','Una parte conocía un vicio subsanable y actuó sin reclamarlo oportunamente. ¿Qué concepto puede ser relevante?','La convalidación o preclusión de la nulidad en los casos permitidos por la ley',['La imprescriptibilidad de todo vicio','La competencia universal','La tradición ficta'],'El régimen de nulidades contempla oportunidad y saneamiento, salvo situaciones que jurídicamente no admitan convalidación.','Código Procesal Penal, nulidades');
  add('DPP-06','¿Puede declararse nulidad por un defecto que no causó ningún perjuicio procesal relevante y fue plenamente subsanado?','En principio no, si faltan los presupuestos legales de nulidad',['Sí, porque toda forma procesal es absoluta','Sí, aunque ninguna garantía se vea afectada','No, porque la nulidad penal está prohibida en cualquier caso'],'La nulidad es un remedio excepcional sujeto a sus presupuestos.','Código Procesal Penal, nulidades procesales');
  add('DPP-06','Al pedir nulidad de una actuación, ¿qué debe identificar el solicitante?','El vicio, la garantía o interés procesal afectado, el perjuicio y la forma en que la invalidación lo repara',['Sólo que no le gustó el resultado','Una causal de responsabilidad civil del juez sin conexión','La nacionalidad de los intervinientes como regla automática'],'Una alegación de nulidad exige concreción del defecto y de su trascendencia.','Código Procesal Penal, nulidad');

  // DPP-07 Salidas alternativas
  add('DPP-07','¿Qué caracteriza a la suspensión condicional del procedimiento?','Suspende la persecución bajo condiciones y por un plazo, pudiendo extinguirse la acción si se cumplen los requisitos legales',['Constituye una sentencia condenatoria firme','Impone pena sin intervención judicial','Equivale necesariamente a reconocimiento civil de todos los hechos'],'Es una salida alternativa sometida a requisitos, control judicial y condiciones.','Código Procesal Penal, suspensión condicional');
  add('DPP-07','¿Qué presupuesto conceptual distingue un acuerdo reparatorio?','Un acuerdo entre imputado y víctima en casos legalmente habilitados, aprobado judicialmente cuando se satisfacen sus requisitos',['Una condena impuesta unilateralmente por la víctima','Una decisión administrativa del fiscal sin participación de la víctima','Un recurso contra la formalización'],'Los acuerdos reparatorios son salidas alternativas limitadas a supuestos legales.','Código Procesal Penal, acuerdos reparatorios');
  add('DPP-07','¿Puede cualquier delito terminar mediante acuerdo reparatorio por sola voluntad de imputado y víctima?','No; la ley delimita los casos en que el acuerdo reparatorio es procedente',['Sí; todos los delitos son disponibles por las partes','Sí; incluso cuando la ley lo prohíbe expresamente','No; porque los acuerdos reparatorios no existen en Chile'],'La disponibilidad penal es limitada y la procedencia depende del estatuto del CPP.','Código Procesal Penal, acuerdos reparatorios');
  add('DPP-07','¿Qué debe controlar el juez antes de aprobar una salida alternativa?','El cumplimiento de sus presupuestos legales y la voluntariedad cuando corresponda',['Sólo la rapidez con que finalizará la audiencia','La popularidad de la decisión','Que la defensa renuncie a todos sus derechos futuros sin límite'],'El control judicial evita aplicar salidas alternativas fuera de los casos habilitados.','Código Procesal Penal');

  // DPP-08 Cierre e intermedia
  add('DPP-08','Cerrada la investigación, ¿qué alternativas procesales generales debe evaluar el fiscal conforme al CPP?','Acusar, solicitar sobreseimiento o comunicar decisión de no perseverar, según concurran sus presupuestos',['Dictar sentencia condenatoria por sí mismo','Imponer prisión preventiva definitiva','Transferir la causa a la Contraloría'],'El cierre abre decisiones conclusivas de investigación reguladas por el CPP.','Código Procesal Penal, cierre de investigación');
  add('DPP-08','¿Qué función cumple la audiencia de preparación del juicio oral?','Depurar la controversia, discutir acusación, convenciones probatorias y admisibilidad de prueba, preparando el juicio',['Recibir toda la prueba y dictar sentencia definitiva como regla','Reabrir automáticamente toda investigación','Resolver recursos civiles de casación'],'La etapa intermedia organiza el juicio oral y controla la acusación y la prueba que llegará a él.','Código Procesal Penal, APJO');
  add('DPP-08','¿Qué diferencia existe entre sobreseimiento definitivo y temporal?','El definitivo produce cierre con efectos más intensos en los casos legales; el temporal suspende el procedimiento mientras subsista la causa que lo justifica',['Son idénticos y siempre irrevocables','El temporal equivale a condena','El definitivo sólo puede dictarlo el fiscal sin tribunal'],'El CPP regula causales y efectos distintos para ambos tipos de sobreseimiento.','Código Procesal Penal, sobreseimiento');
  add('DPP-08','Si la acusación introduce hechos que desbordan sustancialmente la imputación comunicada, ¿qué garantía debe analizarse?','La congruencia de la acusación y el derecho de defensa',['La posesión inscrita','La libertad sindical','La competencia de la Contraloría'],'El imputado debe conocer oportunamente el núcleo fáctico de la imputación para defenderse.','Código Procesal Penal; principio de congruencia');

  // DPP-09 Prueba penal
  add('DPP-09','¿Qué regla caracteriza la valoración de la prueba en el juicio oral penal?','El tribunal valora libremente sin contradecir principios de lógica, máximas de experiencia y conocimientos científicamente afianzados, debiendo fundamentar',['Existe tarifa legal rígida para toda prueba','La confesión obliga siempre a condenar','La prueba policial prevalece por jerarquía sobre toda otra'],'El CPP adopta valoración racional y exige fundamentación.','Código Procesal Penal, valoración de la prueba');
  add('DPP-09','Una prueba fue obtenida con vulneración de garantías fundamentales. ¿En qué etapa se discute paradigmáticamente su exclusión antes del juicio?','En la audiencia de preparación del juicio oral, conforme a las reglas de exclusión',['Sólo después de cumplida la condena','En una licitación pública','Ante un árbitro civil'],'La APJO cumple una función de control de admisibilidad y exclusión probatoria.','Código Procesal Penal, exclusión de prueba');
  add('DPP-09','¿Puede una condena penal fundarse únicamente en antecedentes de investigación no incorporados como prueba al juicio oral, salvo reglas excepcionales?','No; la decisión debe fundarse en prueba producida o incorporada válidamente al juicio conforme al CPP',['Sí; la carpeta investigativa reemplaza siempre el juicio','Sí; basta el resumen del fiscal','No; porque ninguna prueba documental puede entrar al juicio'],'La inmediación y oralidad exigen que la prueba fundante de la sentencia sea rendida conforme al procedimiento.','Código Procesal Penal, juicio oral y prueba');
  add('DPP-09','¿Qué finalidad tiene la cadena de custodia respecto de evidencia material?','Preservar identidad, integridad y trazabilidad desde su obtención hasta su incorporación y valoración',['Determinar por sí sola culpabilidad','Sustituir la declaración del perito en todo caso','Convertir cualquier objeto en prueba lícita aunque se haya obtenido vulnerando derechos'],'La trazabilidad apoya autenticidad e integridad, pero no resuelve por sí sola todos los problemas de admisibilidad.','Código Procesal Penal; protocolos de evidencia');

  // DPP-10 APJO, juicio y sentencia
  add('DPP-10','¿Qué principio exige que los jueces que decidirán el caso reciban directamente la prueba en el juicio oral, salvo excepciones legales?','La inmediación',['La prórroga de competencia civil','La prescripción adquisitiva','La autonomía administrativa'],'La inmediación vincula al tribunal de juicio con la prueba rendida ante él.','Código Procesal Penal, principios del juicio oral');
  add('DPP-10','¿Cuál es la función del veredicto en el juicio oral penal?','Comunicar la decisión de absolución o condena después de la deliberación, antes de la sentencia redactada conforme al régimen legal',['Formalizar la investigación','Autorizar una diligencia intrusiva','Resolver una licitación pública'],'El juicio oral culmina con deliberación, veredicto y sentencia dentro de las reglas del CPP.','Código Procesal Penal, juicio oral');
  add('DPP-10','¿Qué estándar probatorio exige el CPP para condenar?','Convicción más allá de toda duda razonable sobre el hecho punible y participación culpable',['Probabilidad administrativa simple','Sospecha suficiente para formalizar','Mera preponderancia de evidencia civil'],'La condena requiere el estándar penal expresamente previsto por el CPP.','Código Procesal Penal, sentencia definitiva');
  add('DPP-10','Una sentencia condenatoria omite explicar por qué descarta una prueba exculpatoria relevante. ¿Qué exigencia debe revisarse?','El deber de fundamentación completa y racional de la valoración probatoria',['La facultad del tribunal de decidir sin motivar','La inexistencia de obligación de considerar prueba de descargo','La cosa juzgada antes de redactar la sentencia'],'La sentencia debe exponer razonamiento probatorio suficiente y controlable.','Código Procesal Penal, requisitos de sentencia');

  // DPP-11 Recursos
  add('DPP-11','¿Qué finalidad central tiene el recurso de nulidad penal?','Invalidar el juicio oral o la sentencia cuando concurre una causal legal de nulidad',['Obtener una tercera instancia plena sobre cualquier desacuerdo','Reabrir automáticamente la investigación','Sustituir la formalización'],'Es un recurso extraordinario sujeto a causales y requisitos específicos.','Código Procesal Penal, recurso de nulidad');
  add('DPP-11','¿Es apelable cualquier resolución dictada por un juez de garantía?','No; la apelación procede sólo respecto de resoluciones que la ley declara apelables',['Sí; toda resolución admite apelación','Sí; incluso actos materiales policiales','No; porque la apelación no existe en el proceso penal'],'El CPP establece taxativamente o por categorías las resoluciones apelables.','Código Procesal Penal, apelación');
  add('DPP-11','Una parte pretende que el mismo tribunal reconsidere una resolución dictada fuera de audiencia cuando el CPP permite esa impugnación. ¿Qué recurso puede corresponder?','Reposición',['Casación civil','Amparo económico en todo caso','Invalidación administrativa'],'La reposición permite pedir reconsideración al mismo tribunal dentro del régimen del CPP.','Código Procesal Penal, reposición');
  add('DPP-11','Años después de una condena firme aparecen antecedentes que encuadran en una causal legal extraordinaria para cuestionarla. ¿Qué mecanismo debe examinarse?','La revisión de sentencia firme',['La apelación ordinaria sin plazo','La reposición administrativa','La conciliación civil'],'La revisión es un mecanismo excepcional contra condenas firmes en hipótesis legales.','Código Procesal Penal, revisión de sentencias firmes');

  // DPP-12 Procedimientos especiales
  add('DPP-12','¿Qué rasgo caracteriza al procedimiento abreviado?','Permite resolver sin juicio oral ordinario cuando concurren los presupuestos legales y el imputado acepta expresamente los hechos y antecedentes de la investigación en los términos del CPP',['Garantiza una condena automática','Suprime la intervención del juez','Puede imponerse unilateralmente al imputado'],'El abreviado exige presupuestos, consentimiento informado y control judicial; no asegura condena.','Código Procesal Penal, procedimiento abreviado');
  add('DPP-12','¿Qué debe verificar el juez respecto de la aceptación del imputado en un procedimiento abreviado?','Que sea libre, voluntaria e informada y que comprenda sus efectos en los términos legales',['Sólo que el fiscal la solicite','Que la víctima renuncie a toda pretensión civil','Que el imputado esté en prisión preventiva'],'El consentimiento del imputado es un presupuesto central del abreviado.','Código Procesal Penal, procedimiento abreviado');
  add('DPP-12','¿En qué tipo de asuntos opera el procedimiento simplificado?','En los casos que la ley asigna a ese procedimiento por la naturaleza y pena del ilícito, bajo las reglas del CPP',['En toda causa criminal sin excepción','Sólo en crímenes con pena perpetua','Exclusivamente en litigios civiles'],'El CPP reserva procedimientos simplificados a categorías legalmente determinadas.','Código Procesal Penal, procedimiento simplificado');
  add('DPP-12','¿Qué caracteriza al procedimiento monitorio penal?','Una forma especial y simplificada prevista para supuestos específicos, con posibilidad de reclamación u oposición conforme a la ley',['Una sentencia dictada siempre sin posibilidad de contradicción','Un procedimiento civil de ejecución hipotecaria','Una investigación secreta sin control judicial'],'El monitorio penal opera en un ámbito legal acotado y contempla mecanismos de contradicción.','Código Procesal Penal, procedimiento monitorio');

  // DPP-13 Acción civil
  add('DPP-13','La víctima pretende que el imputado le indemnice los daños derivados del delito. ¿Qué debe determinarse para ejercer esa pretensión en sede penal?','La naturaleza de la acción civil, legitimación y reglas de oportunidad y competencia previstas por el CPP',['Que toda acción civil deba ejercerse necesariamente en el proceso penal','Que el fiscal sea siempre titular exclusivo de la indemnización','Que exista sentencia civil previa obligatoria'],'El CPP regula qué acciones civiles pueden interponerse en el proceso penal y bajo qué condiciones.','Código Procesal Penal, acción civil');
  add('DPP-13','¿Puede confundirse la responsabilidad penal con la responsabilidad civil derivada del mismo hecho?','No; tienen presupuestos y finalidades distintas, aunque puedan coexistir',['Sí; toda condena penal fija automáticamente cualquier indemnización posible','Sí; una absolución penal impide siempre cualquier análisis civil','No; porque los delitos nunca generan daños civiles'],'La coexistencia de consecuencias penales y civiles exige aplicar estatutos propios.','Código Procesal Penal; Código Civil');
  add('DPP-13','¿Qué finalidad cumple la demanda civil presentada dentro del proceso penal cuando procede?','Obtener reparación patrimonial conforme a las reglas civiles y procesales aplicables, aprovechando el marco que el CPP autoriza',['Pedir la imposición de una pena adicional','Sustituir al Ministerio Público en toda persecución','Determinar la competencia de la Contraloría'],'La acción civil persigue consecuencias reparatorias, no la imposición de pena.','Código Procesal Penal, acción civil');
  add('DPP-13','Antes de admitir una pretensión civil en la causa penal, ¿qué debe revisarse?','Si el CPP permite su ejercicio en esa sede, quién puede interponerla, contra quién y en qué oportunidad',['Sólo el monto solicitado','La existencia de un contrato laboral entre las partes','La nacionalidad de la víctima'],'La acumulación civil en sede penal está sometida a reglas de legitimación y oportunidad.','Código Procesal Penal, acción civil');

  // DPE-01 Ius puniendi
  add('DPE-01','Una conducta no estaba descrita como delito al momento de ejecutarse y una ley posterior pretende castigarla. ¿Qué principio se opone?','El principio de legalidad penal y prohibición de retroactividad desfavorable',['La autonomía de la voluntad','La cosa juzgada civil','La libertad contractual'],'Nadie puede ser sancionado penalmente por una conducta no previamente tipificada, salvo aplicación retroactiva favorable cuando corresponda.','Constitución Política de la República; Código Penal');
  add('DPE-01','¿Qué exige el principio de culpabilidad como límite al poder punitivo?','Que la pena se funde en responsabilidad personal por un hecho imputable, no en mera peligrosidad o responsabilidad objetiva',['Que se sancione por hechos de terceros cercanos','Que toda lesión produzca pena sin analizar imputación','Que la pena dependa sólo de la alarma social'],'La responsabilidad penal exige atribución personal del hecho conforme a categorías de culpabilidad.','Constitución Política de la República; Código Penal; doctrina penal');
  add('DPE-01','¿Qué expresa el principio non bis in idem en su dimensión material?','Impide sancionar penalmente dos veces al mismo sujeto por el mismo hecho y fundamento en los términos reconocidos por el ordenamiento',['Permite duplicar penas por idéntico hecho sin justificación','Sólo impide repetir contratos civiles','Obliga a imponer siempre la pena máxima'],'El principio limita duplicidad punitiva sobre una misma base fáctica y jurídica.','Constitución Política de la República; tratados de derechos humanos; jurisprudencia');
  add('DPE-01','¿Qué exige la proporcionalidad penal?','Que la intervención punitiva y la pena guarden relación justificada con la gravedad del hecho y los fines legítimos del sistema',['Que toda infracción reciba la misma pena','Que la pena dependa sólo del patrimonio del condenado','Que las sanciones carezcan de límite legal'],'La proporcionalidad funciona como límite de racionalidad del ius puniendi.','Constitución Política de la República; doctrina penal');
  add('DPE-01','¿Por qué la taxatividad es relevante en derecho penal?','Porque los tipos penales deben describir con suficiente determinación la conducta prohibida y sus consecuencias',['Porque permite crear delitos por analogía desfavorable','Porque autoriza al juez a inventar penas no previstas','Porque elimina la necesidad de ley previa'],'La legalidad penal exige determinación y limita analogía in malam partem.','Constitución Política de la República; Código Penal');

  // DPE-02 Ley penal tiempo/espacio
  add('DPE-02','Después de cometido un delito entra en vigencia una ley que establece una pena menos severa para el mismo hecho. ¿Qué principio debe analizarse?','La aplicación retroactiva de la ley penal más favorable en los términos legales',['La irretroactividad absoluta incluso favorable','La competencia civil prorrogada','La novación de la obligación penal'],'El derecho penal admite aplicación retroactiva favorable conforme a la Constitución y la ley.','Constitución Política de la República; Código Penal');
  add('DPE-02','¿Cuál es la regla territorial básica del derecho penal chileno?','La ley penal chilena se aplica a los delitos cometidos en el territorio de la República, sin perjuicio de excepciones legales',['Se aplica únicamente a ciudadanos chilenos','Nunca se aplica a hechos cometidos a bordo de naves chilenas','Se aplica universalmente a cualquier hecho del mundo sin conexión'],'El Código Penal establece territorialidad y excepciones de extraterritorialidad.','Código Penal; Código Orgánico de Tribunales');
  add('DPE-02','Un hecho se prolonga durante un cambio legislativo. ¿Qué debe determinarse para resolver la ley aplicable?','El momento jurídicamente relevante de comisión y el régimen de sucesión de leyes, atendida la estructura del delito',['La ley que el fiscal prefiera','La ley más antigua en todo caso','La ley civil del domicilio del imputado'],'La aplicación temporal exige precisar consumación, permanencia o continuidad y comparar los regímenes legales.','Código Penal; reglas de aplicación temporal');
  add('DPE-02','¿Puede aplicarse por analogía una ley penal posterior más gravosa a hechos anteriores?','No; la legalidad e irretroactividad desfavorable lo impiden',['Sí; si el resultado parece socialmente conveniente','Sí; toda analogía está permitida en perjuicio del imputado','No; porque ninguna ley posterior puede beneficiar tampoco'],'La analogía desfavorable y la retroactividad penal más gravosa están prohibidas.','Constitución Política de la República; Código Penal');

  // DPE-03 Tipicidad
  add('DPE-03','¿Qué función cumple la tipicidad en la teoría del delito?','Comprobar que la conducta concreta encaja en la descripción legal de un delito',['Determinar exclusivamente la cuantía de una deuda civil','Sustituir la antijuridicidad y culpabilidad en todos los casos','Permitir condenar conductas semejantes aunque no estén descritas'],'La tipicidad vincula el hecho con el tipo penal legal.','Código Penal; teoría del delito');
  add('DPE-03','Un tipo exige un resultado material separado de la conducta. ¿Cómo se clasifica normalmente?','Como delito de resultado',['Como delito meramente contractual','Como falta administrativa necesariamente','Como delito de omisión propia en todo caso'],'Los delitos de resultado requieren verificar producción e imputación del resultado típico.','Teoría del delito; Código Penal');
  add('DPE-03','¿Qué diferencia existe entre elemento descriptivo y normativo del tipo?','El descriptivo se capta principalmente por percepción o experiencia; el normativo requiere una valoración jurídica o social',['Ambos son siempre sinónimos','El normativo nunca aparece en tipos penales','El descriptivo depende exclusivamente de una sentencia civil previa'],'La estructura típica puede contener elementos que exigen distinta forma de comprensión y prueba.','Teoría del delito');
  add('DPE-03','Una conducta no satisface un elemento exigido expresamente por el tipo penal. ¿Puede afirmarse tipicidad completa sólo porque parece reprochable?','No; deben concurrir todos los elementos objetivos y subjetivos que el tipo exige',['Sí; la reprochabilidad moral sustituye al tipo','Sí; basta que exista un daño','No; porque la tipicidad nunca requiere elementos subjetivos'],'La legalidad impide completar por valoración moral un elemento típico ausente.','Código Penal; principio de tipicidad');

  // DPE-04 Causalidad/imputación objetiva
  add('DPE-04','En un delito de resultado, ¿basta comprobar que la conducta fue una condición física del resultado para atribuirlo jurídicamente?','No; además de causalidad debe examinarse la imputación jurídica u objetiva del resultado',['Sí; toda condición física genera responsabilidad penal','Sí; aunque el riesgo creado sea permitido','No; porque la causalidad es irrelevante en todo delito de resultado'],'La atribución penal del resultado exige algo más que una relación naturalística cuando la teoría del delito así lo requiere.','Teoría del delito; jurisprudencia penal');
  add('DPE-04','Una persona crea un riesgo jurídicamente permitido y ocurre un resultado extraordinario fuera del ámbito de ese riesgo. ¿Qué categoría debe examinarse?','La imputación objetiva del resultado',['La tradición civil','La cosa juzgada','La competencia territorial administrativa'],'La imputación objetiva pregunta si el resultado realiza el riesgo jurídicamente desaprobado creado por la conducta.','Teoría de la imputación objetiva');
  add('DPE-04','¿Qué utilidad tiene la teoría de la condición sine qua non?','Sirve como herramienta inicial para examinar causalidad fáctica suprimiendo mentalmente la condición',['Determina por sí sola la culpabilidad','Fija automáticamente la pena','Sustituye todas las causas de justificación'],'La causalidad naturalística es un primer nivel y no agota la atribución penal.','Teoría del delito');
  add('DPE-04','Si un resultado se debe enteramente a un curso causal independiente que habría producido el mismo resultado sin la conducta investigada, ¿qué elemento debe revisarse?','La relación causal e imputación del resultado a la conducta',['La capacidad civil del autor','La inscripción de dominio','La legitimación activa de la víctima civil'],'La atribución de un resultado exige conexión causal y normativa con la conducta.','Teoría del delito');

  // DPE-05 Antijuridicidad
  add('DPE-05','Una persona repele una agresión ilegítima actual usando un medio racionalmente necesario y sin provocación suficiente, conforme al caso. ¿Qué institución debe examinarse?','La legítima defensa',['La tentativa inidónea','La reincidencia','La prescripción extintiva civil'],'La legítima defensa es una causa de justificación sometida a requisitos legales.','Código Penal, legítima defensa');
  add('DPE-05','¿Qué efecto produce una causa de justificación plenamente concurrente?','Excluye la antijuridicidad de la conducta típica',['Elimina la tipicidad material de cualquier conducta por definición','Aumenta necesariamente la pena','Convierte el hecho en delito culposo'],'Las causas de justificación hacen lícita una conducta típica bajo sus presupuestos.','Código Penal; teoría del delito');
  add('DPE-05','En estado de necesidad justificante, ¿qué debe analizarse especialmente?','El conflicto de bienes o intereses, necesidad de la conducta y proporcionalidad conforme al régimen aplicable',['La voluntad de castigar a un tercero','La existencia de una deuda civil','La antigüedad del autor'],'El estado de necesidad exige presupuestos específicos y no se presume por cualquier dificultad.','Código Penal; teoría de causas de justificación');
  add('DPE-05','Un agente actúa creyendo erróneamente que existe una agresión que justificaría defenderse. ¿Qué problema dogmático debe examinarse?','El error sobre los presupuestos de una causa de justificación y su efecto en imputación subjetiva o culpabilidad',['La posesión inscrita','La competencia laboral','La rescisión por lesión enorme'],'El error sobre circunstancias justificantes exige analizar su tratamiento conforme a la teoría del delito.','Teoría del delito; jurisprudencia');

  // DPE-06 Culpabilidad
  add('DPE-06','Una persona desconoce un elemento fáctico integrante del tipo penal. ¿Qué categoría debe examinarse?','El error de tipo y sus efectos sobre dolo e imprudencia',['La prescripción adquisitiva','La cosa juzgada civil','La competencia absoluta'],'El error de tipo puede excluir dolo y, según el caso, dejar subsistente responsabilidad imprudente si está prevista.','Teoría del delito');
  add('DPE-06','¿Qué diferencia básica existe entre dolo e imprudencia?','El dolo supone conocimiento y voluntad respecto del hecho típico en los términos dogmáticos; la imprudencia infringe un deber de cuidado sin esa estructura dolosa',['Son siempre idénticos en requisitos y pena','La imprudencia exige intención directa de producir el resultado','El dolo sólo existe en faltas'],'La imputación subjetiva distingue actuación dolosa e imprudente y la punibilidad de esta última exige previsión legal.','Código Penal; teoría del delito');
  add('DPE-06','Una persona obra bajo una coacción extrema que el ordenamiento reconoce como exculpante. ¿Qué nivel de la teoría del delito resulta comprometido?','La culpabilidad o exigibilidad de otra conducta',['La existencia material del resultado','La clasificación de los bienes','La competencia territorial'],'Las causas de exculpación pueden excluir reproche personal aunque el hecho siga siendo típico y antijurídico.','Código Penal; teoría de culpabilidad');
  add('DPE-06','¿Qué debe determinarse frente a un error de prohibición?','Si el autor podía conocer la ilicitud de su conducta y qué efecto produce la evitabilidad o inevitabilidad del error según el sistema aplicable',['Si existió inscripción conservatoria','Si la víctima es acreedora contractual','Si el tribunal civil admitió la demanda'],'El error de prohibición se relaciona con conciencia de antijuridicidad y culpabilidad.','Teoría del delito; jurisprudencia penal');

  // DPE-07 Concurso
  add('DPE-07','Una sola conducta realiza simultáneamente más de un tipo penal. ¿Qué problema debe analizarse?','El concurso ideal y las reglas de determinación aplicables',['La novación civil','La mediación familiar','La prórroga de competencia'],'El concurso ideal aborda pluralidad de infracciones realizadas mediante un mismo hecho, según el régimen penal.','Código Penal, concurso de delitos');
  add('DPE-07','Varias conductas independientes constituyen delitos distintos imputables al mismo autor. ¿Qué categoría concursal puede corresponder?','Concurso real o material',['Un único delito por definición','Una causa de justificación automática','Una cuestión exclusivamente civil'],'La pluralidad de hechos puede configurar concurso real, sujeto a reglas de pena.','Código Penal, concurso y reiteración');
  add('DPE-07','Cuando una norma penal especial desplaza a otra general que también parecería describir el hecho, ¿qué relación puede operar?','Especialidad dentro del concurso aparente de leyes',['Concurso real necesario','Prescripción adquisitiva','Solidaridad civil'],'El concurso aparente se resuelve mediante criterios como especialidad, subsidiariedad, consunción u otros reconocidos.','Teoría del concurso aparente');
  add('DPE-07','¿Por qué debe distinguirse concurso de delitos de concurso aparente de leyes?','Porque en el primero hay pluralidad de infracciones a sancionar; en el segundo varias normas parecen aplicables pero una desplaza a las otras',['Porque ambos producen siempre la misma pena','Porque el concurso aparente requiere varios hechos materiales','Porque el concurso real sólo existe en derecho civil'],'La distinción determina cuántas infracciones se consideran y cómo se calcula la respuesta penal.','Código Penal; teoría del concurso');

  // DPE-08 Autoría y participación
  add('DPE-08','¿Qué cuestión central resuelven las reglas de autoría y participación?','Cómo atribuir responsabilidad a quienes realizan, determinan o colaboran en un hecho delictivo conforme a las categorías legales',['Cómo transferir el dominio de la cosa objeto del delito','Cómo fijar la competencia civil','Cómo extinguir una obligación contractual'],'El Código Penal diferencia formas de intervención con efectos jurídicos propios.','Código Penal, arts. 15 y siguientes');
  add('DPE-08','Una persona presta una colaboración relevante al delito sin realizar por sí sola el núcleo de la conducta típica. ¿Qué debe analizarse?','Si su intervención encuadra como autoría o forma de participación conforme a los hechos y reglas legales',['Que todo colaborador es necesariamente autor directo','Que ninguna ayuda puede ser punible','Que sólo existe responsabilidad si recibe pago'],'La calificación depende del aporte concreto y de las categorías legales de autor, cómplice o encubridor, entre otras.','Código Penal, participación criminal');
  add('DPE-08','¿Puede atribuirse responsabilidad penal a una persona sólo por su relación familiar con el autor?','No; debe acreditarse una forma de intervención personalmente imputable conforme a la ley',['Sí; el parentesco genera autoría automática','Sí; toda convivencia presume complicidad','No; porque los familiares nunca pueden participar en delitos'],'La responsabilidad penal es personal y requiere conducta propia jurídicamente relevante.','Código Penal; principio de culpabilidad');
  add('DPE-08','¿Qué diferencia conceptual existe entre autor y cómplice?','El autor encuadra en las formas legales de autoría; el cómplice coopera en los términos legales sin quedar comprendido como autor',['Son categorías sin diferencia jurídica','El cómplice siempre ejecuta íntegramente el tipo','El autor sólo aparece después de consumado el delito'],'Las categorías de intervención se definen por el Código Penal y afectan imputación y pena.','Código Penal, participación criminal');

  // DPE-09 Iter criminis
  add('DPE-09','El autor inicia la ejecución de un delito mediante hechos directos, pero no realiza todos los actos necesarios por causas ajenas a su voluntad. ¿Qué grado debe examinarse?','La tentativa, conforme a su definición legal',['El delito consumado necesariamente','Una mera idea impune en todo caso','La prescripción'],'La tentativa supone principio de ejecución sin completar todos los actos necesarios por causas independientes de la voluntad.','Código Penal, grados de desarrollo');
  add('DPE-09','Se ejecutan todos los actos necesarios para consumar un delito, pero el resultado no se produce por causas independientes de la voluntad. ¿Qué grado puede corresponder según el régimen chileno?','El delito frustrado, cuando el tipo y los hechos permiten esa categoría',['La etapa preparatoria impune necesariamente','La consumación','La complicidad posterior'],'El Código Penal distingue tentativa, frustración y consumación en los delitos que admiten esas fases.','Código Penal, iter criminis');
  add('DPE-09','¿Cuándo existe consumación?','Cuando se realizan todos los elementos exigidos por el tipo penal correspondiente',['Cuando el autor sólo piensa cometer el delito','Desde cualquier acto preparatorio remoto','Sólo después de cumplida la pena'],'La consumación depende de la estructura del tipo y de la realización completa de sus elementos.','Código Penal; teoría del delito');
  add('DPE-09','¿Son punibles en general los meros actos preparatorios de cualquier delito?','No; como regla no lo son, salvo que la ley los tipifique específicamente o contemple una excepción',['Sí; todo pensamiento preparatorio es delito','Sí; cualquier conversación previa se castiga como consumación','No; porque jamás pueden ser tipificados por la ley'],'La punibilidad anticipada requiere base legal expresa.','Código Penal; principio de legalidad');

  // DPE-10 Pena y modificatorias
  add('DPE-10','Para determinar concretamente una pena, ¿qué debe hacerse antes de aplicar atenuantes o agravantes?','Identificar el marco penal del delito, grado de ejecución y forma de participación, aplicando luego las reglas legales pertinentes',['Elegir la pena por intuición y después buscar fundamento','Aplicar siempre el máximo legal','Ignorar el grado de ejecución'],'La determinación de pena sigue una secuencia normativa regulada por el Código Penal y leyes especiales.','Código Penal, determinación de penas');
  add('DPE-10','¿Qué efecto tienen las circunstancias atenuantes o agravantes?','Modifican la responsabilidad y pueden incidir en la determinación de la pena conforme a reglas legales',['Cambian automáticamente la tipicidad del hecho','Siempre extinguen la responsabilidad','No producen nunca ningún efecto'],'Su incidencia depende del número, naturaleza y reglas de compensación o graduación aplicables.','Código Penal, circunstancias modificatorias');
  add('DPE-10','¿Por qué no basta contar mecánicamente atenuantes y agravantes?','Porque deben aplicarse las reglas legales sobre su naturaleza, efectos, compensación y marco de pena',['Porque las circunstancias nunca importan','Porque sólo el fiscal determina la pena','Porque toda atenuante equivale a una absolución'],'La determinación de pena exige aplicar sistemáticamente el estatuto correspondiente.','Código Penal, determinación de penas');
  add('DPE-10','Antes de invocar reincidencia como agravante, ¿qué debe verificarse?','La causal legal específica y sus presupuestos, incluidos antecedentes condenatorios relevantes y reglas aplicables',['Sólo que el imputado haya sido alguna vez detenido','Que exista una denuncia antigua','La existencia de cualquier causa civil previa'],'La reincidencia exige presupuestos legales y no deriva de mera sospecha o detención anterior.','Código Penal, agravantes');

  // DPE-11 Vida y salud
  add('DPE-11','Una conducta dolosa causa la muerte de otra persona. ¿Qué debe determinarse para calificar jurídicamente el hecho?','El tipo de homicidio aplicable y la concurrencia de circunstancias específicas previstas por la ley',['Sólo que exista un resultado de muerte, pues toda muerte tiene igual calificación','La existencia de un contrato entre autor y víctima','La cuantía del patrimonio de la víctima'],'Los delitos contra la vida se diferencian por elementos y circunstancias típicas que deben acreditarse.','Código Penal, delitos contra la vida');
  add('DPE-11','Una agresión causa lesiones corporales. ¿Qué aspecto es central para su calificación penal?','La entidad y consecuencias de la lesión conforme a las categorías legales, junto con el elemento subjetivo',['La profesión de la víctima como único criterio','El lugar geográfico sin considerar el daño','La mera existencia de una discusión previa'],'Los delitos de lesiones se clasifican considerando resultados y circunstancias tipificadas.','Código Penal, lesiones');
  add('DPE-11','¿Puede equipararse automáticamente toda omisión de auxilio a un homicidio por omisión?','No; una imputación omisiva de resultado exige, entre otros elementos, una posición de garante y los demás presupuestos dogmáticos y legales',['Sí; toda omisión produce autoría de homicidio','Sí; basta presencia física en el lugar','No; porque los delitos de resultado nunca admiten comisión por omisión'],'La comisión por omisión requiere deber especial de actuar y atribución del resultado.','Código Penal; teoría de la omisión impropia');
  add('DPE-11','En un delito contra la vida, ¿por qué es relevante distinguir dolo de imprudencia?','Porque determina el tipo aplicable y el régimen de responsabilidad, y la imprudencia sólo se sanciona cuando la ley lo contempla',['Porque ambas formas producen siempre idéntica calificación','Porque el dolo excluye toda pena','Porque la imprudencia es siempre más grave'],'La imputación subjetiva es decisiva para diferenciar delitos dolosos y culposos.','Código Penal, homicidio y cuasidelitos');
  add('DPE-11','Una lesión se produce en legítima defensa plenamente justificada. ¿Basta el resultado lesivo para afirmar delito?','No; debe examinarse la antijuridicidad y la eventual causa de justificación',['Sí; todo resultado lesivo es delito sin excepciones','Sí; las causas de justificación sólo afectan la pena','No; porque las lesiones nunca son típicas'],'Tipicidad y resultado no bastan si concurre una causa de justificación.','Código Penal, legítima defensa y lesiones');

  // DPE-12 Delitos sexuales
  add('DPE-12','Al analizar un delito sexual, ¿qué debe hacerse antes de escoger la figura penal aplicable?','Identificar la conducta concreta, edad y situación de la víctima, medios empleados y demás elementos específicos del tipo',['Aplicar una única figura a cualquier conducta sexual','Presumir consentimiento por ausencia de lesiones físicas','Determinar la pena antes de establecer el tipo'],'Los delitos sexuales contienen elementos diferenciados que exigen análisis preciso de hechos y tipo.','Código Penal, delitos sexuales');
  add('DPE-12','¿Por qué el consentimiento no puede analizarse de manera puramente formal en delitos sexuales?','Porque deben considerarse capacidad, libertad, edad, coerción y circunstancias que la ley tipifica como excluyentes o irrelevantes para consentir',['Porque el consentimiento nunca tiene relevancia en ningún delito sexual','Porque basta una relación previa entre las personas','Porque siempre se presume consentimiento si no hay testigos'],'La validez o relevancia del consentimiento depende de condiciones legales y de la libertad real de la persona.','Código Penal, delitos contra la libertad e indemnidad sexual');
  add('DPE-12','Una conducta sexual involucra a una persona menor de edad. ¿Qué criterio jurídico es indispensable?','Aplicar las reglas especiales de protección y edades que integran los tipos penales correspondientes',['Usar las mismas reglas de consentimiento de cualquier adulto sin matices','Considerar irrelevante la edad','Resolver exclusivamente por costumbre social'],'La edad es elemento central en diversas figuras de protección de indemnidad sexual.','Código Penal, delitos sexuales');
  add('DPE-12','¿Puede condenarse por un delito sexual sin probar más allá de duda razonable los elementos específicos del tipo?','No; la gravedad del delito no reduce el estándar probatorio penal',['Sí; basta la mera denuncia para condenar automáticamente','Sí; el estándar se reemplaza por probabilidad simple','No; porque estos delitos no pueden perseguirse penalmente'],'El estándar de condena y la presunción de inocencia rigen también en delitos sexuales.','Código Procesal Penal; Código Penal');
  add('DPE-12','¿Qué metodología es correcta para diferenciar figuras sexuales próximas?','Comparar sistemáticamente acción típica, sujeto pasivo, edad, medios comisivos y circunstancias calificantes de cada figura',['Escoger siempre la figura con pena mayor','Atender sólo al nombre común de la conducta','Omitir elementos normativos porque son difíciles de probar'],'La calificación exige subsunción precisa y respeto de legalidad y tipicidad.','Código Penal, delitos sexuales');

  // DPE-13 Patrimonio
  add('DPE-13','¿Qué elemento distingue paradigmáticamente robo de hurto?','El empleo de violencia o intimidación en las personas, o fuerza en las cosas, según las figuras legales',['La existencia de una cosa mueble como único elemento','El valor de la cosa en todo caso','La relación contractual previa entre autor y víctima'],'Hurto y robo comparten apropiación de cosa mueble ajena, pero el robo incorpora medios comisivos específicos.','Código Penal, hurto y robo');
  add('DPE-13','En una estafa, ¿qué secuencia conceptual debe examinarse?','Engaño idóneo, error, disposición patrimonial, perjuicio y relación entre esos elementos, conforme al tipo aplicable',['Violencia física como elemento indispensable','Apropiación clandestina sin interacción con la víctima como única forma','La mera promesa incumplida como estafa automática'],'La estafa exige una estructura defraudatoria que no se identifica con cualquier incumplimiento civil.','Código Penal, estafas y defraudaciones');
  add('DPE-13','Una persona toma una cosa mueble ajena sin voluntad de su dueño y con ánimo de apropiación, sin violencia, intimidación ni fuerza típica. ¿Qué figura debe examinarse inicialmente?','Hurto',['Estafa necesariamente','Homicidio','Malversación pública en todo caso'],'El hurto protege la propiedad frente a apropiación de cosa mueble ajena sin los medios que califican el robo.','Código Penal, hurto');
  add('DPE-13','¿Por qué un mero incumplimiento contractual no constituye automáticamente estafa?','Porque deben acreditarse los elementos típicos de engaño, error, disposición y perjuicio, incluido el dolo correspondiente',['Porque los contratos nunca pueden relacionarse con delitos','Porque toda deuda civil excluye responsabilidad penal','Porque la estafa no exige perjuicio'],'La frontera civil-penal depende de los elementos típicos y no del solo incumplimiento.','Código Penal, estafa; jurisprudencia');
  add('DPE-13','Al determinar si la fuerza empleada sobre una cosa configura una modalidad de robo, ¿qué debe hacerse?','Verificar si el medio y las circunstancias encajan en las hipótesis tipificadas por el Código Penal',['Considerar robo cualquier deterioro mínimo sin atender al tipo','Aplicar analogía para ampliar las hipótesis legales','Atender sólo al valor económico de lo sustraído'],'La legalidad obliga a subsumir el medio comisivo en una figura expresamente prevista.','Código Penal, robos');

  return out;
})();
