/* Banco PF93 — especialidad laboral. Borrador para revisión humana. */
const PF93_DRAFT_LABORAL = (() => {
  const out=[]; const seq={};
  function add(tema,pregunta,correcta,distractores,explicacion,fuente){seq[tema]=(seq[tema]||0)+1;const pos=(out.length+seq[tema])%4;const opciones=distractores.slice(0,3);opciones.splice(pos,0,correcta);out.push({id:`pf93-${tema.toLowerCase()}-${String(seq[tema]).padStart(2,'0')}`,temaPF93:tema,pregunta,opciones:opciones.map((text,i)=>({id:'ABCD'[i],text})),respuesta:pos,explicacion,fuente:{cita:fuente,verificada:false,revisadaEn:null},estado:'revision_humana',dificultad:'media',tipo:'alternativa'});}

  // DLA-01 Derechos fundamentales
  add('DLA-01','Un empleador revisa comunicaciones privadas de un trabajador sin política previa, justificación ni resguardo de proporcionalidad. ¿Qué dimensión debe analizarse especialmente?','El respeto de la vida privada y derechos fundamentales del trabajador dentro de la relación laboral',['La propiedad del establecimiento como poder ilimitado','La inexistencia de derechos fundamentales en el trabajo','La competencia de la Contraloría'],'El poder de dirección está limitado por derechos fundamentales y por criterios de justificación y proporcionalidad.','Constitución Política de la República; Código del Trabajo, tutela de derechos fundamentales');
  add('DLA-01','¿Qué caracteriza al principio de no discriminación laboral?','Prohíbe distinciones, exclusiones o preferencias carentes de justificación legítima en los términos constitucionales y legales',['Impide toda diferenciación fundada en requisitos objetivos del cargo','Permite discriminar si se informa por escrito','Sólo rige después de terminado el contrato'],'La igualdad y no discriminación se proyectan al acceso, desarrollo y término de la relación laboral.','Constitución Política de la República; Código del Trabajo');
  add('DLA-01','Una medida empresarial limita un derecho fundamental para alcanzar un fin legítimo. ¿Qué test debe realizarse?','Examinar idoneidad, necesidad y proporcionalidad de la medida, además de su habilitación jurídica',['Aceptar toda limitación por provenir del empleador','Rechazar toda medida organizativa sin ponderación','Evaluar sólo si la medida reduce costos'],'La ciudadanía en la empresa exige compatibilizar facultades de dirección con derechos fundamentales.','Código del Trabajo, tutela laboral; doctrina constitucional');
  add('DLA-01','¿Qué finalidad tiene el procedimiento de tutela laboral?','Otorgar protección jurisdiccional frente a vulneraciones de derechos fundamentales en el ámbito de la relación laboral, bajo sus requisitos',['Resolver únicamente diferencias de cálculo de remuneraciones','Reemplazar toda negociación colectiva','Convertir cualquier despido en delito'],'La tutela es un procedimiento especial dirigido a lesiones de derechos fundamentales laborales.','Código del Trabajo, procedimiento de tutela');
  add('DLA-01','Un trabajador denuncia una vulneración y luego es objeto de represalia por ejercer una acción o participar ante la autoridad. ¿Qué garantía puede resultar comprometida?','La garantía de indemnidad',['La posesión inscrita','La libertad de contratación civil del empleador como regla absoluta','La competencia territorial penal'],'La tutela laboral protege frente a represalias asociadas al ejercicio legítimo de derechos y acciones.','Código del Trabajo, tutela de derechos fundamentales');

  // DLA-02 Sujetos/subordinación
  add('DLA-02','Una persona presta servicios personales, recibe remuneración y está sujeta a instrucciones, supervisión y horario impuesto. ¿Qué debe examinarse para determinar si existe contrato de trabajo?','La concurrencia de prestación personal, remuneración y subordinación o dependencia, más allá del nombre dado al acuerdo',['Sólo el título escrito del documento','La emisión de boletas como factor siempre concluyente','La profesión del prestador como único criterio'],'La realidad de la prestación prevalece sobre la denominación formal si concurren elementos del contrato de trabajo.','Código del Trabajo, arts. 7 y 8');
  add('DLA-02','¿Qué indicios suelen ser relevantes para apreciar subordinación o dependencia?','Continuidad, sujeción a instrucciones y control, horario o inserción organizacional, valorados en conjunto',['Únicamente la existencia de uniforme','Sólo el lugar físico de trabajo','Exclusivamente la duración del vínculo'],'La subordinación se infiere de indicios de dirección y organización, no de un solo elemento aislado.','Código del Trabajo; jurisprudencia laboral');
  add('DLA-02','¿Puede la denominación “prestación de servicios independientes” impedir siempre que un tribunal declare relación laboral?','No; debe atenderse a los hechos efectivos y a los elementos legales de la relación',['Sí; el nombre contractual es irrebatible','Sí; si se emite una sola boleta, cualquiera sea la realidad','No; porque todo servicio personal es necesariamente laboral'],'El principio de primacía de la realidad orienta la calificación del vínculo.','Código del Trabajo; jurisprudencia');
  add('DLA-02','¿Quién es empleador para el Código del Trabajo?','La persona natural o jurídica que utiliza servicios de una o más personas en virtud de un contrato de trabajo',['Sólo una sociedad anónima','Exclusivamente quien paga materialmente cada remuneración','El cliente final de cualquier servicio, sin considerar subordinación'],'El estatuto define empleador atendiendo a la utilización de servicios bajo relación laboral.','Código del Trabajo, definiciones');

  // DLA-03 Tercerización
  add('DLA-03','Una empresa principal encarga a un contratista ejecutar obras o servicios por su cuenta y riesgo con trabajadores propios. ¿Qué régimen debe examinarse?','La subcontratación, si concurren los presupuestos legales',['El suministro transitorio necesariamente','Una sociedad entre todos los trabajadores y la principal','Un mandato civil que excluye toda regla laboral'],'La subcontratación supone contratista que ejecuta obras o servicios por su cuenta y riesgo para una empresa principal.','Código del Trabajo, subcontratación');
  add('DLA-03','¿Qué diferencia esencial existe entre subcontratación y suministro de trabajadores por empresa de servicios transitorios?','En el suministro la EST pone trabajadores a disposición de una usuaria bajo un régimen legal temporal; en subcontratación el contratista organiza la obra o servicio por su cuenta y riesgo',['Son figuras idénticas','La subcontratación siempre implica cesión ilegal de trabajadores','El suministro puede ser permanente y sin causal'],'Cada figura tiene sujetos, finalidades y responsabilidades distintas.','Código del Trabajo, subcontratación y empresas de servicios transitorios');
  add('DLA-03','¿Qué finalidad tienen los derechos de información y retención de la empresa principal en subcontratación?','Permitir controlar cumplimiento de obligaciones laborales y previsionales y modular la responsabilidad conforme al régimen legal',['Eliminar toda responsabilidad de la principal sin condiciones','Autorizar a pagar remuneraciones inferiores','Sustituir al contratista como empleador en todo caso'],'El estatuto vincula mecanismos de control con responsabilidad solidaria o subsidiaria según corresponda.','Código del Trabajo, subcontratación');
  add('DLA-03','Una empresa “contratista” carece de organización propia y la principal dirige directamente en forma permanente a sus trabajadores. ¿Qué debe analizarse?','La realidad de la relación, eventual simulación o suministro ilícito y quién ejerce efectivamente funciones de empleador',['Sólo el contrato comercial escrito entre empresas','La inexistencia de cualquier consecuencia laboral','La competencia de un tribunal civil como única vía'],'La tercerización no puede usarse para eludir la identificación del verdadero empleador o las reglas legales.','Código del Trabajo; jurisprudencia laboral');

  // DLA-04 Poder empleador
  add('DLA-04','¿Cuál es un límite general al poder de dirección del empleador?','El respeto de la ley, el contrato y los derechos fundamentales del trabajador',['La voluntad empresarial como fuente ilimitada','La inexistencia de límites dentro del establecimiento','La facultad de modificar cualquier condición esencial sin restricción'],'Las potestades organizativas están jurídicamente limitadas.','Código del Trabajo; Constitución Política de la República');
  add('DLA-04','El empleador implementa una medida de control. ¿Qué debe examinarse respecto de derechos fundamentales?','Que persiga un fin legítimo y sea idónea, necesaria y proporcional, además de cumplir las reglas laborales aplicables',['Sólo que sea tecnológicamente posible','Que permita vigilar fuera del trabajo sin límite','Que nunca sea informada al trabajador'],'El control empresarial debe conciliarse con dignidad y derechos fundamentales.','Código del Trabajo; jurisprudencia de tutela');
  add('DLA-04','¿Puede el empleador alterar unilateralmente cualquier cláusula contractual invocando su poder de mando?','No; las modificaciones unilaterales sólo proceden dentro de facultades y requisitos legales específicos',['Sí; el contrato queda enteramente a discreción del empleador','Sí; siempre que el trabajador no reclame el mismo día','No; porque ninguna condición laboral puede modificarse jamás por acuerdo'],'El ius variandi es excepcional y reglado; fuera de él rige fuerza obligatoria del contrato y acuerdo de partes.','Código del Trabajo');
  add('DLA-04','Una instrucción empresarial ordena ejecutar una conducta manifiestamente ilícita. ¿El deber de obediencia obliga a cumplirla?','No; el poder de dirección no ampara órdenes contrarias al ordenamiento',['Sí; toda instrucción del empleador es jurídicamente superior a la ley','Sí; pero sólo si consta por escrito','No; porque el trabajador puede ignorar cualquier instrucción aunque sea lícita'],'La subordinación laboral no elimina la sujeción de ambas partes a la ley.','Código del Trabajo; principios generales');

  // DLA-05 Contrato
  add('DLA-05','¿Qué caracteriza al contrato de trabajo?','Prestación personal de servicios bajo subordinación o dependencia a cambio de remuneración',['Transferencia de dominio de una cosa a cambio de precio','Prestación necesariamente gratuita','Ausencia de dirección por parte del empleador'],'Los elementos del contrato están definidos legalmente y se aprecian en la realidad.','Código del Trabajo, art. 7');
  add('DLA-05','¿Qué efecto tiene la falta de escrituración del contrato dentro del plazo legal?','No impide por sí sola la existencia de relación laboral si concurren sus elementos, aunque genera consecuencias probatorias y sancionatorias',['Hace inexistente toda relación y elimina remuneraciones','Convierte al trabajador en socio','Impide al tribunal conocer del vínculo'],'El contrato es consensual, aunque existe deber legal de escriturarlo.','Código del Trabajo, reglas de escrituración');
  add('DLA-05','¿Qué debe contener la escrituración del contrato?','Las estipulaciones mínimas que exige el Código del Trabajo, además de las que las partes acuerden lícitamente',['Sólo nombre y firma del empleador','Una renuncia general a derechos laborales','Cláusulas que permitan modificar libremente cualquier condición sin límite'],'El Código exige individualizar elementos esenciales de la relación.','Código del Trabajo, contenido del contrato');
  add('DLA-05','Una cláusula contractual renuncia anticipadamente a un derecho laboral indisponible mientras subsiste el contrato. ¿Qué principio resulta relevante?','La irrenunciabilidad de los derechos laborales en los términos legales',['La autonomía absoluta de la voluntad','La prescripción adquisitiva','La libertad de empresa como derogación de la ley'],'El Código limita renuncias mientras subsiste la relación respecto de derechos establecidos por las leyes laborales.','Código del Trabajo, art. 5');

  // DLA-06 Jornada
  add('DLA-06','Antes de calcular si existe exceso de jornada ordinaria, ¿qué debe verificarse?','El régimen de jornada aplicable al trabajador, eventuales exclusiones o sistemas especiales y la jornada máxima vigente en la fecha',['Un número histórico fijo sin revisar reformas graduales','Sólo la voluntad unilateral del empleador','La cantidad de años trabajados'],'La jornada ha sido objeto de reformas graduales; debe usarse el texto vigente y el régimen específico.','Código del Trabajo, jornada; Ley N° 21.561 y vigencia progresiva');
  add('DLA-06','¿Qué diferencia existe entre jornada de trabajo y tiempo de descanso?','La jornada comprende tiempo de prestación y aquel en que el trabajador está a disposición sin labor por causas no imputables, conforme a la ley; los descansos se rigen por reglas propias',['Todo tiempo calendario es jornada','Los descansos siempre integran jornada sin excepción','La jornada depende sólo del lugar físico'],'El Código define jornada y regula descansos, colación y sistemas especiales.','Código del Trabajo, jornada');
  add('DLA-06','¿Puede pactarse libremente cualquier cantidad de horas extraordinarias de manera permanente?','No; las horas extraordinarias están sujetas a finalidad, acuerdo, límites y temporalidad legal',['Sí; no existe límite alguno','Sí; pueden reemplazar indefinidamente la jornada ordinaria','No; porque las horas extraordinarias están prohibidas en Chile'],'El sobretiempo tiene régimen excepcional y límites.','Código del Trabajo, horas extraordinarias');
  add('DLA-06','Un sistema de control de asistencia no registra de modo fiable las horas efectivamente trabajadas. ¿Qué problema genera?','Dificulta acreditar y controlar cumplimiento de jornada, descansos y sobretiempo, además de incumplir las obligaciones de registro que correspondan',['Elimina automáticamente el contrato','Convierte todo tiempo en descanso','Impide pagar remuneraciones base'],'El empleador debe llevar los registros exigidos por el régimen aplicable.','Código del Trabajo; normativa de registro de asistencia');

  // DLA-07 Remuneraciones
  add('DLA-07','¿Qué principio protege que el trabajador reciba íntegra y oportunamente su remuneración, salvo descuentos autorizados por la ley?','La protección de las remuneraciones',['La libre apropiación empresarial del salario','La prescripción adquisitiva del sueldo','La compensación unilateral ilimitada'],'El Código regula forma, oportunidad y descuentos para proteger la remuneración.','Código del Trabajo, protección de remuneraciones');
  add('DLA-07','¿Puede el empleador practicar cualquier descuento que estime conveniente de la remuneración?','No; los descuentos deben fundarse en la ley, mandato o acuerdo válido dentro de límites legales',['Sí; toda deuda alegada permite descuento completo','Sí; basta una instrucción verbal de jefatura','No; porque ningún descuento está permitido nunca'],'La ley distingue descuentos obligatorios, permitidos y prohibidos o limitados.','Código del Trabajo, descuentos de remuneraciones');
  add('DLA-07','Una prestación es pagada regularmente como contraprestación por los servicios. ¿Qué debe examinarse para saber si constituye remuneración?','Su naturaleza y si encaja en la definición y exclusiones legales, no sólo el nombre asignado por las partes',['Sólo el nombre “bono” o “asignación”','La voluntad unilateral del empleador','La forma de pago en efectivo como único criterio'],'La calificación depende de la función económica y de las reglas del Código.','Código del Trabajo, concepto de remuneración');
  add('DLA-07','¿Por qué el comprobante de pago de remuneraciones es relevante?','Permite transparentar haberes, descuentos y monto pagado y facilita control del cumplimiento',['Porque reemplaza el contrato de trabajo','Porque extingue cualquier acción laboral aunque contenga errores','Porque autoriza descuentos no permitidos'],'La documentación de remuneraciones cumple una función de información y prueba.','Código del Trabajo, pago de remuneraciones');

  // DLA-08 Protección/maternidad/paternidad/familia
  add('DLA-08','Una trabajadora embarazada es despedida sin autorización judicial pese a encontrarse amparada por fuero. ¿Qué institución debe examinarse?','La protección de maternidad y el régimen de fuero laboral',['La prescripción adquisitiva','La libertad de despido sin límites','La competencia arbitral obligatoria'],'La maternidad cuenta con protección especial y el despido de persona aforada exige desafuero en los casos legales.','Código del Trabajo, protección a la maternidad');
  add('DLA-08','¿Qué finalidad tiene el descanso de maternidad y las licencias relacionadas con cuidado familiar?','Proteger salud, maternidad, paternidad, infancia y conciliación de vida laboral y familiar dentro del régimen legal',['Sancionar al empleador','Eliminar definitivamente la obligación de prestar servicios','Transferir el contrato a un tercero'],'El Código contempla permisos y descansos protectores con requisitos y efectos definidos.','Código del Trabajo, protección a la maternidad, paternidad y vida familiar');
  add('DLA-08','¿Puede un empleador discriminar a una postulante por embarazo o maternidad en los términos prohibidos por la ley?','No; la maternidad no habilita discriminaciones contrarias al ordenamiento',['Sí; siempre es un criterio empresarial legítimo','Sí; si se pregunta en una entrevista privada','No; pero sólo después de un año de contrato'],'La protección de maternidad se conecta con igualdad y no discriminación.','Código del Trabajo; Constitución Política de la República');
  add('DLA-08','Un trabajador solicita un permiso legal para atender una situación familiar cubierta por la legislación. ¿Qué debe hacer el empleador?','Aplicar el régimen específico de permiso, verificando requisitos y sin desconocer el derecho cuando procede',['Negarlo por regla general porque la vida familiar es ajena al trabajo','Exigir renuncia al empleo','Transformarlo automáticamente en vacaciones'],'Los permisos de conciliación operan según causales y requisitos definidos por ley.','Código del Trabajo, permisos y conciliación');

  // DLA-09 Terminación
  add('DLA-09','Un empleador pone término al contrato invocando una causal legal. ¿Qué debe verificarse para evaluar el despido?','Que los hechos comunicados encajen en la causal, se cumplan formalidades y existan antecedentes suficientes cuando la causal lo exige',['Sólo que la carta mencione un número de artículo','Que el empleador prefiera terminar el vínculo','La firma del trabajador aceptando la causal como requisito universal'],'La legalidad del despido depende de causal, hechos, comunicación y demás requisitos.','Código del Trabajo, terminación');
  add('DLA-09','El empleador incurre en un incumplimiento grave de sus obligaciones y el trabajador pone término al contrato reclamando indemnizaciones. ¿Qué institución corresponde?','El despido indirecto o autodespido, si concurren sus causales y requisitos',['La renuncia pura y simple necesariamente','La prescripción adquisitiva','La huelga individual'],'El autodespido permite al trabajador terminar por incumplimientos del empleador tipificados legalmente.','Código del Trabajo, art. 171');
  add('DLA-09','¿Qué finalidad tiene la nulidad del despido asociada a cotizaciones previsionales impagas en los casos legales?','Incentivar regularización previsional mediante los efectos remuneracionales que establece la ley hasta la convalidación',['Declarar inexistente toda relación laboral','Imponer pena criminal automática al empleador','Eliminar la deuda previsional'],'La denominada nulidad del despido tiene un régimen específico ligado al entero de cotizaciones.','Ley N° 19.631; Código del Trabajo');
  add('DLA-09','¿Qué efecto jurídico tiene un finiquito válidamente celebrado respecto de materias comprendidas sin reserva?','Puede producir efecto liberatorio en el ámbito efectivamente acordado, según sus requisitos, texto y circunstancias',['Extingue cualquier derecho imaginable aunque no esté comprendido','Impide siempre discutir vicios del consentimiento','Carece de cualquier valor jurídico'],'El efecto liberatorio del finiquito se interpreta según su contenido y validez; una reserva puede delimitar materias no liberadas.','Código del Trabajo; jurisprudencia sobre finiquito');
  add('DLA-09','Un trabajador goza de fuero y el empleador desea despedirlo por una causal que exige autorización previa. ¿Qué procedimiento debe seguir?','Solicitar desafuero judicial y obtener autorización antes de despedir cuando la ley así lo exige',['Despedir primero y pedir autorización años después','Solicitar permiso a otro trabajador','Ignorar el fuero si existe carta escrita'],'El fuero limita la facultad de despido y exige intervención judicial en los supuestos legales.','Código del Trabajo, fuero y desafuero');

  // DLA-10 Teletrabajo
  add('DLA-10','¿Qué debe contener un acuerdo de trabajo a distancia o teletrabajo?','Las estipulaciones que el Código del Trabajo exige sobre modalidad, lugar, jornada o exclusión, control y demás aspectos aplicables',['Una renuncia general a seguridad y salud','La transferencia al trabajador de todos los costos sin límite legal','Sólo la dirección de correo electrónico'],'El teletrabajo tiene regulación contractual específica y deberes de registro y protección.','Código del Trabajo, trabajo a distancia y teletrabajo');
  add('DLA-10','¿Quién mantiene deberes de protección de seguridad y salud en teletrabajo?','El empleador conserva las obligaciones legales de protección, adaptadas a la modalidad',['Nadie, porque el domicilio es ajeno al derecho laboral','Exclusivamente el trabajador','La empresa de internet'],'El trabajo remoto no elimina el deber general de protección.','Código del Trabajo; normativa de seguridad y salud en teletrabajo');
  add('DLA-10','¿Qué busca proteger el derecho a desconexión en los casos en que procede?','Un período en que el trabajador no esté obligado a responder comunicaciones u órdenes laborales, conforme al régimen legal',['La facultad de ausentarse indefinidamente','La prohibición absoluta de usar tecnología','El derecho del empleador a contactar sin límite'],'La desconexión protege descanso y límites temporales en modalidades remotas.','Código del Trabajo, teletrabajo');
  add('DLA-10','¿Puede el teletrabajo utilizarse para excluir al trabajador de derechos colectivos o de protección laboral?','No; la modalidad no elimina los derechos laborales que correspondan',['Sí; el teletrabajador deja de ser trabajador','Sí; se transforma en prestador civil por definición','No; porque todo teletrabajo exige sindicato obligatorio'],'El lugar o modalidad de prestación no suprime el estatuto laboral aplicable.','Código del Trabajo, teletrabajo');

  // DLA-11 Libertad sindical
  add('DLA-11','¿Qué comprende la libertad sindical en su dimensión individual?','La facultad de constituir sindicatos, afiliarse, desafiliarse y no ser obligado a pertenecer, dentro del marco legal',['La obligación de afiliarse al sindicato mayoritario','La prohibición de renunciar a un sindicato','La facultad empresarial de escoger afiliaciones'],'La libertad sindical protege decisiones individuales de asociación y participación.','Constitución Política de la República; Código del Trabajo');
  add('DLA-11','¿Qué protege la dimensión colectiva de libertad sindical?','La autonomía de las organizaciones para organizarse, representar intereses y desarrollar actividad sindical dentro de la ley',['La dependencia jerárquica del sindicato respecto del empleador','La prohibición de negociar colectivamente','La administración empresarial de los fondos sindicales'],'La autonomía sindical es una garantía constitucional y legal.','Constitución Política de la República; Código del Trabajo; Convenios OIT pertinentes');
  add('DLA-11','Una empresa amenaza con despedir a quienes se afilien a un sindicato. ¿Qué derecho resulta comprometido?','La libertad sindical y la prohibición de prácticas antisindicales',['La propiedad inmueble','La competencia de familia','La prescripción civil'],'Las represalias por afiliación pueden constituir lesión de libertad sindical y práctica antisindical.','Código del Trabajo, libertad sindical y prácticas antisindicales');
  add('DLA-11','¿Puede un convenio individual válidamente eliminar el derecho constitucional a libertad sindical?','No; la autonomía individual no puede renunciar anticipadamente a garantías indisponibles en contravención de la ley',['Sí; basta una cláusula en el contrato','Sí; si aumenta la remuneración','No; porque ningún derecho laboral admite regulación legal'],'La libertad sindical tiene protección constitucional y legal indisponible en su núcleo.','Constitución Política de la República; Código del Trabajo');

  // DLA-12 Organizaciones sindicales
  add('DLA-12','¿Qué debe verificarse para constituir válidamente una organización sindical?','El cumplimiento de quórum, asamblea, estatutos y formalidades previstas por el Código del Trabajo',['La autorización discrecional del empleador','La existencia de una sentencia judicial previa','La aprobación unánime de todos los trabajadores de la empresa'],'La constitución sindical está reglada y no depende del permiso del empleador.','Código del Trabajo, organizaciones sindicales');
  add('DLA-12','¿Qué función cumplen los estatutos sindicales?','Regular organización y funcionamiento interno dentro de la ley y la autonomía sindical',['Permitir infringir normas imperativas laborales','Transferir la administración al empleador','Sustituir la Constitución'],'Los estatutos expresan autonomía interna bajo el marco legal.','Código del Trabajo, sindicatos');
  add('DLA-12','¿Qué protección puede corresponder a dirigentes sindicales en el ejercicio de su función?','Fuero y permisos u otras garantías en los casos y términos establecidos por la ley',['Inmunidad penal absoluta','Propiedad sobre bienes de la empresa','Exención de toda obligación laboral sin límite'],'Las garantías sindicales buscan permitir actividad representativa sin represalias.','Código del Trabajo, dirigentes sindicales');
  add('DLA-12','¿Puede el empleador intervenir en la administración interna de un sindicato para decidir sus autoridades?','No; ello vulneraría la autonomía sindical y puede configurar una práctica antisindical',['Sí; por ser titular de la empresa','Sí; siempre que financie actividades','No; pero sólo durante una huelga'],'La organización sindical debe ser independiente del empleador.','Código del Trabajo; libertad sindical');

  // DLA-13 Negociación colectiva
  add('DLA-13','¿Qué finalidad tiene la negociación colectiva?','Permitir que trabajadores organizados y empleador acuerden condiciones comunes de trabajo y remuneración dentro del marco legal',['Sustituir toda ley laboral por acuerdo','Resolver delitos cometidos en la empresa','Transferir propiedad de la empresa a los trabajadores'],'Es un mecanismo colectivo de determinación de condiciones laborales.','Constitución Política de la República; Código del Trabajo, negociación colectiva');
  add('DLA-13','Antes de iniciar una negociación colectiva reglada, ¿qué debe identificarse?','Sujetos habilitados, oportunidad, instrumento vigente y reglas de procedimiento aplicables',['Sólo el número de trabajadores de la región','La opinión de clientes de la empresa','La autorización de un tribunal penal'],'El Código establece sujetos, plazos y etapas para negociación reglada.','Código del Trabajo, Libro IV');
  add('DLA-13','¿Qué efecto tiene un instrumento colectivo respecto de quienes quedan afectos a él?','Regula condiciones comunes durante su vigencia en los términos legales y contractuales aplicables',['Deroga permanentemente toda legislación laboral','Se aplica automáticamente a cualquier persona ajena sin regla legal','Carece de fuerza obligatoria'],'Los instrumentos colectivos generan obligaciones durante su vigencia dentro del marco legal.','Código del Trabajo, instrumentos colectivos');
  add('DLA-13','¿Puede una cláusula individual posterior empeorar válidamente condiciones establecidas por un instrumento colectivo vigente para el trabajador afecto?','Debe respetarse la fuerza del instrumento colectivo y las reglas legales sobre relación entre instrumentos y contratos individuales',['Sí; el contrato individual siempre prevalece aunque empeore','Sí; basta decisión unilateral del empleador','No; porque nunca puede modificarse ninguna condición individual aunque mejore'],'La relación entre contrato individual e instrumento colectivo está regulada y protege el contenido colectivo aplicable.','Código del Trabajo, negociación colectiva');

  // DLA-14 Huelga/tutela libertad sindical
  add('DLA-14','¿Qué debe determinarse para ejercer una huelga dentro de negociación colectiva reglada?','La etapa del procedimiento, votación, quórum y demás requisitos establecidos por la legislación vigente',['Sólo la voluntad de una persona','La autorización unilateral del empleador','La existencia de una sentencia civil firme'],'La huelga está constitucional y legalmente regulada con procedimiento específico.','Constitución Política de la República; Código del Trabajo, huelga');
  add('DLA-14','¿Puede el empleador realizar conductas destinadas a impedir ilegítimamente el ejercicio de libertad sindical durante una huelga?','No; esas conductas pueden constituir prácticas antisindicales o desleales según el caso',['Sí; la huelga suspende todos los derechos fundamentales','Sí; cualquier represalia es lícita','No; porque el empleador carece de cualquier derecho durante la huelga'],'El conflicto colectivo sigue sometido a reglas de buena fe y tutela de libertad sindical.','Código del Trabajo, prácticas antisindicales y desleales');
  add('DLA-14','¿Qué finalidad tienen los servicios mínimos y equipos de emergencia cuando legalmente proceden?','Atender bienes jurídicos y necesidades cuya protección justifica continuidad acotada durante la huelga, sin vaciar el derecho',['Mantener íntegramente toda producción como si no hubiera huelga','Reemplazar a todos los huelguistas','Prohibir la negociación colectiva'],'El régimen equilibra ejercicio de huelga con protección de bienes definidos por la ley.','Código del Trabajo, servicios mínimos');
  add('DLA-14','Una vulneración de libertad sindical ocurre fuera de un despido. ¿Puede ser objeto de tutela jurisdiccional?','Sí, si encuadra en los mecanismos legales de tutela de libertad sindical',['No; sólo existe protección si hay despido','No; la libertad sindical carece de tutela judicial','Sí; pero únicamente ante la Contraloría'],'La libertad sindical cuenta con acciones y procedimientos de protección específicos.','Código del Trabajo, tutela de libertad sindical');

  // DLA-15 Prácticas desleales
  add('DLA-15','Un empleador entrega beneficios selectivos para desincentivar la afiliación sindical durante una negociación. ¿Qué debe analizarse?','Si la conducta configura práctica antisindical o desleal atendidos finalidad, contexto y tipo legal',['Sólo si existe un delito penal','La propiedad del beneficio','La competencia civil sobre donaciones'],'Las conductas que interfieren ilegítimamente con libertad sindical o negociación pueden ser sancionadas.','Código del Trabajo, prácticas antisindicales y desleales');
  add('DLA-15','¿Quiénes pueden cometer prácticas desleales en negociación colectiva?','Los sujetos que la ley contempla, incluidos empleador, trabajadores u organizaciones según la conducta tipificada',['Exclusivamente el empleador en cualquier hipótesis','Sólo autoridades públicas','Nadie, porque no existen sanciones colectivas'],'El Código tipifica conductas reprochables de distintos intervinientes.','Código del Trabajo, Libro IV');
  add('DLA-15','¿Qué debe acreditarse para sancionar una práctica desleal?','Los hechos constitutivos de una conducta descrita por la ley y los elementos que ésta exige, respetando debido proceso',['Sólo que una parte se sienta perjudicada','La existencia de negociación colectiva como responsabilidad automática','Una presunción irrebatible contra quien tenga más poder económico'],'La sanción requiere subsumir hechos en una hipótesis legal.','Código del Trabajo, prácticas desleales');
  add('DLA-15','¿Qué finalidad tiene la tutela frente a prácticas antisindicales?','Restablecer el ejercicio efectivo de libertad sindical y aplicar las consecuencias legales frente a interferencias ilegítimas',['Eliminar toda facultad empresarial','Convertir el sindicato en órgano estatal','Resolver exclusivamente conflictos individuales de remuneración'],'La respuesta judicial busca cesar y reparar la lesión y sancionar según el régimen aplicable.','Código del Trabajo, prácticas antisindicales');

  // DPL-01 Competencia laboral
  add('DPL-01','Un trabajador demanda remuneraciones adeudadas derivadas de su contrato. ¿Qué tribunal resulta, en principio, competente por materia?','El tribunal laboral competente conforme a las reglas del Código del Trabajo y organización judicial',['El Tribunal Constitucional','La Contraloría General de la República','Un juzgado de policía local por regla general'],'Los conflictos derivados de relaciones laborales están entregados a tribunales laborales en los casos definidos por ley.','Código del Trabajo; Código Orgánico de Tribunales');
  add('DPL-01','Antes de presentar una demanda laboral, ¿qué reglas de competencia deben revisarse?','La competencia material y territorial y las opciones que la ley reconozca al demandante',['Sólo el domicilio del abogado','La cuantía civil como criterio único','La elección irrestricta de cualquier tribunal del país'],'La competencia laboral tiene reglas específicas que deben aplicarse al conflicto.','Código del Trabajo, competencia');
  add('DPL-01','Una controversia deriva directamente de la aplicación de normas laborales entre empleador y trabajador. ¿Puede una cláusula contractual desplazar libremente la competencia legal hacia cualquier tribunal civil?','No; la competencia jurisdiccional laboral se rige por normas legales y no queda a libre disposición en cualquier caso',['Sí; basta una cláusula estándar','Sí; la autonomía contractual es ilimitada','No; porque todo conflicto laboral debe ir a arbitraje'],'La competencia de los tribunales laborales es materia reglada.','Código del Trabajo; Código Orgánico de Tribunales');
  add('DPL-01','En una demanda existen pretensiones laborales y previsionales relacionadas. ¿Qué debe hacer quien determina competencia?','Identificar la naturaleza de cada pretensión y las reglas especiales de competencia y acumulación aplicables',['Enviar siempre todo a un tribunal penal','Elegir el tribunal por el monto más alto sin revisar materia','Dividir obligatoriamente toda pretensión aunque la ley permita acumulación'],'La competencia depende de la materia y de las reglas que articulan tribunales laborales y de cobranza.','Código del Trabajo; Ley N° 20.022; Ley N° 20.023');

  // DPL-02 Orgánica
  add('DPL-02','¿Quién ejerce jurisdicción en un Juzgado de Letras del Trabajo?','El juez o los jueces del tribunal conforme a la organización legal',['El administrador del tribunal','Los funcionarios de atención de público','La Inspección del Trabajo'],'La gestión administrativa apoya al tribunal, pero la jurisdicción corresponde a jueces.','Código Orgánico de Tribunales; legislación orgánica laboral');
  add('DPL-02','¿Qué función cumple la administración del tribunal laboral?','Gestionar recursos y apoyo operativo sin ejercer la función jurisdiccional reservada a los jueces',['Modificar sentencias por eficiencia','Resolver recursos de nulidad','Fijar jurisprudencia obligatoria'],'El diseño orgánico separa administración y decisión jurisdiccional.','Código Orgánico de Tribunales');
  add('DPL-02','¿Qué característica procesal influyó en la organización moderna de los tribunales laborales?','Un modelo oral, concentrado y con soporte administrativo especializado',['Un sistema exclusivamente escrito y secreto','La ausencia de audiencias','La sustitución de jueces por mediadores privados'],'La reforma laboral articuló tribunales y unidades para una litigación predominantemente oral.','Código del Trabajo; legislación orgánica laboral');
  add('DPL-02','¿Puede un funcionario administrativo del tribunal dictar una sentencia definitiva por delegación del juez?','No; la potestad de juzgar corresponde al juez competente y no puede trasladarse a la administración del tribunal',['Sí; cualquier tarea jurisdiccional es delegable','Sí; si disminuye la carga de trabajo','No; porque los funcionarios no pueden realizar ninguna actuación administrativa'],'La jurisdicción es indelegable fuera de los mecanismos expresamente autorizados por el ordenamiento.','Constitución Política de la República; Código Orgánico de Tribunales');

  // DPL-03 Aplicación general
  add('DPL-03','¿Qué función cumple la audiencia preparatoria en el procedimiento laboral de aplicación general?','Depurar la controversia, promover conciliación, resolver cuestiones previas y determinar prueba para el juicio',['Recibir toda la prueba y dictar siempre sentencia inmediata','Ejecutar cotizaciones previsionales','Resolver exclusivamente recursos'],'La audiencia preparatoria concentra funciones de ordenación y preparación del juicio.','Código del Trabajo, procedimiento de aplicación general');
  add('DPL-03','¿Qué caracteriza la audiencia de juicio laboral?','La recepción concentrada de prueba, observaciones y actuaciones destinadas a dejar el asunto en estado de decisión',['La mediación administrativa previa como única actividad','La presentación inicial de la demanda','El cumplimiento forzado de sentencia como regla'],'El juicio oral laboral concentra prueba y debate ante el juez.','Código del Trabajo, procedimiento laboral');
  add('DPL-03','Un trabajador presenta demanda fuera del plazo de caducidad aplicable a la acción ejercida. ¿Qué debe hacer el tribunal?','Aplicar el régimen legal de caducidad, considerando hechos que suspenden o amplían el plazo cuando la ley los contempla',['Ignorar todo plazo por tratarse de derechos laborales','Aplicar siempre prescripción civil de cinco años','Convertir la demanda en reclamo administrativo'],'Los plazos de caducidad laboral son especiales y deben calcularse con precisión.','Código del Trabajo, acciones por terminación');
  add('DPL-03','¿Qué criterio rige la valoración de prueba en el proceso laboral?','La sana crítica, expresando razones jurídicas, lógicas, científicas, técnicas o de experiencia pertinentes',['Tarifa legal absoluta para toda prueba','Convicción secreta sin motivación','La preferencia por la prueba del empleador'],'El Código del Trabajo adopta sana crítica y exige fundamentación.','Código del Trabajo, prueba y sentencia');

  // DPL-04 Recursos
  add('DPL-04','¿Qué recurso extraordinario procede contra determinadas sentencias definitivas laborales por las causales que establece el Código?','El recurso de nulidad laboral',['La casación civil como regla ordinaria','La reposición administrativa','La protección como sustituto universal'],'El sistema laboral contempla recurso de nulidad sujeto a causales, plazo y formalidades.','Código del Trabajo, recursos');
  add('DPL-04','¿Qué finalidad tiene el recurso de unificación de jurisprudencia?','Obtener un pronunciamiento de la Corte Suprema cuando existen distintas interpretaciones sobre una materia de derecho bajo los requisitos legales',['Repetir íntegramente toda prueba de hechos','Sustituir cualquier apelación ordinaria','Impugnar actos administrativos sin relación laboral'],'La unificación busca uniformar interpretación jurídica en hipótesis legalmente acotadas.','Código del Trabajo, unificación de jurisprudencia');
  add('DPL-04','Antes de interponer nulidad laboral, ¿qué debe identificar el recurrente?','La causal legal específica, el vicio, su influencia sustancial y la petición concreta, además de cumplir plazo y preparación cuando corresponda',['Sólo el desacuerdo con el resultado','Cualquier argumento nuevo sin conexión con el juicio','La conveniencia económica del recurso'],'La nulidad laboral es de derecho estricto y exige fundamentación vinculada a causales legales.','Código del Trabajo, recurso de nulidad');
  add('DPL-04','¿Puede utilizarse un recurso para revalorar libremente toda la prueba como si existiera una segunda instancia plena?','No; el alcance de revisión depende del recurso y causal invocados y de las competencias del tribunal superior',['Sí; toda impugnación reabre completamente los hechos','Sí; la Corte siempre reemplaza al juez de juicio','No; porque ningún recurso laboral puede examinar prueba en ninguna hipótesis'],'El sistema recursivo laboral limita la revisión según causales y diseño legal.','Código del Trabajo, recursos');

  // DPL-05 Monitorio/tutela/reclamación multas
  add('DPL-05','¿Qué caracteriza al procedimiento monitorio laboral?','Un procedimiento simplificado para asuntos comprendidos por la ley, con etapas administrativas o judiciales y reglas especiales según el caso',['Un juicio penal abreviado','Un procedimiento reservado sólo a grandes empresas','Una ejecución previsional sin fase declarativa'],'El monitorio busca solución rápida de controversias de menor entidad dentro de sus presupuestos.','Código del Trabajo, procedimiento monitorio');
  add('DPL-05','En tutela de derechos fundamentales, ¿qué debe vincular el demandante?','La conducta denunciada con el derecho fundamental afectado y los hechos que permitan aplicar la distribución probatoria especial cuando corresponda',['Sólo el monto de la remuneración','La existencia de sindicato como requisito universal','Una sentencia penal previa'],'La tutela exige hechos de vulneración y contempla reglas probatorias propias.','Código del Trabajo, tutela laboral');
  add('DPL-05','¿Qué finalidad tiene la reclamación judicial de una multa administrativa laboral?','Permitir control jurisdiccional de la sanción impuesta por la autoridad administrativa bajo el procedimiento y plazo legal',['Transformar la multa en una pena privativa de libertad','Impedir todo control de la Inspección del Trabajo','Resolver una negociación colectiva'],'El empleador sancionado dispone de vías de impugnación administrativa o judicial conforme al régimen legal.','Código del Trabajo, reclamación de multas');
  add('DPL-05','¿Puede confundirse el procedimiento monitorio con tutela laboral sólo porque ambos pueden tramitarse ante tribunal del trabajo?','No; tienen objeto, presupuestos, reglas y finalidades procesales diferentes',['Sí; son procedimientos idénticos','Sí; toda demanda monitoria alega derechos fundamentales','No; porque la tutela corresponde a tribunales civiles'],'La elección de procedimiento depende de la pretensión y estatuto aplicable.','Código del Trabajo, procedimientos especiales');

  // DPL-06 Cobranza
  add('DPL-06','Existe una sentencia laboral firme que ordena pagar sumas al trabajador y no se cumple voluntariamente. ¿Qué etapa debe activarse?','La ejecución o cobranza laboral conforme al régimen aplicable',['Un nuevo juicio declarativo idéntico como única vía','Una investigación penal automática','Una mediación familiar'],'Las obligaciones reconocidas en títulos laborales se ejecutan mediante procedimientos de cobranza especializados.','Código del Trabajo; Ley N° 20.023');
  add('DPL-06','¿Qué finalidad tiene el procedimiento de cobranza laboral y previsional?','Obtener cumplimiento forzado y oportuno de obligaciones laborales o previsionales incorporadas en títulos ejecutivos reconocidos por la ley',['Reabrir el debate declarativo sin límites','Determinar responsabilidad penal del empleador como único fin','Negociar contratos colectivos'],'La Ley N° 20.023 fortaleció ejecución especializada de créditos laborales y previsionales.','Ley N° 20.023');
  add('DPL-06','Antes de despachar ejecución por cotizaciones previsionales, ¿qué debe verificarse?','La existencia de un título ejecutivo previsional y los demás presupuestos legales de la cobranza',['Sólo la afirmación verbal del trabajador','La existencia de una querella penal','La propiedad de bienes inmuebles del empleador'],'La ejecución requiere título y obligación exigible dentro del régimen especial.','Ley N° 17.322; Ley N° 20.023');
  add('DPL-06','¿Por qué el procedimiento de cobranza no debe utilizarse para resolver una controversia compleja sobre existencia misma de la relación laboral que aún no ha sido declarada?','Porque la ejecución presupone un título y una obligación ejecutable; una controversia declarativa puede requerir el procedimiento correspondiente antes de cobrar',['Porque los tribunales laborales nunca pueden declarar relaciones laborales','Porque toda relación se presume inexistente','Porque la cobranza sólo procede respecto de multas penales'],'Debe distinguirse fase declarativa de fase ejecutiva.','Código del Trabajo; Ley N° 20.023');

  return out;
})();
