/* Blueprint de cobertura PF93.
 * Fuente de estructura: Temario PF especial aplicable desde PF N°93.
 * Cupos: convocatoria docente 2026 para confección de preguntas de selección múltiple.
 * IMPORTANTE: los 451 cupos representan el universo encargado a docentes y NO equivalen
 * a una distribución oficial publicada para las 90 preguntas de una aplicación concreta.
 */
const PF93_BLUEPRINT_VERSION = '2026-09-09-review-1';
const PF93_BLUEPRINT = [
  ['DCO-01','DCO','comun','Derecho constitucional','Bases de la institucionalidad',4],
  ['DCO-02','DCO','comun','Derecho constitucional','Funciones estatales: administrativa, legislativa, judicial y contralora',4],
  ['DCO-03','DCO','comun','Derecho constitucional','Forma de gobierno y forma de Estado',4],
  ['DCO-04','DCO','comun','Derecho constitucional','Poder Ejecutivo: atribuciones y potestad reglamentaria',4],
  ['DCO-05','DCO','comun','Derecho constitucional','Bases generales de la Administración del Estado',4],
  ['DCO-06','DCO','comun','Derecho constitucional','Principios constitucionales del Poder Judicial',4],
  ['DCO-07','DCO','comun','Derecho constitucional','Tribunal Constitucional y control de constitucionalidad',4],
  ['DCO-08','DCO','comun','Derecho constitucional','Derechos fundamentales: titulares, destinatarios, garantías, límites y conflictos',4],
  ['DCO-09','DCO','comun','Derecho constitucional','Acciones de amparo y de protección',4],

  ['DAD-01','DAD','comun','Derecho administrativo','Principio de legalidad y de juridicidad: potestades',4],
  ['DAD-02','DAD','comun','Derecho administrativo','Acto administrativo: efectos y vigencia',4],
  ['DAD-03','DAD','comun','Derecho administrativo','Procedimiento administrativo',4],
  ['DAD-04','DAD','comun','Derecho administrativo','Formas de control y revisión de los actos administrativos',4],
  ['DAD-05','DAD','comun','Derecho administrativo','Nulidad de derecho público',4],
  ['DAD-06','DAD','comun','Derecho administrativo','Contratación administrativa',4],
  ['DAD-07','DAD','comun','Derecho administrativo','Responsabilidad extracontractual de la Administración del Estado',4],

  ['DPO-01','DPO','comun','Derecho procesal orgánico','Organización de la administración de justicia',4],
  ['DPO-02','DPO','comun','Derecho procesal orgánico','Deberes, prohibiciones y responsabilidad de los jueces',4],
  ['DPO-03','DPO','comun','Derecho procesal orgánico','Causales de implicancia y recusación',4],
  ['DPO-04','DPO','comun','Derecho procesal orgánico','Competencia',4],
  ['DPO-05','DPO','comun','Derecho procesal orgánico','Jurisdicción y equivalentes jurisdiccionales',4],

  ['DCI-01','DCI','civil','Derecho civil','Acto jurídico',4],
  ['DCI-02','DCI','civil','Derecho civil','Bienes: clasificaciones',4],
  ['DCI-03','DCI','civil','Derecho civil','Propiedad: modos de adquirir el dominio',4],
  ['DCI-04','DCI','civil','Derecho civil','Teoría de la posesión inscrita',4],
  ['DCI-05','DCI','civil','Derecho civil','Limitaciones a los derechos reales',4],
  ['DCI-06','DCI','civil','Derecho civil','Acciones posesorias y reivindicatorias',4],
  ['DCI-07','DCI','civil','Derecho civil','Obligaciones',5],
  ['DCI-08','DCI','civil','Derecho civil','Teoría general de los contratos',4],
  ['DCI-09','DCI','civil','Derecho civil','Contratos en particular',4],
  ['DCI-10','DCI','civil','Derecho civil','Responsabilidad civil contractual y extracontractual',5],
  ['DCI-11','DCI','civil','Derecho civil','Sucesión por causa de muerte',4],
  ['DCI-12','DCI','civil','Derecho civil','Matrimonio y AUC: régimen patrimonial, bienes familiares, compensación y término',4],
  ['DCI-13','DCI','civil','Derecho civil','Filiación: prueba, efectos y acciones',4],

  ['DPC-01','DPC','civil','Derecho procesal civil','El proceso: principios formativos y actos procesales',4],
  ['DPC-02','DPC','civil','Derecho procesal civil','Efectos del proceso y cosa juzgada',4],
  ['DPC-03','DPC','civil','Derecho procesal civil','Reglas comunes a todo procedimiento',5],
  ['DPC-04','DPC','civil','Derecho procesal civil','Procedimiento declarativo ordinario: discusión, emplazamiento y conciliación',5],
  ['DPC-05','DPC','civil','Derecho procesal civil','La prueba',4],
  ['DPC-06','DPC','civil','Derecho procesal civil','La sentencia',4],
  ['DPC-07','DPC','civil','Derecho procesal civil','Incidentes',4],
  ['DPC-08','DPC','civil','Derecho procesal civil','Medidas cautelares y prejudiciales',4],
  ['DPC-09','DPC','civil','Derecho procesal civil','Juicios especiales: ejecutivo y sumario',5],
  ['DPC-10','DPC','civil','Derecho procesal civil','Recursos procesales',4],

  ['DPP-01','DPP','penal','Derecho procesal penal','Principios y garantías del proceso penal',5],
  ['DPP-02','DPP','penal','Derecho procesal penal','Sujetos e intervinientes',5],
  ['DPP-03','DPP','penal','Derecho procesal penal','Procedimiento penal: formas de inicio y desarrollo',4],
  ['DPP-04','DPP','penal','Derecho procesal penal','Formalización y desarrollo de la investigación',4],
  ['DPP-05','DPP','penal','Derecho procesal penal','Medidas cautelares',4],
  ['DPP-06','DPP','penal','Derecho procesal penal','Nulidad procesal',4],
  ['DPP-07','DPP','penal','Derecho procesal penal','Salidas alternativas',4],
  ['DPP-08','DPP','penal','Derecho procesal penal','Cierre de la investigación y etapa intermedia',4],
  ['DPP-09','DPP','penal','Derecho procesal penal','Prueba en el proceso penal',4],
  ['DPP-10','DPP','penal','Derecho procesal penal','APJO, juicio oral y sentencia',4],
  ['DPP-11','DPP','penal','Derecho procesal penal','Recursos: nulidad, apelación, reposición y revisión',4],
  ['DPP-12','DPP','penal','Derecho procesal penal','Procedimientos especiales: abreviado, monitorio y simplificado',4],
  ['DPP-13','DPP','penal','Derecho procesal penal','Acción civil en el proceso penal',4],

  ['DPE-01','DPE','penal','Derecho penal','Principios y límites al ius puniendi',5],
  ['DPE-02','DPE','penal','Derecho penal','Aplicación de la ley penal en el tiempo y espacio',4],
  ['DPE-03','DPE','penal','Derecho penal','Tipicidad y clasificación de tipos',4],
  ['DPE-04','DPE','penal','Derecho penal','Causalidad e imputación objetiva',4],
  ['DPE-05','DPE','penal','Derecho penal','Antijuridicidad y causas de justificación',4],
  ['DPE-06','DPE','penal','Derecho penal','Culpabilidad: dolo, imprudencia, error y exculpación',4],
  ['DPE-07','DPE','penal','Derecho penal','Concurso de delitos',4],
  ['DPE-08','DPE','penal','Derecho penal','Autoría y participación',4],
  ['DPE-09','DPE','penal','Derecho penal','Grados de desarrollo del delito',4],
  ['DPE-10','DPE','penal','Derecho penal','Determinación de la pena y circunstancias modificatorias',4],
  ['DPE-11','DPE','penal','Derecho penal','Delitos contra la vida y la salud',5],
  ['DPE-12','DPE','penal','Derecho penal','Delitos contra la libertad e indemnidad sexual',5],
  ['DPE-13','DPE','penal','Derecho penal','Hurto, robo y estafa',5],

  ['DFA-01','DFA','familia','Derecho de familia','Matrimonio y AUC: requisitos, efectos y causales de término',5],
  ['DFA-02','DFA','familia','Derecho de familia','Compensación económica',5],
  ['DFA-03','DFA','familia','Derecho de familia','Bienes familiares',4],
  ['DFA-04','DFA','familia','Derecho de familia','Regímenes patrimoniales del matrimonio y AUC',4],
  ['DFA-05','DFA','familia','Derecho de familia','Divorcio',4],
  ['DFA-06','DFA','familia','Derecho de familia','Filiación y acciones de filiación',4],
  ['DFA-07','DFA','familia','Derecho de familia','Adopción',4],
  ['DFA-08','DFA','familia','Derecho de familia','Derecho de alimentos',4],
  ['DFA-09','DFA','familia','Derecho de familia','Cuidado personal',4],
  ['DFA-10','DFA','familia','Derecho de familia','Relación directa y regular',4],

  ['DPFA-01','DPFA','familia','Derecho procesal de familia','Principios y fundamentos del procedimiento de familia',4],
  ['DPFA-02','DPFA','familia','Derecho procesal de familia','Tribunales, unidades operativas y Consejo Técnico',4],
  ['DPFA-03','DPFA','familia','Derecho procesal de familia','Sistema de mediación familiar',4],
  ['DPFA-04','DPFA','familia','Derecho procesal de familia','Reglas comunes y rol del juez',4],
  ['DPFA-05','DPFA','familia','Derecho procesal de familia','Procedimiento ordinario de familia',4],
  ['DPFA-06','DPFA','familia','Derecho procesal de familia','VIF, protección NNA y procedimiento contravencional',4],
  ['DPFA-07','DPFA','familia','Derecho procesal de familia','Prueba en materia de familia',4],
  ['DPFA-08','DPFA','familia','Derecho procesal de familia','Sistema de recursos',4],

  ['DLA-01','DLA','laboral','Derecho del trabajo','Derechos fundamentales en el trabajo',5],
  ['DLA-02','DLA','laboral','Derecho del trabajo','Sujetos del contrato y subordinación/dependencia',4],
  ['DLA-03','DLA','laboral','Derecho del trabajo','Tercerización, subcontratación y suministro',4],
  ['DLA-04','DLA','laboral','Derecho del trabajo','Poder y facultades del empleador',4],
  ['DLA-05','DLA','laboral','Derecho del trabajo','Contrato de trabajo',4],
  ['DLA-06','DLA','laboral','Derecho del trabajo','Jornada de trabajo',4],
  ['DLA-07','DLA','laboral','Derecho del trabajo','Protección a las remuneraciones',4],
  ['DLA-08','DLA','laboral','Derecho del trabajo','Protección al trabajador, maternidad, paternidad y vida familiar',4],
  ['DLA-09','DLA','laboral','Derecho del trabajo','Terminación, autodespido, nulidad, finiquito, fuero e indemnizaciones',5],
  ['DLA-10','DLA','laboral','Derecho del trabajo','Teletrabajo o trabajo a distancia',4],
  ['DLA-11','DLA','laboral','Derecho del trabajo','Derecho sindical constitucional y libertad sindical',4],
  ['DLA-12','DLA','laboral','Derecho del trabajo','Organizaciones sindicales',4],
  ['DLA-13','DLA','laboral','Derecho del trabajo','Negociación colectiva y contrato colectivo',4],
  ['DLA-14','DLA','laboral','Derecho del trabajo','Huelga y tutela de la libertad sindical',4],
  ['DLA-15','DLA','laboral','Derecho del trabajo','Prácticas desleales e infracciones en negociación colectiva',4],

  ['DPL-01','DPL','laboral','Derecho procesal del trabajo','Competencia de los tribunales del trabajo',4],
  ['DPL-02','DPL','laboral','Derecho procesal del trabajo','Aspectos orgánicos del tribunal de letras del trabajo',4],
  ['DPL-03','DPL','laboral','Derecho procesal del trabajo','Procedimiento de aplicación general declarativo',4],
  ['DPL-04','DPL','laboral','Derecho procesal del trabajo','Sistema de recursos',4],
  ['DPL-05','DPL','laboral','Derecho procesal del trabajo','Monitorio, tutela y reclamación de multas',4],
  ['DPL-06','DPL','laboral','Derecho procesal del trabajo','Cobranza laboral y previsional (Ley N° 20.023)',4]
].map(([id,codigo,track,materia,tema,cupo]) => ({ id,codigo,track,materia,tema,cupo }));

if (PF93_BLUEPRINT.length !== 109) throw new Error('PF93 blueprint debe contener 109 temas');
if (PF93_BLUEPRINT.reduce((n,t) => n + t.cupo, 0) !== 451) throw new Error('PF93 blueprint debe sumar 451 cupos');
